### ISSUE TITLE
GPU support?

### ISSUE THREAD

**Issue by EddieOne** [google-research/text-to-text-transfer-transformer#1]
This looks amazing. Would it be too slow to run of GPUs?

**Comment by adarob** [comment]
The larger models won't fit on a single GPU. You could try running multiple GPUs or using one of the smaller models. We have not attempted this yet ourselves, but it is on our list.

@sharannarang

**Comment by EddieOne** [comment]
Thank you, for the information.

**Comment by snowpeakz** [comment]
@adarob 
hi, I'm now trying to run t5_mesh_transformer on GPUs, It is going to downgrade automatically to GPU when setting options about TPU (e.g. tpu_job_name, tpu, gcp_project, tpu_zone) None, is that right?
Thanks!

**Comment by GrahamboJangles** [comment]
@adarob What about a Colab TPU?

**Comment by adarob** [comment]
I have not had a chance to look at GPU support but I have successfully
finetuned the 3B parameter model on a Colab TPU. We need to wait until one
of the Cloud binaries are updated before this will work externally,
however. Stay tuned!

**Comment by GrahamboJangles** [comment]
@adarob That's awesome! Can you drop a link to a Colab notebook when you get the chance?

**Comment by loretoparisi** [comment]
@adarob did you use the pre-trained model or a smaller one? Thanks.

**Comment by emiydulce** [comment]
Archivos

**Comment by adarob** [comment]
https://tiny.cc/t5-colab
