### ISSUE TITLE
Proto duplication

### ISSUE THREAD

**Issue by jarney1** [google-research/text-to-text-transfer-transformer#10]
Hi there,

I'm trying to fine tune a model on my own dataset, running on a GCP TPU. After following the setup instructions and installing t5 on the VM instance, i run into the following error when trying to execute t5_mesh_transformer:

TypeError: Conflict register for file "tensorboard/compat/proto/tensor_shape.proto": tensorboard.TensorShapeProto is already defined in file "tensorboard/src/tensor_shape.proto". Please fix the conflict by adding package name on the proto file, or use different name for the duplication.

Thanks in advance for any help you can give,
James

**Comment by craffel** [comment]
As a first guess maybe something is up with your TensorFlow version? What do you get when you run
`python -c "import tensorflow; print(tensorflow.__version__)"`
?

**Comment by jarney1** [comment]
Thanks, for your reply. It seems the version is **version 1.15.0**

Having included the flag **--tf-version=1.15.dev20190821** in the TPU setup, should i expect to have a version with that exact name? i.e. **1.15.dev20190821**

Also just to check, I installed T5 with 'pip3 install t5[gcp]' as opposed to 'pip intstall...' in the documentation, I'm assuming python 3 is what I'm supposed to be using?

**Comment by craffel** [comment]
Yes, that's the right version and was installed correctly, and it doesn't need to match the TPU. Does TensorFlow work at all for you? If not I'd suggest opening an issue on the TF GitHub because I've never seen this before and am not sure how to help.

**Comment by anatoly-khomenko** [comment]
@jarney1 ,

I have encountered the same issue. The workaround I have found for now is using pre-built image from google (Debian 9 with Tensorflow 1.15 nightly or 1.15.20190821) and **not** creating virtual environment for T5 installation.
So I have created an instance and straight away run:

`pip3 install t5[gcp]`

After that I had to fix 2 issues:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mesh_transformer_main.py#L116
change FLAGS.tfds_data_dir to FLAGS.t5_tfds_data_dir

https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/evaluation/metrics.py#L26
change allennlp.tools to allennlp.common

I did it straightly using nano on my file system. Will try to submit a pull request with these fixes here.

**Comment by craffel** [comment]
Hi, I think you are using an old version of allennlp, the squad_eval was moved to tools a year ago:
https://github.com/allenai/allennlp/commit/1691cb3a61740fbbc8305d52d4e830c79302a666
We will have a fix for the flag shortly, thanks for spotting that.

**Comment by anatoly-khomenko** [comment]
Hi @craffel ,

Thank you for the clarification, I'll update the package.
The point is that I have not installed the package myself, so probably the allennlp version requirements should be added to setup.py, as the old version is installed by default.

**Comment by tomekstarfunds** [comment]
Hi @craffel ,
I have this message when importing tensorboard in anaconda / Windows. I've upgraded allennlp and still have the same issue.
