### ISSUE TITLE
Dataset caching? 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#101]
TLDR; does the code cache datasets? 

I was using T5 and I realized that my dataset has a problem. So I updated it and re-uploaded it on my GC bucket. Now the issue is that I am not sure if the code is using my latest dataset (or it’s using the previous cached version)
Any ideas whether T5 does dataset caching somewhere? (if so, how to drop it?)

**Comment by adarob** [comment]
Caching does not happen automatically. If you did run the caching script, you have nothing to worry about.
