### ISSUE TITLE
Install dependency on `allennlp.tools` failing.

### ISSUE THREAD

**Issue by moscow25** [google-research/text-to-text-transfer-transformer#103]
Hi, apologies if I am the only one having this error -- surprised not to see anyone else report it.

It seem that installing from `pip3` I run into an error on `import t5` because of `from allennlp.tools import squad_eval` in `metrics.py` 
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/evaluation/metrics.py

Installing `allennlp` directly does appears to create this error, actually. As in their repo (at least the one via `pip install allennlp` -- the `allennlp.tools` is no longer built that way. It seems perhaps, they changed and broke your dependency?

Unfortunately, as far as I can tell `allennlp` does not do release versions. Not sure which checkpoint breaks this.

Apologies if this is my mistake. Will try rebuilding `allennlp` from an old commit and see if this works again. Thank you.

**Comment by craffel** [comment]
I'm not sure why they removed squad_eval.
https://github.com/allenai/allennlp/commit/bd9fea0a6797877444cc5bdf0a029454c3ee6132
Really we shouldn't be installing allennlp for this but unfortunately the SQuAD eval script is not on PIP otherwise AFAIK.

**Comment by adarob** [comment]
Maybe we should just copy the necessary functions into T5? It's definitely
overkill to install allennlp just for that anyways.
For now we, can pin to an older version of allennlp.

**Comment by craffel** [comment]
We can pull the code in but we'd have to put it in a separate third_party directory (like https://github.com/brain-research/realistic-ssl-evaluation/tree/master/third_party/vat) which is annoying.

**Comment by moscow25** [comment]
Thanks guys, yes `third_party` solution is never fun. Just wanted to note this issue. Looking forward to getting up to speed on other details of the repo and finetuning a large model :-)

**Comment by nasrinm** [comment]
Hi ... So is there a specific version of the allennlp package that works? if not, what's the exact checkpoint that we should download and build?

**Comment by adarob** [comment]
allennlp==0.9.0 should work
