### ISSUE TITLE
T5 and summarization

### ISSUE THREAD

**Issue by vprelovac** [google-research/text-to-text-transfer-transformer#104]
The announcement mentions use with summarization but the repo does not contain any information about it. Can you update the doc with an example to properly fine-tune on CNN/DM as well as post your results?

**Comment by craffel** [comment]
The results are in our paper (https://arxiv.org/abs/1910.10683). You can fine-tune and evaluate on CNN/DM using the cnn_dailymail_v002 task https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L141
