### ISSUE TITLE
Evaluating on validation data during training

### ISSUE THREAD

**Issue by NaxAlpha** [google-research/text-to-text-transfer-transformer#105]
Is it possible to do evaluation while training. 

I was trying to fine-tune model on a task but to see if it is overfitting, I had to incrementally train model for like 10k steps and then run evaluation etc. I would really love if it were possible to run evaluation on small validation dataset after certain number of steps. 

By looking at the [code of T5](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mtf_model.py#L202) and [mesh tensorflow](https://github.com/tensorflow/mesh/blob/63754cf4524cb96282ac0dfe453a15076a76589f/mesh_tensorflow/transformer/utils.py#L1064), I am not sure if it would be easy to support this feature. but i think using [estimator's train and evaluate api](https://www.tensorflow.org/api_docs/python/tf/estimator/train_and_evaluate) it may be possible. What are your thoughts on this? and Is there any plan to support this in near future?

Thanks

**Comment by craffel** [comment]
Hi Nauman, you can run an evaluation job in parallel to your training job:
https://github.com/google-research/text-to-text-transfer-transformer#eval
If you want it to watch the model directory for new checkpoints and eval the latest checkpoint as it appears, you can set 
``
  --gin_param="eval_checkpoint_step = None"
``
See https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py#L1202

If you are asking if there's a way to have the model train for N steps then eval all in one job/TPU, then no, this is not currently possible. It would be easy to script in a bash while loop though.
