### ISSUE TITLE
Creating MtfModel with GPU

### ISSUE THREAD

**Issue by thoughtsofacrow** [google-research/text-to-text-transfer-transformer#107]
We are trying to create a task, a model, and fine tune on a GPU:

```
[Some imports]
[Some constants defined here]

def create_task(name, dataset_fn):
  t5.data.TaskRegistry.add(
    name,
    # Supply a function which returns a tf.data.Dataset.
    dataset_fn=dataset_fn,
    splits=["train", "validation"],
    # Supply a function which preprocesses text from the tf.data.Dataset.
    text_preprocessor=None,
    # Use the same vocabulary that we used for pre-training.
    sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
    # Lowercase targets before computing metrics.
    postprocess_fn=t5.data.postprocessors.lower_text,
    # We'll use accuracy as our evaluation metric.
    metric_fns=[t5.evaluation.metrics.accuracy]
  )

def create_model():
  return t5.models.MtfModel(
    model_dir=MODEL_DIR,
    tpu=None,
    model_parallelism=1,
    batch_size=1,
    sequence_length=None,  # {"inputs": 128, "targets": 32},
    learning_rate_schedule=0.003,
    save_checkpoints_steps=50,
    keep_checkpoint_max=None,
    iterations_per_loop=100,
  )

gin.parse_config_file(os.path.join(PRETRAINED_DIR, 'operative_config.gin'))
create_task("s_test",s_dataset_fn)
test_model = create_model()

test_model.finetune(
    mixture_or_task_name="s_test",
    pretrained_model_dir=model.PRETRAINED_DIR,
    finetune_steps=FINETUNE_STEPS
)
```

Gin file includes the following (although given the comment below I think this is either the wrong way to do it or is currently being ignored):
```
run.mesh_shape = 'model:1,batch:1'
run.mesh_devices = ['gpu:0']
```

However, we are running into some issues with GPU support.
1. It is trying to run on our CPU and not our GPU
2. The "mesh shape" is being stuck on 8 which does work when we want the batch size to only be one.

We were looking at `mtf_model.py` to understand how to properly set these and saw on the todo:
```
# TODO(adarob): Allow setting mesh_shape and mesh_devices directly for GPU.
```

Does T5 currently not support GPU for the above approach? If it does, is there something that needs to be changed with this configuration to make sure that T5 is properly using our desired GPU and mesh shape?

Thank you!

**Comment by craffel** [comment]
The model API (`t5.models.MtfModel`) hardcodes a TPU mesh shape, so you can't use the model API with a GPU currently (that's what @adarob 's note is about). You need to call `utils.run` from the Mesh TF library directly, as is done here:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mesh_transformer_main.py#L203
That should respect the gin config values you have in your .gin file.

**Comment by adarob** [comment]
It's also quite easy to add this feature to MtfModel, although I can't do
it until next week.

**Comment by thoughtsofacrow** [comment]
Thank you. We are using `utils.run` for now and will look out for any changes to MtfModel.

**Comment by thoughtsofacrow** [comment]
Thank you both for quick responses and help.

We are currently using `utils.run` for now. It is now respecting our gin config values and using the GPU.

There is still however a problem - GPU usage never goes above 4% even during training and it is excruciatingly slow (1 step per minute). (It is however recognizing the card and allocating all available GPU memory).

Is it possible that the code is still not properly utilizing the GPU?

```
tf.compat.v1.enable_eager_execution()
gin.parse_config_file(os.path.join(model.PRETRAINED_DIR, 'operative_config.gin'))

ON_CLOUD = False
FINETUNE_STEPS = 25000
mixture_or_task_name = 's_test'
create_task.create_task(mixture_or_task_name, create_task.s_dataset_fn2)

# Using Mesh TF library
ckpt = tf.train.latest_checkpoint(model.PRETRAINED_DIR)
if ckpt is None:
    raise ValueError("No checkpoints found in model directory: %s" % model_dir)

checkpoint_step = int(re.sub(".*ckpt-", "", ckpt))
model_ckpt = "model.ckpt-" + str(checkpoint_step)
init_checkpoint = os.path.join(model.PRETRAINED_DIR, model_ckpt)

vocabulary = t5.data.get_mixture_or_task(mixture_or_task_name).get_vocabulary()
dataset_fn = functools.partial(
        t5.models.mesh_transformer.mesh_train_dataset_fn, mixture_or_task_name=mixture_or_task_name)

utils.run(
        tpu_job_name=None,
        tpu=None,
        gcp_project=None,
        tpu_zone=None,
        model_dir=model.MODEL_DIR,
        init_checkpoint=init_checkpoint,
        vocabulary=vocabulary,
        train_dataset_fn=dataset_fn,
        train_steps=(checkpoint_step + FINETUNE_STEPS)
)
```

(We will also test with the new update once it is merged and deployed)

**Comment by adarob** [comment]
If you are not using `mesh_shape` and `mesh_devices`, you are not actually using the GPU.

**Comment by thoughtsofacrow** [comment]
We are - our .gin file is the same as it was before:
```
run.mesh_shape = 'model:1,batch:1'
run.mesh_devices = ['gpu:0']
```
Is there somewhere else we should be specifying this?

**Comment by adarob** [comment]
I see. I'm not sure why it's not utilizing more of the GPU in this case. How expensive is your preprocessing? Is it using filtering?
