### ISSUE TITLE
Question about cross-node(multi-node) data parallelism on GPU

### ISSUE THREAD

**Issue by hwyFighting** [google-research/text-to-text-transfer-transformer#1101]
Hi! I would like to ask how to get t5 to train data in parallel across nodes on GPUs? 

Is there a corresponding solution in the case of mesh_tensorflow based? Or there is no corresponding design yet?

Thank you for your positive and exact reply!

**Comment by adarob** [comment]
See https://github.com/google-research/t5x#gpu-usage
