### ISSUE TITLE
Right to Left Languages: Arabic, Urdu & Hebrew

### ISSUE THREAD

**Issue by deepseek** [google-research/text-to-text-transfer-transformer#115]
@adarob @sharannarang @craffel 
Thank you for your hard word,

Regarding training RTL `Right to Left` languages, such as "Arabic, Urdu, Hebrew":
- Does this project support training RTL languages
- How do I train Urdu to Arabic translator
- How many lines of text are needed to produce a good neural translator model.

**Comment by craffel** [comment]
> Does this project support training RTL languages
In principle yes, but the vocabulary we are using only supports English, German and French. You'd need to create a new vocabulary based on some other text data.
> How do I train Urdu to Arabic translator
You'd need to collect a suitable training dataset; I'm not sure if one exists already or not.
> How many lines of text are needed to produce a good neural translator model.
It's hard to say. If you are training from scratch, probably on the order of hundreds of thousands of examples. If you are fine-tuning a pre-trained model, you may get better results from fewer examples (e.g. tens of thousands of examples).

**Comment by deepseek** [comment]
@craffel 

- How do I change the vocabulary
- what changes to the code should i make inorder to better integrate RTL languages

**Comment by craffel** [comment]
You can train a new SentencePiece model and supply it via the `sentencepiece_model_path` argument when constructing a Task.
