### ISSUE TITLE
Any plan for German Language? 

### ISSUE THREAD

**Issue by engrsfi** [google-research/text-to-text-transfer-transformer#116]
Is there any plan for releasing a German Language C4 dataset if any?

**Comment by craffel** [comment]
No, but it should be totally possible to fork the [C4 dataset creation code](https://github.com/tensorflow/datasets/blob/master/tensorflow_datasets/text/c4.py) from TFDS and set up the language detector for German, and then update some of the heuristic processing for German (e.g. using a German badwords list).
