### ISSUE TITLE
SelfAttention & EncDecAttention allow different dimensions for query, key and value

### ISSUE THREAD

**Issue by desperadoola** [google-research/text-to-text-transfer-transformer#120]
This paper [Low-Rank Bottleneck in Multi-head Attention Models](https://arxiv.org/pdf/2002.07028.pdf) suggests that we could fix the head size, increase the number of heads, and keep hidden dimensions unchanged. Could you support setting `d_k`, `d_q`, `d_v` independently instead of being bonded with `d_kv` and `d_model`?

**Comment by craffel** [comment]
Hi there, this should be possible - you could achieve this by writing a new version of the attention layers/functions in the Mesh TensorFlow Transformer example. It's not in scope for the T5 library.
