### ISSUE TITLE
`eval()` abruptly ends without an error message.

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#123]
While running the evaluation code: 

```python
   model.eval(
        mixture_or_task_name=mixture_name,
        checkpoint_steps=checkpoint_steps,
        summary_dir=summary_dir,
        split="dev"
    )
```
just few seconds after getting here, the program ends without any informative message. 

What can be the reason for this? 

 - In the past, I have noticed that specifying/dropping `split` change the behavior, although I don't understand why. It didn't make a difference this time. 
 - One hypothesis is that the evaluation code does not find any model. I have checked it and I think the address to the directory that contains the models is correct. 
 - Would be helpful to add logging here to inform the user about any unusual outcome.

**Comment by danyaljj** [comment]
Update: 

The issue was that when specifying the task, I did not have `dev` included in the `splits`. 
To be more concrete, had to change:
```python 
t5.data.TaskRegistry.add(
     ...
     splits=["train"],
    ...
)
```
to 
```python 
t5.data.TaskRegistry.add(
     ...
     splits=["train", "dev"],
    ...
)
```

This also explains my earlier observation: 
> In the past, I have noticed that specifying/dropping `split` change the behavior, although I don't understand why. It didn't make a difference this time. 


Leaving the issue if you want to add warning logs to the evaluation code.

**Comment by craffel** [comment]
There is a message logged when this happens:
https://github.com/google-research/text-to-text-transfer-transformer/blob/3de7b8baa99b87869eef1fe0195838458a59f900/t5/models/mesh_transformer.py#L136
It may be that your notebook is not set up to display INFO logs.
