### ISSUE TITLE
Question about the experiment on the text deshuffling objective.

### ISSUE THREAD

**Issue by MichaelZhouwang** [google-research/text-to-text-transfer-transformer#125]
Hi, I have several questions about the deshuffling experiment. First, when a text span in one example consists of multilple sentences, is the word shuffling done within the sentence or within the entire text span? Second, according to the experiment configuration, the pretraining is done with noisy ratio 1.0, that's to say, all the tokens are shuffled. Have you tried a lower noisy ratio for pretraining? Thanks.

**Comment by craffel** [comment]
> when a text span in one example consists of multilple sentences, is the word shuffling done within the sentence or within the entire text span? 

Within the entire text span.

> Have you tried a lower noisy ratio for pretraining?

No, but it would not be difficult to try this.
