### ISSUE TITLE
Question on Input Length

### ISSUE THREAD

**Issue by nickwalton** [google-research/text-to-text-transfer-transformer#130]
How does T5 handle longer input sequences? 

I read in another issue that with relative positional embeddings it can handle more than the 512 it was trained on, but how much would you expect quality to decrease as you increase the input sequence length arbitrary amounts?

**Comment by craffel** [comment]
We have trained on sequences of up to 2048 and it worked fine. Beyond that, things will start to get very slow and you will need a lot of memory to compute the full attention matrices.

**Comment by nickwalton** [comment]
Awesome thanks!
