### ISSUE TITLE
What is `use_model_api`? 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#141]
In the [export](https://github.com/google-research/text-to-text-transfer-transformer#export) model section there is a parameter `use_model_api`.  I looked around in the code but couldn't figure out what parameter does. Wondering if you clarify what this parameter does (and ideally clarify it in the readme as well to prevent future questions.)

**Comment by craffel** [comment]
It controls whether the t5_mesh_transformer binary uses the `MtfModel class` or calls `mesh_tensorflow.transformer.utils.run` directly. https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mesh_transformer_main.py#L71
The model API allows you to use less gin hackery, but some people like using gin hackery (or at least, there is plenty of legacy code that uses utils.run) so both modes need to be available.
There has been some discussion of removing this flag but I'm not sure that will happen.

**Comment by danyaljj** [comment]
Got it, thank you!
