### ISSUE TITLE
Regarding masking function

### ISSUE THREAD

**Issue by h19920918** [google-research/text-to-text-transfer-transformer#149]
@adarob Thank you for your quickly answer.

I don't understand one more thing in your code.

In 

https://github.com/google-research/text-to-text-transfer-transformer/blob/4598ccbda22ba051e565b8d13326afe1cbd1de33/t5/data/preprocessors.py#L2115,

you describe as below:

We want to generate training examples like
  "We hold X to be Y that Z" -> "X these truths Y self evident Z that"

In my assumption, its original sentence is "We hold these truths to be self evident that".
Following the 'T5' paper, it is converted as

Input: We hold X to be Y that
Target: X these truths Y self evident Z

I would like to know why the target has 'that'.
Additionally, in the language processing, there should be '(BOS)' and '(EOS)' tokens in the input and target.

In my best knowledge, the input and target will be

Input: We hold X to be Y that (EOS)
target: (BOS) X these truths Y self evident Z (EOS)

Is my assumption correct?

_Originally posted by @h19920918 in https://github.com/google-research/text-to-text-transfer-transformer/issues/147#issuecomment-607605929_

**Comment by craffel** [comment]
Yes, there is a typo in the docstring, the "that" should not be there at the end of the target.

The token sequences will eventually have EOS and BOS tokens added; the example is just to illustrate what the function does, not the actual token sequences that result at the end of our data pipeline.

**Comment by h19920918** [comment]
@craffel Thank you !
