### ISSUE TITLE
Train or Fine tuning

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#169]
Hi guys,

My doubt is the following: if I have a task completely new, Should I fine-tune the network or I have to train the pre-trained one(starting by one of your pre-trained models)? Technically, Which kind of operations are performed in both cases by the network? are they similar?

**Comment by craffel** [comment]
If the task involves natural English text, you should fine-tune. If it involves non-English text or extremely non-natural text (like SQL queries), you should re-pre-train from scratch before fine-tuning. The network performs exactly the same operations before and after fine-tuning, the difference is in whether the weights are randomly initialized or set to their value after pre-training for a while.
