### ISSUE TITLE
StructBert

### ISSUE THREAD

**Issue by Albert-Ma** [google-research/text-to-text-transfer-transformer#17]
The StructBERT have released their [paper](https://openreview.net/forum?id=BJgQ4lSFPH). It's very good to see the great performance improvement when incorporating language structures into language model. They use the same data as BERT, but the base model can get a comparable score with bert-large in GLUE.

So I want to know if T5 have tried this unsupervised objective recently? And if it works better than the span mlm?

**Comment by craffel** [comment]
We didn't include this objective; it came out too late in the game to consider. You could implement the shuffle-masking objective as a text or token preprocessor, should be reasonably straightforward. The sentence order objective would be a little trickier but could probably be done as a text preprocessor. But overall it's definitely out of scope of the work we are doing for this project.
