### ISSUE TITLE
Question about setting up T5 on local machine

### ISSUE THREAD

**Issue by resotto** [google-research/text-to-text-transfer-transformer#178]
Could I set up T5 on local machine and train it?
If I could, I wanna know how to do it.

Thank you.

**Comment by craffel** [comment]
Of course. If you have a GPU you can use this: https://github.com/google-research/text-to-text-transfer-transformer#gpu-usage
If you have no GPU you could try something like
```
t5_mesh_transformer \ 
 --gin_file="dataset.gin" \
 --gin_param="utils.run.mesh_shape = ''" \
 --gin_param="utils.run.mesh_devices = ['cpu:0']" \
--gin_param="MIXTURE_NAME = 'super_glue_copa_v102'"
```

replacing the mixture name with whatever mixture or task you want to use.
