### ISSUE TITLE
Doubt on input format

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#179]
Hello everybody,

I have a doubt about the input format. 
Let's say I want to recreate the translation task on my custom dataset and I want to use pre-train too.
I.E: assume I have a dataset eng-ita.

1) How should I frame the samples to feed into the model?

2) Furthermore, I've done some experiment(specifically I've pre-trained the base model) with the following "input framing" {inputs: "my name is luigi", targets: "il mio nome è luigi" }

With the latter framing, I got some results, however as far as I understand from the paper that kind of sample should be not valid since I'm not specifying the type of task.

One last question, both training and fine-tuning need the framing of input, right?

**Comment by craffel** [comment]
The task prefix is useful when you're doing multi-task training, i.e. training the model to do multiple tasks at once (e.g. when we train on GLUE tasks we randomly sample examples from all the GLUE tasks and prepend a task prefix). If you are only ever training the model for english-italian translation, you don't need a task prefix, but it won't hurt to include one. If you are pre-training on one task before fine-tuning separately on a single task, you probably can also get by not using the task prefix, but again it won't hurt.
