### ISSUE TITLE
specifying checkpoint id when exporting models

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#181]
I am exporting a certain checkpoint of my models using this command: 
```bash 
export PROJECT=...
export ZONE=....
export MODEL_DIR=gs://...
t5_mesh_transformer \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --checkpoint_steps=1100500 \
  --use_model_api \
  --mode="export" \
  --export_dir="${MODEL_DIR}/export" \
  --tpu="SOME_NAME"
```

At some point in the logs I see that it says: 
```
I0420 21:00:06.213297 139918767342976 saver.py:1284] Restoring parameters from gs://danielk-files/t5-models/union_mixture/3B/model.ckpt-1120000
```
Does this comment mean the command is exporting checkpoint 1120000? 

Notice that the checkpoint I specified is 1100500 which is different than what this log is saying 1120000.

**Comment by adarob** [comment]
It does look like it's exporting the wrong checkpoint. I took a quick glance at the codepath and don't see an obvious issue. I can have a look later, but if you happen to find the issue, please send a PR!

**Comment by adarob** [comment]
Ah, I think you need to set `--checkpoint_mode=specific`. This is definitely confusing and we should at least add an error message when these 2 flags conflict.

**Comment by sharannarang** [comment]
Added a check for this issue.

**Comment by danyaljj** [comment]
@sharannarang I suggest updating the readme as well: 
https://github.com/google-research/text-to-text-transfer-transformer#export

**Comment by sharannarang** [comment]
This flag is only used when `use_model_api` is set. We haven't documented the flags of this mode in our README since it might change. So, I don't think the readme needs to be updated.

**Comment by adarob** [comment]
Daniel, are you suggesting to add an example with a specific checkpoint?

**Comment by danyaljj** [comment]
Adam, yes, that's what I am suggesting.

**Comment by adarob** [comment]
Seems like a good idea. @sharannarang can you take care of this?
