### ISSUE TITLE
Fine-Tune T5 for Question Answering

### ISSUE THREAD

**Issue by vapyc** [google-research/text-to-text-transfer-transformer#184]
I want to fine-tune the T5 model on a custom dataset of question Answers. Can anyone guide it how can I proceed?
Specifically, I want to know the input data format. (Whether to use tsv or any other)
How to preprocess the input data?
Secondly how to run it in the GPU?

**Comment by adarob** [comment]
Have a look a the Colab example which does exactly this: tiny.cc/t5-colab

**Comment by espoirMur** [comment]
Hey @adarob, mind sharing the link again, it seems to be broken..

**Comment by adarob** [comment]
http://goo.gle/t5-colab
