### ISSUE TITLE
Clarification on "steps" params

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#188]
Hi guys,

First of all, I want to thank for your amazing support, you're such great guys.
My perplexity is the following: the concept of steps, stands for the # of times the weights of the network are updates, wrt batch size, am I right?

Sorry for the trivial question, however, if I'm not mistaken even in the original paper of T5 you never talk about epochs. Moreover if so, I would like to know why in these settings, you never mention the number of epochs?

Have a great day :)

**Comment by adarob** [comment]
Yes, your understanding of steps is correct.

We never mention epochs because it varies by task and we're typically training on mixtures of multiple tasks. Also, our primary pre-training dataset (C4) is so large that we never make it through a full epoch.
