### ISSUE TITLE
T5 11B requirements to run on CPU machine?

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#189]
Wondering if you have tried 11B models on cpu machine. If so, 
 - Any estimates on how long it might take to run it on each instance? 
 - How much memory should be sufficient to run this model? Since the exported models are around 21GB, I suppose the memory usage should def be bigger.

**Comment by sharannarang** [comment]
Hi Daniel,

AFAIK, none of us have attempted to train the 11B model on a CPU machine. As you can imagine, it would require a lot of memory and would be quite slow.

**Comment by adarob** [comment]
Just to clarify, are you asking about training or inference?

**Comment by danyaljj** [comment]
Inference time (Sorry for not making it clear in the first post.)

**Comment by adarob** [comment]
The inference time is surprisingly fast on CPU considering the size of the model actually. From an exported model, I believe it takes ~1 second to decode a batch size of 1. I don't recall the exact details but it should be easy to try.

**Comment by danyaljj** [comment]
Adam, that's super-helpful to know!

Any thoughts on the memory usage?

Daniel
