### ISSUE TITLE
Non-autoregressive decoding

### ISSUE THREAD

**Issue by BogdanDidenko** [google-research/text-to-text-transfer-transformer#19]
The autoregressive nature makes inference difficult to parallelize and leads to high decoding latency. Have you noticed new researches in non-autoregressive decoding area? I found this: https://arxiv.org/abs/1908.07181
https://github.com/zomux/lanmt

**Comment by craffel** [comment]
Yes, these approaches are awesome but they are definitely out-of-scope for T5. You could try extending the Mesh TF transformer to add this or use our model interface to feed data from T5 into a different model.

**Comment by Santosh-Gupta** [comment]
@BogdanDidenko where you able to implement a version with  non-autogressive decoder?
