### ISSUE TITLE
The importance of sequence length

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#190]
Hi guys,

I have a doubt if a have a dataset where each sample is made of k tokens(let's say 100) if I train the network with the default sequence length of 512 tokens, Could this hinder the learning process?. The same doubt arises for fine-tuning as well.

In other words, if I know a priori which is the max size of all my samples in the dataset, Could be useful to specify exactly this size during training and fine-tuning even though the size is not exactly a power of 2?

Have a good day :)

**Comment by sharannarang** [comment]
We pack different examples together to fill up a sequence. So, in your example, 4 100 token examples can be packed into a single example of 512 tokens. You can also simply set sequence length to a smaller or larger value. We typically set it to powers of 2 for the computation to be efficient. But sequence length which isn't a power of 2 should also work.
