### ISSUE TITLE
What sequence_length parameter of get_dataset() means

### ISSUE THREAD

**Issue by resotto** [google-research/text-to-text-transfer-transformer#193]
I referenced comments about it:

>     sequence_length: dict of int, a dict mapping feature name to length.
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py#L142

but I couldn't understand what it means.
Could someone explain it?

Thank you.

**Comment by sharannarang** [comment]
The `sequence_length` parameter needs to be a dict of all the features in your dataset. So, in case of seq-to-seq models for text, we have 'inputs' and 'targets' as features in our datasets. The dict would specify sequence length for each of the features. E.g.

```
{ 
  'inputs': 512
  'targets': 512
}
```

Hope this helps.

**Comment by working12** [comment]
@sharannarang  To be crystal clear for future users

If I have a input sentence like "This is a test" and correspoding output to be "correct answer" then sequence length for the inputs would be 4 and  outputs would be "2" right? (or do you mean tokenized  parts like "Th is a te st" so it would be 5 for inputs?)

**Comment by craffel** [comment]
It corresponds to tokenized lengths.

**Comment by adarob** [comment]
I think it would be worth creating a simple script to compute the length
distribution for a given task.
