### ISSUE TITLE
Possibility to use own Multi-Task Learning Datasets and Train Model 

### ISSUE THREAD

**Issue by Halli20** [google-research/text-to-text-transfer-transformer#194]
If I understood the paper correctly, in the released models (3B, 11B, etc.) you already trained the models on several supervised tasks? 

Is it possible to use a model which is only pre-trained on the unsupervised tasks (without any datasets used in multi-task pre-training)? This refers to the model ("Unsupervised pre-training + fine-tuning") mentioned in the paper in table 12.

My goal is to analyze the influences of the task choices when using multi-task learning. I would like to do this by using different task combinations (e.g. SQuAD and GLUE) for pre-training. I.e I want to further train your model on a customized selection of supervised tasks and fine-tune the pre-trained model on a specific task to see the influence of multi-task learning on this specific task. 
Is that possible or can I only use your model which is already trained on the supervised tasks you mention in the paper?

**Comment by adarob** [comment]
Please see the t5.1.1 checkpoints here: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/released_checkpoints.md

They are trained only on the unsupervised tasks and achieve similar results.
