### ISSUE TITLE
Generation task

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#195]
Hi everybody,

I have a problem related to my task(generation task).
In particular, the network doesn't seem able to learn when the generation of tokens could be stopped, it continues to generate nonsense tokens after the correct sentence was predicted fine.

Just to be more clear, let's suppose this:

target: I love you for your works
predicted: I love you for your works ......random tokens

At first glance, I thought that was the sequence length, but the problem still persists after some experiments to asses the sequence length.

Do you have any hint?

**Comment by sharannarang** [comment]
Does your training data have end of sequence symbols? Has the model learnt to generate them? I suspect that might be the problem here.

**Comment by antoniomastro1996** [comment]
Hi, no my training data doesn't have an end of sequence symbols
Just to be clear all my training sentences(samples) are separated by \n, but at the end of each ones I don't have a special token that indicates the termination of sentence. Same thing for the dataset used during fine-tuning.

Which specific token I have to set to solve the problem? Do you have any idea?

**Comment by sharannarang** [comment]
@adarob just shared that there was a bug in Mesh-Tf where the decoding was generating some extra tokens even after the end of the sequence. Can you uninstall and re-install mesh-tf? 

Also, it might be good to inspect the examples to ensure that the inputs and targets fields in the dataset are getting set correctly.

**Comment by antoniomastro1996** [comment]
@sharannarang  thanks a lot for your support, I think I solved by creating a new vocab from scratch, since the token that output after the end of the prediction, actually was "??. 
It was my mistake. 
Again, I appreciate your support, thank you :)
