### ISSUE TITLE
Extracting sequence embeddings

### ISSUE THREAD

**Issue by tr1pzz** [google-research/text-to-text-transfer-transformer#198]
I'm trying to extract some of the latent information of my trained T5 model.

Looking at the MtfModel(T5Model) class I only see high-level methods to do training, evaluation etc.
The core functions seem to be implemented in [the mesh-tensorflow/transformer methods ](https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py), does anybody have some example code of how to extract latent embeddings (eg by tensor name) from the model?

Also, will this only work on TPU, or can this also be done on GPU once the model has been exported?
Any help is greatly appreciated!

Best,
Xander

**Comment by sharannarang** [comment]
@nshazeer , could you help with this?

**Comment by tr1pzz** [comment]
@nshazeer @sharannarang an update on this would be highly appreciated!
Thanks in advance

**Comment by craffel** [comment]
There's no straightforward way to do this that I'm aware of. In the past Noam has just logged out float values and copied and pasted... If you figure(d) something out, let us know.
