### ISSUE TITLE
Are newline '\n' characters allowed in .tsv data format?

### ISSUE THREAD

**Issue by misrasaurabh1** [google-research/text-to-text-transfer-transformer#2]
I am trying to finetune the model on a new dataset. My data has newline characters. Even though sentence-piece should be able to handle newlines, I am not how to mix dataset newlines and tsv file-format newlines

Consider this tsv data- 
Hi there!\nHello! How are you doing!?\t I am doing great!
Sample dataline1\nSample dataline2\t Sample dataline3\nSample dataline4

I want to ask if is \n the right way to encode newlines for tsv file?

**Comment by adarob** [comment]
Newline characters will not work in the tsv format. We will be adding
support soon for other ways of specifying datasets for fine tuning that
will allow newlines.

For now, I'd suggest replacing the newlines with another special character
(or sequence, like '<newline>') that doesn't appear in your strings.

**Comment by ArijRB** [comment]
Hello, 
I was wondering if there is any change in handling newlines for a new dataset tsv format.
Thank you in advance

**Comment by adarob** [comment]
No, tsv will never support newline characters since tsv files are split on newlines. You could use some other sequence (like __NEWLINE__) to replace newlines in your text and then convert them to \n in a preprocessor. Otherwise, you can just a TFRecord file for your inputs.

**Comment by tfmorris** [comment]
> No, tsv will never support newline characters since tsv files are split on newlines. You could use some other sequence (like `__NEWLINE__`) to replace newlines in your text and then convert them to `\n` in a preprocessor. 

Some TSV readers support unescaping `\n` and '\r' (as well as '\t').
