### ISSUE TITLE
Modifying Your Model for Open Book QA?

### ISSUE THREAD

**Issue by ZhiliWang** [google-research/text-to-text-transfer-transformer#201]
Hello and I think this is an amazing, extremely beginner-friendly project! I am new to the QA domain and currently focusing my research on Open Book QA. Do you think it would be a viable direction to to do so based on your current TI5 model in this repo (I will certainly cite your work properly)? Thank you!

**Comment by sharannarang** [comment]
Thanks for your interest in T5. It should be fairly straightforward to use T5 for OpenBook QA. The setup should be similar to SQUAD, which contains a context, question, and answer.

**Comment by adarob** [comment]
Our closed book QA code is at https://github.com/google-research/google-research/tree/master/t5_closed_book_qa but we do some closed-book tasks with the code in this repo (e.g., SQUAD: https://github.com/google-research/text-to-text-transfer-transformer/blob/ca5203977780b4718910e025cbe88d3b0625b951/t5/data/tasks.py#L282).
