### ISSUE TITLE
Multiple predictions

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#204]
Hi all,

Is it possible to predict multiple sequences?
For the sake of clarity, assume my task is a translation task, I want such a behavior

input: I love English

output[1]: I amo l'inglese
output[2]: I ama l'inglese
output[3] I adoro l'inglese

I tried to use the method predict found in t5-trivia Colab, however, even if I set a temperature = 0 and a beam size greater than 1, the output is still one sentence.

Where am I wrong int the described process?

**Comment by sharannarang** [comment]
To get multiple outputs, you want to set the temperature to 1 to randomly sample based on predicted distribution.

**Comment by allen-q** [comment]
@sharannarang , just a follow up on this question. I can get different predictions with temperature set to 1 when I run the model multiple times. However, how can I get more than 1 different predictions at once? I.e feeding 'love English' and get 3 different predictions all at once?

**Comment by craffel** [comment]
What do you mean by "all at once"? If you want to call predict on the model once and get multiple predictions for the same input, you could create a batch of repeated examples.

**Comment by allen-q** [comment]
@craffel , thanks for getting back to me. Yes, I was wondering if I can get multiple predictions by calling the model only once. Batch of repeated samples is a good idea and I will give it a try. Thanks.

**Comment by mellahysf** [comment]
Hi,

How can I do it @craffel @allen-q ?
