### ISSUE TITLE
Is possible to get multiple predictions?

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#209]

**Comment by antoniomastro1996** [comment]
Hi guys, my problem Is that I'm not able to generate multiple prediction given an input.
@sharannarang suggests me to set the temperature to 1, however when I try to run the following code : 
  
model.predict(
      input_file=predict_inputs_path,
      output_file=predict_outputs_path,
      beam_size = 10, 
      temperature = 1.0,
      sentencepiece_model_path=vocab_model_path
  )

I get the following error: 
<b>
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-33-3c269a6e5848> in <module>()
     21       beam_size = 10,
     22       temperature = 1.0,
---> 23       sentencepiece_model_path=vocab_model_path
     24   )
     25 

40 frames
/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/transformer.py in decode(self, inputs, variable_dtype, beam_size, alpha, temperature, decode_length_multiplier, decode_length_constant, max_decode_length)
   2054       if temperature != 0:
   2055         raise ValueError(
-> 2056             "don't know how to beam search with nonzero temperature")
   2057       # beam search
   2058       beam_dim = mtf.Dimension("beam", beam_size)

ValueError: don't know how to beam search with nonzero temperature
  In call to configurable 'decode' (<function Bitransformer.decode at 0x7f3046c741e0>)
  In call to configurable 'decode' (<function decode at 0x7f3046c2f6a8>)
  In call to configurable 'decode_from_file' (<function decode_from_file at 0x7f3046c2f950>)
  In call to configurable 'infer_model' (<function infer_model at 0x7f3046c3c048>)
</b>

I checked the code and there is a comment which tell that whenever we want to use beam_search, the temperature must be 0. Where I am going wrong?

**Comment by sharannarang** [comment]
Hi, 

You need to set beam_size to 1 if you want to generate decodes using random sampling.
