### ISSUE TITLE
Does beam search works?

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#213]
Hi guys,

I'm experiencing difficulties to work on beam search. In particular, it seems that the evaluation method(in mft_mode class l) doesn't perform beam search, I always get the same results over and over again even though I change the beam size. (The evaluation metric I used was the bleu score.)
In order to correctly set the parameter in Colab I use the following command:

<b>import gin
with gin.unlock_config():
      gin.parse_config_file(GIN_FILE)
      gin.bind_parameter("Bitransformer.decode.beam_size", 25)
      gin.bind_parameter("Bitransformer.decode.alpha", 0.6)
      gin.bind_parameter("utils.get_variable_dtype.slice_dtype", "bfloat16")
      gin.bind_parameter("utils.get_variable_dtype.activation_dtype", "bfloat16")
</b>

I can deduce so since the results I obtain after validation on multiple beam size are always the same, nothing change in terms of evaluation metric.
Is this an error or I'm getting wrong on something?

Thanks in advance :)

**Comment by adarob** [comment]
It's also possible that, especially for short outputs, the argmax decode is the best. Maybe try setting the beam size to 1 and using a really high temperature. If you still get the same results, there is likely something wrong with the gin settings.

**Comment by adarob** [comment]
@antoniomastro1996 did you have a chance to try that?

**Comment by antoniomastro1996** [comment]
hi @adarob ,
I've tried with a very high temperature and beam size = 1, but it seems that the network is not able to produce anything. However, by changing the beam width the evaluation metric slightly changes, this should be a sign that the beam search works fine. 
The only thing I didn't get it is if the prediction output file should contain more predictions for each input according to the beam size or if the prediction output file contains only the best prediction among the k( where k is the beam size). From what I get, it seems true the latter.
It could be useful to have a variant of beam search where each predicted output is stored, not only the best one.

**Comment by antoniomastro1996** [comment]
hi @adarob 
Right now I have tried with beam size = 1 and a temperature = 0.95, the accuracy slightly changes compared to beam search where beam size = 50 and alpha = 0.3. Is that normal?

**Comment by adarob** [comment]
The prediction file only contains the "best" output. Please open an issue against tensorflow/mesh if you'd like to add support for full beam output. Although, in all honesty, you may have to add it yourself. 

It looks like you'd need to change the gather here: https://github.com/tensorflow/mesh/blob/d4ac40af502444870f3e194e7fb6c92c4b2973c7/mesh_tensorflow/transformer/transformer.py#L1323

And yes, it does it make sense that you'd get different outputs since you're using a different temperature.
