### ISSUE TITLE
Doubt on objective function for fine-tuning

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#217]
Hi guys, just quick info, as far I understand, during training everything is treated in unsupervised way, and in particular you have experimented with a variety of unsupervised objectives. 
However, it's not clear to me when I fine-tune the network where let's say we have translation task { input: I love you - output: ti voglio bene } how this Denoising obj function is applied.

On the other hand, for training, things are more clear since the framing of the input is like the following: { input: My name is ...........}.

Where I'm going wrong?

Thanks in advance :)

**Comment by adarob** [comment]
We only use the unsupervised tasks like denoising during pre-training. During finetuning, the model is simply trying to predict the targets from the inputs in a supervised way.
