### ISSUE TITLE
Regarding the model structure, what is the main difference between T5 and original Transformer?

### ISSUE THREAD

**Issue by Morizeyao** [google-research/text-to-text-transfer-transformer#22]
I've been trying to do some experiments on T5 recently, and have read the paper.

After reading 2.1 part of the paper, my understanding is, the differences of model structure between T5 and Transformer are:

1. T5 uses relative positional embedding.
2. LayerNorm are used at the start of each block and the end of last block. 

Am I right?

Thank you for your time!

**Comment by craffel** [comment]
Yes, that's right. We also use a "scale-only" layer norm, which we failed to mention in v1 of the paper. An updated version of the paper which includes this detail will be online soon. The implementation is available at https://github.com/tensorflow/mesh/tree/master/mesh_tensorflow/transformer/

**Comment by Morizeyao** [comment]
Much thank you for your quick answer!
