### ISSUE TITLE
Session crashing on running first cell.

### ISSUE THREAD

**Issue by nickwalton** [google-research/text-to-text-transfer-transformer#220]
On running the first cell of the notebook on a TPU runtime I'm getting session crashes where Colab gives a`Your session has crashed for an unknown reason` notification. This didn't happen a week ago so it seem something has become incompatible with Colab.

**Comment by adarob** [comment]
Thanks for letting us know, Nick. I'll raise the issue with the colab team.

**Comment by adarob** [comment]
@rjpower

**Comment by antoniomastro1996** [comment]
Hi, I found out that the the instruction which lead to a crash is the following: tensorflow_gcs_config.configure_gcs_from_colab_auth('/device:CPU:0').
Just comment it and should works

**Comment by adarob** [comment]
Thanks @antoniomastro1996. Previously the code did not work without that line, but maybe something has changed underneath us. I'll update the notebook unless you want to submit a PR.

**Comment by antoniomastro1996** [comment]
@adarob No problem :) you can update the notebook
