### ISSUE TITLE
fill-in-the-blank task 

### ISSUE THREAD

**Issue by edmar** [google-research/text-to-text-transfer-transformer#224]
Hey,

How can I test T5 on the fill-in-the-blank task?

Described on the paper and as seen on the blog post:
[https://ai.googleblog.com/2020/02/exploring-transfer-learning-with-t5.html](https://ai.googleblog.com/2020/02/exploring-transfer-learning-with-t5.html)

Best

**Comment by sharannarang** [comment]
Hi Edmar,

You can create a task with the fill in the blank preprocessor here: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L463. If you are interested in fill in the blank with sized bins you can use this preprocessor: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L563. You can use C4 or any other dataset to train your model. Hope this helps.

**Comment by arglog** [comment]
Hi @sharannarang 

Does this mean that we need to train (or fine-tune) a separate model for every specific blank length? For example, in the [T5 blog](https://ai.googleblog.com/2020/02/exploring-transfer-learning-with-t5.html) there is a demo showing that the model can fill in the blank with 8 different lengths (N=1, 2, 4, 8 16, 32, 64, 512). So are there 8 different models where each model is handling a specific length? Is there a way to generate blanks with different lengths with a single model?

Thanks!

**Comment by craffel** [comment]
There was a single model trained to fill in blanks of various sizes, all at once.
