### ISSUE TITLE
colab Session crashes

### ISSUE THREAD

**Issue by shurm** [google-research/text-to-text-transfer-transformer#228]
I try to run the first code cell of t5-trivia.ipynb which sets up the TPU environment, but it just crashes my colab notebook. 

I get the following 3 pop up messages when I run this cell: "Your session crashed. Automatically restarting.", "Your session restarted after a crash. Diagnosing...","Your session crashed for an unknown reason.".

Does anyone know why this is happening?

**Below is the runtime log:**
Timestamp | Level | Message
-- | -- | --
May 18, 2020, 4:16:25 PM | WARNING | WARNING:root:kernel c8b3c177-f21b-47c1-b45a-73d6594b4134 restarted
May 18, 2020, 4:16:25 PM | INFO | KernelRestarter: restarting kernel (1/5), keep random ports
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.381403: I tensorflow/core/distributed_runtime/rpc/grpc_server_lib.cc:390] Started server with target: grpc://localhost:30569
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.380847: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30569}
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.380777: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.2.36.82:8470}
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.362458: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job localhost -> {0 -> localhost:30569}
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.362398: I tensorflow/core/distributed_runtime/rpc/grpc_channel.cc:301] Initialize GrpcChannelCache for job worker -> {0 -> 10.2.36.82:8470}
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.352255: I tensorflow/compiler/xla/service/service.cc:176] StreamExecutor device (0): Host, Default Version
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.352221: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7016540 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.351678: I tensorflow/core/platform/profile_utils/cpu_utils.cc:102] CPU Frequency: 2300000000 Hz
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.344978: I tensorflow/stream_executor/cuda/cuda_diagnostics.cc:156] kernel driver does not appear to be running on this host (aae715b21ddd): /proc/driver/nvidia/version does not exist
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.344930: E tensorflow/stream_executor/cuda/cuda_driver.cc:313] failed call to cuInit: CUDA_ERROR_NO_DEVICE: no CUDA-capable device is detected
May 18, 2020, 4:16:24 PM | WARNING | 2020-05-18 20:16:24.342528: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library libcuda.so.1

**Comment by adarob** [comment]
This issue should have been fixed in #221. Please update refresh your colab and reopen this issue if it still fails.
