### ISSUE TITLE
Smaller DataSets for GPU evaluation of pre-trainning using T5

### ISSUE THREAD

**Issue by xdgarrido** [google-research/text-to-text-transfer-transformer#238]
I was wondering if there are smaller data sets to evaluate GPU performance. The idea could be to use Wikipedia data as used by BERT to perform pre-training from scratch using GPU's. It is not clear to me how to use the tools provided in the directory /data from repository. No examples are really provided by readme. Any, guidance would be greatly appreciated.

**Comment by craffel** [comment]
Hi, you can use [Wikipedia](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L50) for pre-training from scratch. See https://github.com/google-research/text-to-text-transfer-transformer#gpu-usage OTOH a command for Wikipedia pre-training of T5-Base could look something like
```
t5_mesh_transformer  \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.run.mesh_shape = 'model:1,batch:1'" \
  --gin_param="utils.run.mesh_devices = ['gpu:0']" \
  --gin_param="MIXTURE_NAME = 'wikipedia_20190301.en_v003_unsupervised'" \
  --gin_file="models/bi_v1.gin" \
  --gin_param="utils.run.train_steps = 524288" \
  --gin_param="utils.run.save_checkpoints_steps = 5000" \
  --gin_param="utils.run.batch_size = (\"tokens_per_batch\", 65536)"  \
  --gin_file="learning_rate_schedules/rsqrt_no_ramp_down.gin" \
  --gin_file="objectives/span_3_15_u_u.gin"
```
