### ISSUE TITLE
Vocabulary size mismatch with t5 checkpoints (using latest version of repository)

### ISSUE THREAD

**Issue by william-r-s** [google-research/text-to-text-transfer-transformer#239]
When I tried to run finetuning or prediction with the available t5 checkpoints (happened with both base and 3B) and the latest code in text-to-text-transfer-transformer and mesh-tensorflow (to use the ability to score samples), I ran into an error:

`ValueError: Shape of variable shared/embedding:0 ((32000, 768)) doesn't match with shape of tensor shared/embedding ([32128, 768]) from checkpoint reader.
`

This seems to be a mismatch in the vocabulary size.

Seems to have been working at https://github.com/google-research/text-to-text-transfer-transformer/commit/2c3d7501a682e5dfc931b362db3b3d621280d1cc

Seems to have been broken after https://github.com/google-research/text-to-text-transfer-transformer/commit/4d8cab3dbea48f3956c798dd47fd50a90f21519c with
https://github.com/google-research/text-to-text-transfer-transformer/commit/9f5fcaef5e9126b863ceff01aeecaad0062953f0 immediately proceeding it
Was able to reproduce in the colab by adding the following lines in the setup cell

```
!pip install --upgrade "git+https://github.com/tensorflow/mesh.git#egg=mesh-tensorflow"
!pip install --upgrade "git+https://github.com/google-research/text-to-text-transfer-transformer.git#egg=t5"
```
Gist with full output in colab [here](https://gist.github.com/william-r-s/05b8cc3289997408bbbe36b37f51d556)

**Comment by william-r-s** [comment]
After looking at https://github.com/google-research/text-to-text-transfer-transformer/issues/76
I tried adding the following after the initial configuration cell, and it seemed to fix the issue.

```
import gin
gin.bind_parameter("SentencePieceVocabulary.extra_ids", 100)
```

My hypothesis is that the vocabulary is now being created before the model gin configuration is loaded, so this parameter isn't set.

**Comment by adarob** [comment]
Thanks for this debugging William! I'm going to see if I can fix this in the codebase.

**Comment by adarob** [comment]
Please try `!pip install -qU git+https://github.com/google-research/text-to-text-transfer-transformer.git@refs/pull/242/merge` if you have a chance

**Comment by william-r-s** [comment]
That pr seems to work, thanks!

**Comment by tr1pzz** [comment]
Given that this broke my custom colab notebook, what's the proper way of now training/finetuning a model with a custom vocabulary?

I previously had `sentencepiece_model_path=my_custom_vocab_model_path` when adding the training task to `t5.data.TaskRegistry`, but now it seems like the `DEFAULT_OUTPUT_FEATURES` param is hardcoded to read from `DEFAULT_SPM_PATH = "gs://t5-data/vocabs/cc_all.32000/sentencepiece.model"` and I don't immediately see how to overwrite that...


Also, as a side question, any pointers to how you can extract sequence embeddings from T5?
(I flagged that [here](https://github.com/google-research/text-to-text-transfer-transformer/issues/198), but haven't gotten a reply yet)

**Comment by adarob** [comment]
on your task, you can set `output_features=t5.data.Feature(vocabulary=t5.data.SentencePieceVocabulary(my_custom_vocab_model_path))`

**Comment by tr1pzz** [comment]
Thank you, I should have probably figured that out myself.. 
Any links/tips to how you can extract embeddings from T5?

**Comment by adarob** [comment]
You may want to open an issue on github.com/tensorflow/mesh to ask that question of @nshazeer et al. I'm not sure if there is an easy way to do that at the moment, however. Another option is to see if it's easy to do with the huggingface implementation.
