### ISSUE TITLE
Is it possible to share dev set numbers for models in Table-14 of the paper

### ISSUE THREAD

**Issue by ngoyal2707** [google-research/text-to-text-transfer-transformer#24]
Hi,
You guys have done amazing job with putting the details in the paper, it is quite helpful to see such detailed study. Thanks for this.

I was wondering if it's possible to share dev set numbers for the 3 models (`T5-large/3B/11B`) presented in Table 14 of the paper. I know that test numbers are more trustworthy in general. But because most of these test numbers are obtained through leaderboard submissions (which are rate limited), they are hard to compare against for different systems. If you can provide the dev numbers also, they will be very helpful to compare against.

I personally specifically care about the GLUE and SuperGLUE tasks if that's possible to share.

Thanks again for the answering the questions.

**Comment by craffel** [comment]
Hi, thanks for the kind words. We'll be posting an update of the paper in the not-too-distant future which includes the validation set version of Table 14.
