### ISSUE TITLE
What is the meaning of these graphs in tensorboard?

### ISSUE THREAD

**Issue by working12** [google-research/text-to-text-transfer-transformer#240]
When I use tensorboard to log the output of the training or fine tune steps. I get 3 things:-
![image](https://user-images.githubusercontent.com/12879472/82775059-dbc15000-9e46-11ea-8e44-4565ffeae8b2.png)
- examples
- gloabl_step
- loss.

What are the usefulness of the first two?

**Comment by adarob** [comment]
The first 2 are just to allow you to monitor the speed of training (steps/second and examples/second).

**Comment by working12** [comment]
@adarob Can you explain the meaning of these two terms? steps meanings epochs here? Examples means the number of qa pair it reads and processes in 1 sec?
