### ISSUE TITLE
Speeding up the inference on CPU

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#244]
I am running a 3B exported model on a CPU machine with the following code:
```python 
import tensorflow.compat.v1 as tf
import tensorflow_text as tf_text

tf.reset_default_graph()

saved_model_path="gs://exported-model-name"
sess = tf.Session()

meta_graph_def = tf.saved_model.loader.load(sess, ["serve"], saved_model_path)
signature_def = meta_graph_def.signature_def["serving_default"]

def answer(question):
  return sess.run(
      fetches=signature_def.outputs["outputs"].name,
      feed_dict={signature_def.inputs["input"].name: [question]}
  )[0].decode('utf-8')

answer("how is the weather tomorrow?")
```

The model takes about ~1min to solve each instance, which is pretty slow. Ans it is not compatible with what @adarob reported in https://github.com/google-research/text-to-text-transfer-transformer/issues/189#issuecomment-619270754 : 

> From an exported model, I believe it takes ~1 second to decode a batch size of 1.  

I am wondering if there is anything I can do to speed this up. 
In particular:
 -  I suspect that my code is using a single code. How can I specify several cores? I have seen that you can do this when using CLI, but not sure how to do it the way I am calling it. 
```
 --gin_param="utils.run.mesh_devices = ['cpu:0']" \
```
(from here: https://github.com/google-research/text-to-text-transfer-transformer/issues/178#issuecomment-615970511 )

- Would it make sense (is it even possible) to batch the instances when running on CPU?

**Comment by danyaljj** [comment]
Follow up on this: 

- I several changes in the section on making predictions from exported models in [T5-trivia](https://colab.research.google.com/github/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb#scrollTo=eWu8lbh3aHjc). In particular, it the changes show how to load the model with eager execution: 

```python 
def load_predict_fn(model_path):
    if tf.executing_eagerly():
        print("Loading SavedModel in eager mode.")
        imported = tf.compat.v2.saved_model.load(model_path, ["serve"])
        return lambda x: imported.signatures['serving_default'](tf.constant(x))['outputs'].numpy()
    else:
        print("Loading SavedModel in tf 1.x graph mode.")
        tf.compat.v1.reset_default_graph()
        sess = tf.compat.v1.Session()
        meta_graph_def = tf.compat.v1.saved_model.load(sess, ["serve"], model_path)
        signature_def = meta_graph_def.signature_def["serving_default"]
        return lambda x: sess.run(
            fetches=signature_def.outputs["outputs"].name,
            feed_dict={signature_def.inputs["input"].name: x}
        )

predict_fn = load_predict_fn(saved_model_path)

def answer(question):
    return predict_fn([question])[0].decode('utf-8')
```

This seems to be speed things up a bit now; now the average time spent on solving individual questions is: 
```

```

I tried passing in several inputs; just duplicated my input `question` but doesn't seem to work as expected (the output of `answer("some question")` is always a single string, as opposed to an array of strings): 
```
def answer(question):
    return predict_fn([question, question])[0].decode('utf-8')
```

- One related question: do you need to specify the batch size while exporting the models? 
In your T5-trivia code, you specify the batch size right **before** you export the model: 

```python 
model.batch_size = 1 # make one prediction per call
saved_model_path = model.export(....) 
```

**Comment by adarob** [comment]
that's because you're still indexing with `[0]`. Try:

```
def answer(question):
    return [ans.decode('utf-8') for ans in predict_fn([question, question])]
```

Yes, you do need to set the batch size before exporting. I'm not sure there is a way around this with the infrastructure we're using.

**Comment by jinoobaek-qz** [comment]
Thanks for the support @adarob. On a somewhat related note, I tried to export with batch_size larger than 1. (I hard coded it for now). It seems to work. Is there some unforeseen downside to this? It seems like when I set batch size to 8 and send it 4 items, I can ignore the last 4 items of the output.

**Comment by Ki6an** [comment]
hey, for speeding up the T5 model, you can have a look at the [fastT5](https://github.com/Ki6an/fastT5) library it boosts the inference speed up to 5x on CPU and also reduces the model size.
