### ISSUE TITLE
[Bug+Fix] Batch-Size other than an integer leads to AttributeError in batch_size setter

### ISSUE THREAD

**Issue by f-lng** [google-research/text-to-text-transfer-transformer#25]
The __init__ of MtfModel tries to set batch_size before initialising various other variables that are needed in order to execute utils.compute_batch_size, which throws an AttributeError if batch_size is a tuple e.g. ("tokens_per_batch", 1024) . 

To fix it, the following code should be at the bottom of the __init__ function.
`self.batch_size = batch_size`

I hope this has no consequences for other initialisations done within the __init__ function, and would be glad if someone could verify this.

**Comment by craffel** [comment]
Yes I think you're right. Feel free to make a PR. @sharannarang @adarob please confirm.

**Comment by sharannarang** [comment]
Yes, that should be fine. Please create a PR.

**Comment by f-lng** [comment]
As my T5 code is already full of other small hacks (see my other bug report), it should be simpler if you just move the line down in one of your next PRs :-)

**Comment by craffel** [comment]
@f-lng Is this your proposed fix? #32
@adarob or @sharannarang please merge the PR

**Comment by f-lng** [comment]
@craffel Yes it is, thank you for the PR.
