### ISSUE TITLE
Deploying T5

### ISSUE THREAD

**Issue by shurm** [google-research/text-to-text-transfer-transformer#256]
Hi again,

I have trained and exported a T5 that generates pretty good text. Now I wish to deploy it on the web so I can have an application query it. Do you know of a way I can do that? 

I tried use the ai-platform at https://console.cloud.google.com/ai-platform but its giving me the error: "NotFoundError: Op type not registered 'SentencepieceOp' in binary" (I think this means I need to import tensorflow_text but I'm sure how to do that in this platform :( ). Do you know of a way to deploy a T5 model?

Thank you for help.

**Comment by adarob** [comment]
Unfortunately Cloud AI Platform does not yet have support for SentencepieceOp. My understanding is that it will be available in the next 4-6 weeks, but I'll try to loop in the team on this issue.

**Comment by shurm** [comment]
ok thank you for the prompt response.

and thank you and your team for creating this cutting edge language model :) ! it's been very interesting to experiment with 👍 

P.S. please let me know you learn of another way to deploy a T5 model

**Comment by adarob** [comment]
One option is to create your own server. I followed these instructions yesterday and was able to deploy a model in ~1 hour: https://www.tensorflow.org/tfx/serving/building_with_docker

**Comment by adarob** [comment]
Note that you'll need to use the `nightly` version to get the SentencePieceOp support.

**Comment by adarob** [comment]
FYI, I added an example for creating the docker image in #279. You can see it in Colab here: https://colab.research.google.com/github/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-deploy.ipynb
