### ISSUE TITLE
Did you explore harder pretraining objectives for bigger models 

### ISSUE THREAD

**Issue by ngoyal2707** [google-research/text-to-text-transfer-transformer#26]
Hi, 

Thanks again for answering these questions and great study.

Just a quick question,  when you scaled the model size were you able to explore different pretraining objectives? My intuition is, maybe bigger models are able to fit harder pretraining tasks. And harder pretraining tasks get even better downstream representations?

**Comment by craffel** [comment]
Hi, we explored different unsupervised objectives in section 3.3 and different model sizes in 3.6 and 3.7. We did not explore changing the objective alongside changing the model size. This would be pretty easy to do using our code.
