### ISSUE TITLE
Summarization Checkpoints

### ISSUE THREAD

**Issue by sshleifer** [google-research/text-to-text-transfer-transformer#265]
Two questions about finetuning T5 for seq2seq tasks:

1) Do you guys plan to release/know of any t5 checkpoints that are finetuned on summarization tasks or translation tasks?

2) In table 2 of the t5 paper, would it be correct to say that the top row is finetuned t5-large and the 3rd row is finetuned t5-base?
![image](https://user-images.githubusercontent.com/6045025/84704732-433f5c80-af28-11ea-9cad-9bd54548123e.png)

Thanks in advance!

**Comment by alexgaskell10** [comment]
I would also like checkpoints for models fine-tuned for summarisation, particularly CNN/DM.

**Comment by peterjliu** [comment]
Another option is to use the Pegasus checkpoints which have been released https://github.com/google-research/pegasus.

**Comment by craffel** [comment]
We don't have any plans to release fine-tuned checkpoints, but if you need them for a specific experiment or diagnostic purposes I can send them to you directly, just email me.
