### ISSUE TITLE
SentencePiece model_type used on paper

### ISSUE THREAD

**Issue by marcospiau** [google-research/text-to-text-transfer-transformer#270]
Hi guys. First of all, thanks for sharing you work with us.

I'm trying to use SentencePiece to generate a custom vocab in another language, but keeping the parameters you used. 
Do you know which ```model_type``` you used on the training your SentencePiece vocab? The default ```model_type``` is ```unigram```, and the other ones available  are ```bpe```, ```char```, or ```word```.

Thanks in advance!

**Comment by adarob** [comment]
We used the default (`unigram`). The only options we changed are the following:

```
  --pad_id=0 \
   --eos_id=1 \
   --unk_id=2 \
   --bos_id=-1 \
```

**Comment by marcospiau** [comment]
Thank you @adarob !!
