### ISSUE TITLE
pretrained model gin file seem to have a bug

### ISSUE THREAD

**Issue by jinoobaek-qz** [google-research/text-to-text-transfer-transformer#271]
```
diff operative_config.gin operative_config.gin.chg
201a202
> run.init_checkpoint = %init_checkpoint
248d248
< tpu_estimator_model_fn.init_checkpoint = %init_checkpoint
```

If I don't do this, the command shown in the README.md (shown below) does not start with the pretrained model.

```
t5_mesh_transformer  \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --t5_tfds_data_dir="${DATA_DIR}" \
  --gin_file="dataset.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"
```

**Comment by craffel** [comment]
I also noticed this. I'm not sure when it broke. It's because the `None` default from `run` is passed in at calling time which overrides gin. @sharannarang Do you mind updating with the script you use to bulk update the operative configs?

**Comment by sharannarang** [comment]
I've updated the pretrained models and added the init_checkpoint variable to the t5.1.1 models. Please let me know if you see any issues.

**Comment by jinoobaek-qz** [comment]
Confirmed with small and 3B. Thanks.
