### ISSUE TITLE
What is the maximum input seq length, when using T5-3b model? 

### ISSUE THREAD

**Issue by shamanez** [google-research/text-to-text-transfer-transformer#273]
What kind of positional embedding method was used during the training? Is it learned positions embedding? If yes, what is the max length?

**Comment by adarob** [comment]
It is a relative attention mechanism so you're only limited by length due to memory.

**Comment by shamanez** [comment]
Thanks a lot. So I can use a sequence that has more than 512 tokens as the input to the pretrained T5 model right?
