### ISSUE TITLE
Problem after last commit

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#278]
Hi everybody, 
I noticed the following error after the last commit.
Specifically, the exception is raised when I perform the fine-tuning of a model.

Please find below the error and the command that raised the error.

---------------------------------------
FINETUNE_STEPS = 1500000

model.finetune(
    mixture_or_task_name="all_tasks",
    pretrained_model_dir=MODEL_DIR,
    finetune_steps=FINETUNE_STEPS
)

---------------------------------------

INFO:tensorflow:training_loop marked as finished
WARNING:tensorflow:Reraising captured error
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-35-7cd6bedbd07b> in <module>()
      4     mixture_or_task_name="all_tasks",
      5     pretrained_model_dir=MODEL_DIR,
----> 6     finetune_steps=FINETUNE_STEPS
      7 )

26 frames
/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/simd_mesh_impl.py in physical_shape_3d_from_topology_proto_4d(mesh_shape)
    827   """
    828   if len(mesh_shape) != 4 or mesh_shape[2] != 1:
--> 829     raise ValueError("Expected a 4d shape [x, y, 1, core]")
    830   return [mesh_shape[1], mesh_shape[0], mesh_shape[3]]
    831 

ValueError: Expected a 4d shape [x, y, 1, core]

Can you suggest a workarounds?

**Comment by adarob** [comment]
@nshazeer PTAL

**Comment by nshazeer** [comment]
Looking... I guess the topology proto can sometimes have 3 dimensions and sometimes 4.  I will push a fix.

**Comment by adarob** [comment]
Fixed by https://github.com/tensorflow/mesh/pull/135
