### ISSUE TITLE
About scoring examples by model.score

### ISSUE THREAD

**Issue by hycsie** [google-research/text-to-text-transfer-transformer#281]
I have encounter the following error message while trying to extract the log-likelihood of target.

/usr/local/lib/python3.6/dist-packages/mesh_tensorflow/transformer/utils.py in <listcomp>(.0)
   1204   result_iter = estimator.predict(input_fn, checkpoint_path=checkpoint_path)
   1205 
-> 1206   scores = [m["scores"] for m in result_iter]
   1207   # Remove any padding examples
   1208   scores = scores[:num_examples]

KeyError: 'scores'
  In call to configurable 'score_from_strings' (<function score_from_strings at 0x7f60d460a7b8>)

Does score function depend on evaluation metric? I'm using accuracy to  fine-tune a classification task.
Can I get extract the log-likelihood or probability score for each class in a classification task?

**Comment by craffel** [comment]
Hi, how is `score_from_strings` being called? Is it via a call to `utils.run`? If so, there must be a codepath where the estimator is not getting built in `"score"` mode (https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py#L494) before `score_from_strings` is called (https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py#L2167). @daphnei any thought?

**Comment by hycsie** [comment]
I simply uses "model.score(inputs=~,targets=~,scores_file=~ )" after loading mtf model checkpoint.
As I trace back the code, it is called from `score_from_strings `.

BTW, it seems that h5 model doesn't support score method.

**Comment by craffel** [comment]
Yes, it looks like the estimator used by the `score` function of `MtfModel` uses the wrong `mode` (something other than `"score"`). @daphnei can you take a look?

**Comment by daphnei** [comment]
Will take a look.

**Comment by craffel** [comment]
Thanks @daphnei.

Hi @hycsie, can you confirm that #283 fixes this issue? Thanks.

**Comment by hycsie** [comment]
Is it merged yes? I tried on reloaded colab, but still get same result.

**Comment by daphnei** [comment]
It hasn't been merged yet. To test it out, try replacing the line in the colab `!pip install -q t5` with `!pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git1

**Comment by daphnei** [comment]
To test it out, try replacing the line in the colab `!pip install -q t5` with `!pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git@test_318745950`.

**Comment by hycsie** [comment]
Hi, I did install from the test branch, while the pulled "mtf_model.py" remains the same.

**Comment by craffel** [comment]
I think you may not have actually installed from the branch. Did you start a new kernel before re-installing T5? Feel free to share the colab and we can try it.

**Comment by hycsie** [comment]
I think it works after I choose to factory reset runtime. Thank @craffel and @daphnei  for the help!
