### ISSUE TITLE
Training Performance for the 11B Model

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#282]
Hello,

Currently, I am training the 11 B model on a custom dataset with the same configuration you used, and the current "examples/sec" is 381 examples only using TPU V3-512.

Could you please share the "examples/sec" for the different models you trained ?

Thanks @adarob and @craffel in advance for your reply

**Comment by craffel** [comment]
Hi Ahmed, what is your input/output sequence length? Picking a random past experiment, training the 11B model on input/target sequence lengths of 512 on a v3-128 gives 86 examples/sec, so 381 examples/sec is totally reasonable for a v3-512 (which should be about 4x faster) assuming you are also using length-512 input/target.

**Comment by agemagician** [comment]
Hi Craffel,

Yes, our sequence length is 512/114 (span denoising), but you have trained the 11B for 2**19 and 2**20 steps, correct?
Based on my calculations, it will take 34/69 days to complete these 2**19/2**20  steps.
It takes approximately 5724 seconds to finish 1k steps, so:
5724 * (2**19 / 1,000) seconds to days = 34 days.
5724 * (2**20 / 1,000) seconds to days = 69 days.

Is my calculations are correct?

**Comment by craffel** [comment]
> Yes, our sequence length is 512/114 (span denoising).

In that case, your examples/sec is a little slow. We got about 1100 examples/second with T5-11B on a v3-1024 with 512/114 sequence length (span denoising). Did you cache the task before running? You may be input-bound if not.

> In your case, you have trained the 11B for 2^19 and 2^20 steps using a batch size of 128 to finish 1/4 epochs, correct?

We trained T5-11B for 1,000,000 steps on batches with 2^20 tokens (= 2048 examples) each.

> Are my calculations are correct or did I miss something?

Training T5-11B on a V3-1024 for 1,000,000 steps with a batch size of 2^20 took us about 25 days.

**Comment by agemagician** [comment]
Thanks for providing this valuable information.

In this case I should get approximetly 550 examples/sec using v3-512.

My current dataset is approximately 150 GB of textual data. I have split it into 6k files and I am reading it using TextLineDataset.

I have tried to cache it by using cache_tasks_main but it didn't work because it is not a TfdsTask:
```
python -m t5.data.cache_tasks_main \
> --tasks=unsupervised_bio_denoising_task \
> --output_cache_dir=gs://xxxxx \
> --module_import=bio_task \
> --alsologtostderr
WARNING:tensorflow:From /home/ahmed/anaconda3/envs/t5_v1/lib/python3.7/site-packages/tensorflow_core/python/compat/v2_compat.py:68: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
Vocab has a size of 128

I0629 21:05:18.016102 140325659158336 cache_tasks_main.py:300] Skipping non-`TfdsTask`: 'unsupervised_bio_denoising_task'
I0629 21:05:18.039242 140325659158336 translations.py:574] ==================== <function annotate_downstream_side_inputs at 0x7f9f0ffe3f80> ====================
I0629 21:05:18.039428 140325659158336 translations.py:574] ==================== <function fix_side_input_pcoll_coders at 0x7f9f0ffe40e0> ====================
I0629 21:05:18.039498 140325659158336 translations.py:574] ==================== <function lift_combiners at 0x7f9f0ffe4170> ====================
I0629 21:05:18.039552 140325659158336 translations.py:574] ==================== <function expand_sdf at 0x7f9f0ffe4200> ====================
I0629 21:05:18.039616 140325659158336 translations.py:574] ==================== <function expand_gbk at 0x7f9f0ffe4290> ====================
I0629 21:05:18.039661 140325659158336 translations.py:574] ==================== <function sink_flattens at 0x7f9f0ffe43b0> ====================
I0629 21:05:18.039735 140325659158336 translations.py:574] ==================== <function greedily_fuse at 0x7f9f0ffe4440> ====================
I0629 21:05:18.039787 140325659158336 translations.py:574] ==================== <function read_to_impulse at 0x7f9f0ffe44d0> ====================
I0629 21:05:18.039830 140325659158336 translations.py:574] ==================== <function impulse_to_input at 0x7f9f0ffe4560> ====================
I0629 21:05:18.039874 140325659158336 translations.py:574] ==================== <function sort_stages at 0x7f9f0ffe47a0> ====================
I0629 21:05:18.039917 140325659158336 translations.py:574] ==================== <function setup_timer_mapping at 0x7f9f0ffe4710> ====================
I0629 21:05:18.039959 140325659158336 translations.py:574] ==================== <function populate_data_channel_coders at 0x7f9f0ffe4830> ====================
```

Any ideas how to cache it correctly without the need to upload it to TensorFlow Datasets?

**Comment by craffel** [comment]
If you are using a TextLineDataset it is probably input-bottlenecked.

You should go ahead and create a custom TFDS, it is not too bad to do and doesn't require uploading anywhere or pushing back to TFDS or anything. https://www.tensorflow.org/datasets/add_dataset

I complained about the fact that task caching requires a TfdsTask to @adarob in the past, maybe we can bully him into fixing this.

**Comment by agemagician** [comment]
I have used TPU Profiler and it says:
"(1) Your program is NOT input-bound because only 0.0% of the total step time sampled is waiting for input. Therefore, you should focus on reducing the TPU time."

<img width="1127" alt="Screenshot 2020-06-29 at 23 49 13" src="https://user-images.githubusercontent.com/6087313/86059525-37dd4c80-ba63-11ea-835f-285060148f51.png">

I will try to use the instructions you mentioned, and hopefully it can increase the performance.

However, I see that making caching doesn't require TfdsTask is a very critical update.
This is going to save a lot of money, power and reduce training time, especially for large scaling problems like mine.

I hope @adarob you can consider how much time and money you will save for T5 users if you could include this feature soon.

**Comment by craffel** [comment]
In my (limited) experience, using a TextLineDataset results in lower examples/s (due to being input-bound) substantially before using a cached dataset.

> However, I see that making caching doesn't require TfdsTask is a very critical update.

It's really pretty straightforward to create a custom TFDS dataset based on a text file, so it doesn't seem totally mission critical, but it definitely would be convenient. If you have any issues creating the custom TFDS, ping this issue.

**Comment by agemagician** [comment]
Thanks a lot @craffel for all the help you provided.
I am really grateful for both of you and @adarob .

I will close this issue for now, and I will implement the custom TFDS dataset.
In case it didn't work out or I didn't see any performance increasement, I will reopen it again.
