### ISSUE TITLE
Do T5 have the next-sentence-predict loss?

### ISSUE THREAD

**Issue by guotong1988** [google-research/text-to-text-transfer-transformer#284]
Input the previous sentence and predict/generate the next sentence.

Thank you very much.

**Comment by craffel** [comment]
Yes, it is a text preprocessor: https://source.corp.google.com/piper///depot/google3/third_party/py/t5/data/preprocessors.py;l=1168

**Comment by guotong1988** [comment]
I cannot visit into the site. Could you please capture a screenshot? Thank you!

**Comment by sharannarang** [comment]
Here's the github pointer: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L1182

**Comment by craffel** [comment]
Whoops, I posted the link to our internal copy. I've edited my comment. Thanks Sharan.

**Comment by guotong1988** [comment]
![image](https://user-images.githubusercontent.com/4702353/86096736-43258c00-bae6-11ea-93a3-a1c9df02c147.png)

Thank you.
