### ISSUE TITLE
Why T5 do not generate the whole next sentence as one of the pretrain loss?

### ISSUE THREAD

**Issue by guotong1988** [google-research/text-to-text-transfer-transformer#285]
T5 has the next-sentence-predict loss.
And the next-sentence-predict loss is not generating the whole next sentence but generating is_next or not_next token.
Why not input the previous sentence and generate the next sentence, instead of input the two sentences?

Thank you very much.

**Comment by craffel** [comment]
The NSP objective implemented in the t5 library corresponds to BERT's NSP objective, where the goal is to classify whether or not two sentences co-occur. There is no objective in t5 corresponding exactly what you're asking but it would be easy to implement. The closest thing currently implemented in the t5 library is the prefix_lm objective which takes a chunk of text, chops it into two pieces, and then the model is trained to predict the second part conditioned on the first part as inputs. The difference is that the two chunks are not necessary sentences, they are just arbitrary-length chunks of text.

**Comment by guotong1988** [comment]
Do you think my idea (input the previous sentence and generate the next sentence) will improve pretraining performance?
