### ISSUE TITLE
Do you think generating the whole next sentence as one of the pretrain loss will improve pretrain performance?

### ISSUE THREAD

**Issue by guotong1988** [google-research/text-to-text-transfer-transformer#286]
T5 has the next-sentence-predict loss. And the next-sentence-predict loss is not generating the whole next sentence but generating is_next or not_next token.

Input the previous sentence and generate the next sentence, instead of input the two sentences. Will it improve the pretrain performance?

Thank you very much.

**Comment by craffel** [comment]
No, I don't think so. What you're describing is not meaningfully different from the prefix_lm objective, which we showed does worse than a MLM objective (see Table 4). The only difference is splitting on sentence boundaries vs. at a random point in a chunk of text. But, feel free to try and let us know!
