### ISSUE TITLE
Fine-tune. Command-line. Define a new task.

### ISSUE THREAD

**Issue by ulapopov** [google-research/text-to-text-transfer-transformer#287]
Fine tuning on a colab or juypyter notebook works fine.
Wanted to fine-tune a model from the command-line. Followed the instructions described in a README file.
https://github.com/google-research/text-to-text-transfer-transformer
I added a new task using --module_import flag.
Inside the module I defined a task:
t5.data.TaskRegistry.add(
    "bioasq_data",
    # Supply a function which returns a tf.data.Dataset.
    dataset_fn=rel_dataset_fn,
    splits=["train", "validation", "test"],
    # Supply a function which preprocesses text from the tf.data.Dataset.
    text_preprocessor=[relevant_preprocessor],
    # Use the same vocabulary that we used for pre-training.
    sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
    # Lowercase targets before computing metrics.
    postprocess_fn=t5.data.postprocessors.lower_text, 
    # We'll use accuracy as our evaluation metric.
    metric_fns=[t5.evaluation.metrics.accuracy],
)

With dataset function defined as follows:
@gin.configurable()
def rel_dataset_fn(split='test', shuffle_files=False):

Got an error: 
ValueError: 'rel_dataset_fn' must have positional args ('split', 'shuffle_files'), got: ()

Changing the definition of the dataset function to not expect any input parameters, produced the same error.

**Comment by craffel** [comment]
Applying the `@gin.configurable()` decorator to `rel_dataset_fn` will change its args:
```Python
>>> import gin
>>> import inspect
>>> def foo(a=10, b=20):
...   print(a, b)
...
>>> print(inspect.getfullargspec(foo).args)
['a', 'b']
>>> @gin.configurable()
... def foo(a=10, b=20):
...   print(a, b)
...
>>> print(inspect.getfullargspec(foo).args)
[]
```
Can you avoid making your dataset function configurable?

**Comment by ulapopov** [comment]
Yes. Removed the decorator and the code runs. Thanks!
