### ISSUE TITLE
Fine-tune. Command-line. Parameters order.

### ISSUE THREAD

**Issue by ulapopov** [google-research/text-to-text-transfer-transformer#288]
Fine-tune a model from the command-line using .tsv file.
Followed the instructions described in a README file.
https://github.com/google-research/text-to-text-transfer-transformer

The script appears to be extremely sensitive to the order of parameters it gets.
The only order that worked for me was:

t5_mesh_transformer  \
  	--tpu="${TPU_NAME}" \
  	--gcp_project="${PROJECT}" \
  	--tpu_zone="${ZONE}" \
  	--model_dir="${MODEL_DIR}" \ 
	--gin_file="gs://t5-data/pretrained_models/small/
operative_config.gin" \
  --gin_file="learning_rate_schedules/constant_0_001.gin" \
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="utils.run.train_dataset_fn = @t5.models.mesh_transformer.tsv_dataset_fn" \
  --gin_param="tsv_dataset_fn.filename = 'gs://my-bucket/train.tsv'" 

	When I change the order, the script will produce errors, - no such file or directory,  and command not found. Is there any reason for that? I didn’t find any documentation describing the nuances of  parameters order.

**Comment by craffel** [comment]
It looks like you are missing some `\` in your command. Any flags preceded by a newline that didn't end in `\` will not be included as part of the command. Should be
```bash
t5_mesh_transformer
--tpu="${TPU_NAME}" \
--gcp_project="${PROJECT}" \
--tpu_zone="${ZONE}" \
--model_dir="${MODEL_DIR}" \
--gin_file="gs://t5-data/pretrained_models/small/operative_config.gin" \
--gin_file="learning_rate_schedules/constant_0_001.gin" \
--gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
--gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
--gin_param="utils.run.train_dataset_fn = @t5.models.mesh_transformer.tsv_dataset_fn" \
--gin_param="tsv_dataset_fn.filename = 'gs://my-bucket/train.tsv'"
```

**Comment by ulapopov** [comment]
You are right in my post I'm missing all but one '\', but I do have all the '\' in my code.
When I change the order of the parameters, the code breaks. There is only one combination that works for me.

**Comment by craffel** [comment]
It isn't the '' that you are missing, it's the backslash `\`. If you are missing that, then newlines will result in separate commands. If you have all of the `\`, then there may be some issue with your bash environment, I can't reproduce your issue.

**Comment by ulapopov** [comment]
All the backslashes are automatically removed from my comments :)
