### ISSUE TITLE
Inference. Command-line.

### ISSUE THREAD

**Issue by ulapopov** [google-research/text-to-text-transfer-transformer#289]
I successfully ran predictions using colabs and jupyter notebooks.
Wanted to run inference from the command-line.
Followed the steps described in README file,
https://github.com/google-research/text-to-text-transfer-transformer ,
“Decode” section.

When I provide input file directly to t5_mesh_transformer as a parameter
t5_mesh_transformer  \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --gin_file="${MODEL_DIR}/operative_config.gin" \
  --gin_file="/home/jupyter/infer.gin" \
  --gin_file="/home/jupyter/sample_decode.gin" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '2x2'" \
  --gin_param="infer_checkpoint_step = 'all'" \
  --gin_param="input_filename = 'gs://my-bucket/input.txt'" \
  --gin_param="output_filename = 'gs://my-bucket/outputs.txt'" 

I get 
--gin_param="input_filename = 'gs://data-eater2/input.txt'" No such file or directory

When I specify the input inside “infer.gin”, the input_filename is not used by the functions. Tried both ‘infer_model’ and ‘decode_from_file’ functions.
# -*-Python-*-
infer_checkpoint_step = "all"
input_filename = "gs://my-bucket/input.txt"
output_filename = "gs://my-bucket/output.txt"

utils.run.mode = "infer"
utils.run.eval_checkpoint_step = %infer_checkpoint_step

utils.tpu_mesh_shape.tpu_topology = '2x2'

utils.infer_model.input_filename = %input_filename
utils.infer_model.output_filename = %output_filename
utils.decode_from_file.input_filename = %input_filename
utils.decode_from_file.output_filename = %output_filename

File utils.py, line 2163:
mode == "infer":
infer_model(estimator, vocabulary, sequence_length, batch_size, model_type,
model_dir, eval_checkpoint_step)

The filename is not passed to the infer_model function.

And by default it is set to “None”. 
input_filename=None (line 1509, utils.py)

**Comment by craffel** [comment]
> --gin_param="input_filename = 'gs://data-eater2/input.txt'" No such file or directory

I think This is the same issue as #288; you are missing trailing `\` in your bash command.

**Comment by ulapopov** [comment]
I do have the '\' in my code. It's just when I copy-paste it here, the editor automatically removes the '\'

**Comment by craffel** [comment]
See #288.
