### ISSUE TITLE
loss calculation

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#29]
Hi,

Regarding loss calculation, I have 2 questions:
1. Do you apply any kind of class weight balancing or any kind of weight balance for the vocab?
2. Do you calculate the loss as a mean of all tasks loss, or do you calculate each task loss separately and then sum them up?

**Comment by craffel** [comment]
Hi, the loss for all tasks is just a standard maximum likelihood (teacher-forced) loss. There is nothing fancy or anything done on a task-specific basis. 
1. No.
2. The loss is just a sum over all tokens in the sequence, from whatever tasks. The loss calculation is completely unaware of different tasks.
