### ISSUE TITLE
Frozen variables

### ISSUE THREAD

**Issue by marcospiau** [google-research/text-to-text-transfer-transformer#292]
Hi guys,

I'm performing some experiments mainly based on the t5-trivia notebook (https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb). I'd like to know if there are some frozen variables, since the logging outputs show that the number of total variables is not equal to the number of trainable ones. Bellow are the excerpts of interest (small model):
```
...
INFO:tensorflow:Trainable Variables            count: 99      Total size: 60506624         Total slice_size: 60506624       
INFO:tensorflow:All Variables                  count: 105     Total size: 60691328         Total slice_size: 60691328 
...
variables: 6.07e+07
 variables/trainable: 6.05e+07
 variables/untrainable: 1.85e+05
...
```

**Comment by adarob** [comment]
@nshazeer can you comment on what the untrainable variables are?

**Comment by nshazeer** [comment]
The trainable variables are the model parameters.  The "untrainable" variables are the accumulator variables in the (Adafactor) optimizer (i.e. the place where you keep track of the approximate second moments of the gradients).  They are not frozen.  The optimizer does change them.  The whole "trainable" thing is a signal to the optimizer to tell it what are the parameters to optimize.

**Comment by marcospiau** [comment]
Thank you!!
