### ISSUE TITLE
Cache Tasks for TextLineTask Runs Sequentially

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#299]
I have converted my generic task to TextLineTask in order to cache it, but "t5.data.cache_tasks_main" runs the cache generation sequentially and doesn't use multithreading, even that I have 6k files.

My task looks like:

```
python -m t5.data.cache_tasks_main \
--tasks=unsupervised_bio_denoising_task_cache \
--output_cache_dir=/xxx_path_xxx/ \
--module_import=bio_task \
--alsologtostderr
```

My task file like:
```
import functools
import t5.data
from t5.data import postprocessors as t5_postprocessors
from t5.evaluation import metrics as t5_metrics
from t5.data.sentencepiece_vocabulary import SentencePieceVocabulary
from t5.data import utils as dataset_utils
import tensorflow as tf

TaskRegistry = t5.data.TaskRegistry

trainFilesPath = tf.io.gfile.glob('gs://xxx/train_*')
validFilesPath = tf.io.gfile.glob('gs://xxx/valid_*')

vocab_model_path = 'vocab.model'

vocab = SentencePieceVocabulary(vocab_model_path,extra_ids=100)
print("Vocab has a size of %d\n" %vocab.vocab_size)

bio_dataset_path = {
    "train": trainFilesPath,
    "validation": validFilesPath
}

def text_line_preprocessor(dataset):

  def _to_inputs_and_targets(input_dict):
    seq_str = input_dict['targets']
    return {"inputs": seq_str, "targets": seq_str}

  return dataset.map(_to_inputs_and_targets, num_parallel_calls=tf.data.experimental.AUTOTUNE)

def parse_textlines(dataset):
  def _parse_fn(line):
    return {'targets': line}

  return dataset.map(
      _parse_fn, num_parallel_calls=tf.data.experimental.AUTOTUNE)

t5.data.TaskRegistry.remove("unsupervised_bio_denoising_task_cache")
t5.data.TaskRegistry.add(
    "unsupervised_bio_denoising_task_cache",
    dataset_utils.TextLineTask,
    split_to_filepattern=bio_dataset_path,
    skip_header_lines=0,
    text_preprocessor=[
          parse_textlines,
          text_line_preprocessor
    ],
    token_preprocessor = t5.data.preprocessors.unsupervised,
    output_features=t5.data.Feature(vocabulary=vocab,add_eos=True),
    metric_fns=[t5.evaluation.metrics.accuracy],
)
```

@adarob What did I miss here ?

**Comment by adarob** [comment]
Can you try setting the paths to be 'gs://xxx/train_*' and 'gs://xxx/valid_*' instead of globbing first?

**Comment by agemagician** [comment]
Now, it seems there are 40 threads running but the CPU utilization is very low, is it normal  ?

<img width="1440" alt="Screenshot 2020-07-08 at 15 17 07" src="https://user-images.githubusercontent.com/6087313/86923348-34feed80-c12e-11ea-9f32-2e7ba7bd908c.png">

**Comment by adarob** [comment]
It's probably I/O bound. It may help to copy the files from GCS to the
local machine.

**Comment by agemagician** [comment]
Still the same, even after copying the data to local machine.
I will wait until tomorrow, maybe it is processing currently the validation split which is only 1 file, while the training is 6k files.
I will update the issue again.

**Comment by adarob** [comment]
If you really need it done quickly, I'd suggest running it with DataFlow.

**Comment by agemagician** [comment]
I have switched the direct_running_mode to multi_processing and it provides a little bit more CPU utilization but still to slow.
I think, I will have to switch to DataFlow as you recommended.

Thanks again @adarob for your help.

I will close the issue now as it seems there is upper limit to multi-threading with apache beam on local machines.
