### ISSUE TITLE
Any plans to publish multilingual models?

### ISSUE THREAD

**Issue by davidhsv** [google-research/text-to-text-transfer-transformer#3]

**Comment by craffel** [comment]
Hi, not sure what you are asking - the pre-trained models are multilingual in the sense that they have been pre-trained on WMT EnDe, EnFr, and EnRo, and the vocabulary supports English, French, German, and Romanian. If you are asking whether we plan to train and models which support more languages than this and/or are applied to multilingual benchmarks (XNLI etc), then no, we don't have any plans to do this.
