### ISSUE TITLE
t5-trivia notebook fails to import `google-colab`

### ISSUE THREAD

**Issue by jonadsimon** [google-research/text-to-text-transfer-transformer#303]
When running `!pip install -q t5` the package `google-colab` fails to install with the message:
```
google-colab 1.0.0 has requirement six~=1.12.0, but you'll have six 1.15.0 which is incompatible.
```

But if I first manually install the (older) compatible version of the `six` package, then the rest of the installation fails.

I'm not sure how to fix this conflicting versioning problem, and for now am simply ignoring the error. However I've noticed that the notebook crashes fairly often, which may be related.

Sidenote: The packages `datascience` and `albumentations` also fail to install with similar conflicting version issues, but those can be rectified by manually installing them prior to installing t5.

**Comment by adarob** [comment]
Thanks for raising this. It's unlikely the six version is causing the issues you see, but I will raise this with the colab team nevertheless, as I'm not sure why they have their version pinned.

**Comment by adarob** [comment]
I filed a bug with Colab and they should update their dependencies soon.
