### ISSUE TITLE
Unsupervised Training and reduce_concat_tokens

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#309]
Hi,

In the "denoise.gin" the "unsupervised preprocessosr" uses "reduce_concat_tokens", which is great to replace padding.
However, after testing it in large scale training, I notice the the model converge very fast compared to Bert and other models I trained on the same dataset.

After some digging, I found a big problem, which I need to confirm from you.
Assuming my dataset looks like:
```
A A T G
C X P Y
```

The result of using "reduce_concat_tokens" will be:
`A A T G C X P Y </s>`
This means the model will simply concatenate samples without having any seperate token between different samples.
I also check and didn't find any masking ids to mask different samples separately.
This will highly affect the model as it doesn't learn that some tokens comes from different samples.

If I removed the "reduce_concat_tokens" from the "noise.gin", the samples is separated correctly:
```
A A T G  </s>
C X P Y  </s>
```

@adarob  Is my understanding is correct or did I miss something ?

**Comment by craffel** [comment]
Your understanding is correct. It doesn't happen that often and it doesn't seem to harm the model in any meaningful way. See https://github.com/google-research/text-to-text-transfer-transformer/issues/95#issuecomment-590551530

**Comment by agemagician** [comment]
Thanks a lot @craffel for the clarification, but in our case (protein sequences), it is extremely crucial to separate documents (protein sequences).
I have removed "reduce_concat_tokens", from the gin file, and now they are separated correctly.

Thanks again.

**Comment by craffel** [comment]
I can see why it would be more important for protein sequences! Removing the reduce_concat step makes sense.

**Comment by agemagician** [comment]
@craffel  
Sorry, but I have two more follow-up questions.
1. Are T5 + Mesh transformer will automatically pad the sequences ?
2. Is the generated padding is automatically masked during training ?

**Comment by craffel** [comment]
> T5 + Mesh transformer will automatically pad the sequences, correct ?

Yes.

> Is the generated padding are automatically masked during training ?

Yes.

**Comment by agemagician** [comment]
Thanks, thanks and another thanks for all the help you are providing 👍
