### ISSUE TITLE
NotImplementedError in Colab Notebook

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#318]
Yesterday it worked fine today when it tries to import `tensorflow_gcs_config` I get
```
NotImplementedError: unable to open file: _gcs_config_ops.so, from paths: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so']
caused by: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl11string_viewEPPKNS_6TensorE']
```

**Comment by Voil8** [comment]
try this `!pip install -U tensorflow-gcs-config==2.1.3`

**Comment by marton-avrios** [comment]
...a better solution would be to replace `!pip install -q t5` with `!pip install -q t5 tensorflow-text==2.2`. It also solves another problem later during fine-tuning. See #320.

**Comment by Arpitshah139** [comment]
I am having the same issue.. I tried both the solutions by !pip install -U tensorflow-gcs-config==2.1.3 and !pip install -q t5 , !pip install -q t5 tensorflow-text==2.2 but still facing the same issue.

**Comment by mrqorib** [comment]
@kripa-george-tfs  This solution works for me:

In the first cell, add the following to connect to Google Storage: `%env USE_AUTH_EPHEM=0`

Then install the following: `!pip install -U tensorflow-gcs-config==2.1.3`

And replace the `!pip install -q t5` with `!pip install tensorflow==2.3 t5 tensorflow-text==2.3`. Afterward, you will see an error message saying you need to restart the runtime to use the new packages. After I restart the runtime (and run the cells again), it works for me

**Comment by CharlieGalvin** [comment]
I am now having the same problem after trying the solutions above :(
