### ISSUE TITLE
Unable to import tensorflow_gcs_config in t5_trivia colab notebook

### ISSUE THREAD

**Issue by Voil8** [google-research/text-to-text-transfer-transformer#319]
Upon running line `import tensorflow_gcs_config` (in t5_trivia colab notebook, setup section) I get this error,
```
---------------------------------------------------------------------------
NotImplementedError                       Traceback (most recent call last)
<ipython-input-2-3bb7f36f8553> in <module>()
----> 1 import tensorflow_gcs_config

1 frames
/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/__init__.py in _load_library(filename, lib)
     55   raise NotImplementedError(
     56       "unable to open file: " +
---> 57       "{}, from paths: {}\ncaused by: {}".format(filename, filenames, errs))
     58 
     59 _gcs_config_so = _load_library("_gcs_config_ops.so")

NotImplementedError: unable to open file: _gcs_config_ops.so, from paths: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so']
caused by: ['/usr/local/lib/python3.6/dist-packages/tensorflow_gcs_config/_gcs_config_ops.so: undefined symbol: _ZN10tensorflow15OpKernelContext5inputEN4absl11string_viewEPPKNS_6TensorE']
```
`tf.__version__` is '2.3.0'

**Comment by Voil8** [comment]
this solved my problem
`!pip install -U tensorflow-gcs-config==2.1.3`

**Comment by Kevinweisl** [comment]
Hi @Voil8, 

`!pip install -U tensorflow-gcs-config==2.1.3` seems to solve this problem last week but it doesn' t work today.

It raises the following error:
```
InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=GcsConfigureCredentials; signature=json:string -> >; NodeDef: {{node GcsConfigureCredentials}}
``` 

Do you face the same problem?

**Comment by yixingfu** [comment]
> Hi @Voil8,
> 
> `!pip install -U tensorflow-gcs-config==2.1.3` seems to solve this problem last week but it doesn' t work today.
> 
> It raises the following error:
> 
> ```
> InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=GcsConfigureCredentials; signature=json:string -> >; NodeDef: {{node GcsConfigureCredentials}}
> ```
> 
> Do you face the same problem?
Try this
`!pip install -U tensorflow-gcs-config==2.3.0`

**Comment by khalman-m** [comment]
I have the same issue as @Kevinweisl 
`!pip install -U tensorflow-gcs-config==2.3.0` gives me the original `NotImplementedError: unable to open file: _gcs_config_ops.so` error on the hosted runtime.

Should we reopen this?

**Comment by yixingfu** [comment]
I agree. As a workaround you may try various combination of TF version and gcs config version. For me TF 2.3.0 + gcs config 2.3.0 worked, hence I suggested.

**Comment by adarob** [comment]
It looks like one of our dependencies is downgrading tf.
