### ISSUE TITLE
ValueError: `mesh_shape` must be a vector of size 4 with positive entries; got [2 2 2]

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#320]
Since yesterday `pip install -q t5` in the colab notebook also installs tensorflow 2.3 (and removes the default 2.2 on Colab). Later when fine-tuning it causes the aforementioned error. 

```
/usr/local/lib/python3.6/dist-packages/tensorflow/python/tpu/topology.py in _parse_topology(self, serialized)
    109     if len(self._mesh_shape) != 4 or any(self._mesh_shape < 1):
    110       raise ValueError("`mesh_shape` must be a vector of size 4 with positive "
--> 111                        "entries; got {}".format(self._mesh_shape))
    112 
    113     if proto.num_tasks < 0:

ValueError: `mesh_shape` must be a vector of size 4 with positive entries; got [2 2 2]```

**Comment by marton-avrios** [comment]
Temporary solution can be to replace `!pip install -q t5` with `!pip install -q t5 tensorflow-text==2.2`. tensorflow-text relased a new version on 29th July and it now requires tensorflow 2.3

**Comment by adarob** [comment]
@nshazeer looks like mesh tf is broken with tf 2.3

**Comment by marton-avrios** [comment]
Starting from 2.3 tensorflow requires it to be of size 4

**Comment by alextp** [comment]
@rxsang have you seen this error before? It seems like some changes in 2.3 broke t5.

**Comment by marton-avrios** [comment]
mesh_shape should be of size 4 instead of 3 since tensorflow 2.3

**Comment by nshazeer** [comment]
Does anyone know what code exactly is passing in a 3d shape?

**Comment by rxsang** [comment]
This behavior is changed in https://github.com/tensorflow/tensorflow/commit/a9e036d99c5e38f4fdf8fc043a626fdd735c4844#diff-cef3a30d8a1a9637b6e6d1c643813259

**Comment by rxsang** [comment]
Does changing the `mesh_shape` from `[2 2 2]` to `[2 2  1 2]` work? It seem the cl changes the mesh shape from `[x y core]` to `[x y z core]`.

**Comment by adarob** [comment]
fyi, this same code works internally

**Comment by adarob** [comment]
@rxsang any update on this bug?

**Comment by rxsang** [comment]
It may indicate your Cloud TPU worker (or Colab TPUs) may not be updated to TF2.3, upgrading them to TF2.3 should work.
