### ISSUE TITLE
Memory usage of t5_cache_tasks

### ISSUE THREAD

**Issue by arglog** [google-research/text-to-text-transfer-transformer#323]
Hi T5 authors,

Does the command `t5_cache_tasks` (or the script `cache_tasks_main.py`) keep all intermediate data in memory and only write to disk after all processings are done? 

I was catching a text line dataset (~800GB) and found the script didn't write anything to the disk since the start of running, and after 10 hrs, the process's memory usage exceeded the system RAM and the process was killed.  My running command:
```bash
t5_cache_tasks \
    --tasks=my_task \
    --output_cache_dir=./tfrecord \
    --pipeline_options="--runner=DirectRunner,--direct_num_workers=0,--direct_running_mode=multi_processing"
```

Is this an expected behavior? Is it possible to let the script gradually write results to disk as it's running, as opposed to having everything in memory and write only after the processing is done?

Thanks!

**Comment by adarob** [comment]
We actually run these jobs on a system similar to DataFlow internally at Google, so I'm not familiar with the behavior of DirectRunner wrt to memory. However this statement isn't very promising: https://beam.apache.org/documentation/runners/direct/#memory-considerations. 

I'd suggest either using DataFlow (or something similar) or investigating how to avoid memory issues with DirectRunner. Please report back if you find a nice solution!

**Comment by arglog** [comment]
Hi,

I was able to cache the task using DataFlow.

Thanks!
