### ISSUE TITLE
eval ignores on the fly gin modifications

### ISSUE THREAD

**Issue by marton-avrios** [google-research/text-to-text-transfer-transformer#324]
https://github.com/google-research/text-to-text-transfer-transformer/blob/94c913c3616bfe312577b3638d61bbbdc5682f0f/t5/models/mtf_model.py#L264

`eval` reloads model config so I cannot change to beam search for example after model dir (and `operative_config` in it) was created. Is that intentional? Is there a simple way to do it apart from directly calling `mesh_tensorflow.transformer.utils.eval_model()`?

**Comment by adarob** [comment]
MtfModel now supports an `extra_gin_bindings` argument that fixes this issue.
