### ISSUE TITLE
Question about number of parameters on large model

### ISSUE THREAD

**Issue by marcospiau** [google-research/text-to-text-transfer-transformer#326]
Hi guys,

I'm performing some experiments with the MtfModel API , initializing the weights with the released pretrained checkpoints, using the models from sizes small, base and large which, accordingly to the github repo, have 60, 200 and 770 million of parameters. I do understand that these numbers are approximations, but on the logging infos for the large models, the approximated total number of parameters is close to 740 million. Below are the portions of logging I am referring to (large model):

```
...
INFO:tensorflow:Trainable Variables            count: 388     Total size: 737668096        Total slice_size: 92317824
INFO:tensorflow:All Variables                  count: 400     Total size: 738908544        Total slice_size: 92927152
...
INFO:tensorflow:Initializing variables from gs://t5-data/pretrained_models/large/model.ckpt-1000700:
...
```

For the small and base models, the number is closer to the informed approximated numbers. Am I doing anything wrong or these are the expected values?

Thanks in advance.

**Comment by craffel** [comment]
Yes, could just be a typo...

**Comment by marcospiau** [comment]
Thank you @craffel !
