### ISSUE TITLE
Issue  Running T5 in colab TPU

### ISSUE THREAD

**Issue by ashispapu** [google-research/text-to-text-transfer-transformer#328]
Hi Team,

I was trying to do a pre training of T5 from scratch on colab. I could see if i install t5 using (pip install t5[gcp]), and tried to connect to execute ` tf.tpu.experimental.initialize_tpu_system(tpu)`, getting  below error.

`InvalidArgumentError: NodeDef expected inputs 'string' do not match 0 inputs specified; Op<name=_Send; signature=tensor:T -> ; attr=T:type; attr=tensor_name:string; attr=send_device:string; attr=send_device_incarnation:int; attr=recv_device:string; attr=client_terminated:bool,default=false; is_stateful=true>; NodeDef: {{node _Send}}`

If install/ upgrade tensorflow, it gets resolved, however import of t5 does not work as below.
`
import t5`

`NotFoundError: /usr/local/lib/python3.6/dist-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE`

Please let me know how if there is a way to resolve this.
Thanks.

**Comment by agemagician** [comment]
I have a similar issue on Colab.

My workaround is to install the following commit:
!pip install -q git+https://github.com/google-research/text-to-text-transfer-transformer.git@1e269e72a981fde4ea64a88a0a0d8cc88871e20a

**Comment by ashispapu** [comment]
I also got the same issues, when I tried to connect the a VM instance with a TPU node(v2-8) and execute `tf.tpu.experimental.initialize_tpu_system(tpu)`

Is there anyone facing the same issue ?

**Comment by adarob** [comment]
This happens when there is a mismatch between the TPU binary and the TF version. Make sure both are version 2.3.x.

**Comment by ashispapu** [comment]
@adarob Do I need to install TF separately on the TPU node ? Since I only installed on VM instance.

**Comment by adarob** [comment]
You can set `--tpu-version` when you launch. By default it should be 2.3 as of last week.

**Comment by ashispapu** [comment]
Thanks. I checked the TPU and VM version of TF and its same `2.3.0.dev20200620`. When I try to import T5(both 0.6.2 and 0.6.3), It does not work as below.
`tensorflow.python.framework.errors_impl.NotFoundError: /home/revt5/.local/lib/python3.7/site-packages/tensorflow_text/python/metrics/_text_similarity_metric_ops.so: undefined symbol: _ZN10tensorflow14kernel_factory17OpKernelRegistrar12InitInternalEPKNS_9KernelDefEN4absl11string_viewESt10unique_ptrINS0_15OpKernelFactoryESt14default_deleteIS8_EE`

**Comment by adarob** [comment]
Try `pip install --upgrade tensorflow-text==2.3.0`
