### ISSUE TITLE
"NameError: name 't5' is not defined" in the Colab notebook 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#33]
Potentially a trivial question: 

When using the Colab notebook, it does not recognize `t5` as a package. 
Any thought what could be going wrong?  

![Screen Shot 2020-01-06 at 3 41 36 PM](https://user-images.githubusercontent.com/2441454/71857083-07f85200-309b-11ea-92f7-edcd9866c9ea.png)

**Comment by adarob** [comment]
Did you run the cell "Install an import required dependencies" successfully?
