### ISSUE TITLE
Fine-tuning makes no progress

### ISSUE THREAD

**Issue by albertoandreottiATgmail** [google-research/text-to-text-transfer-transformer#330]
Hello,

I've been following the instructions from documentation about fine tuning, with the following command,

t5_mesh_transformer \
  --tpu="t5-tpu" \
  --gcp_project="t5-fine-tune" \
  --model_dir="gs://t5-data/pretrained_models/small" \
  --t5_tfds_data_dir="gs://pedrito/data" \
  --gin_file="dataset.gin" \
  --gin_param="MIXTURE_NAME = 'leave_one_out_wmt_t2t_ende_v003'" \
  --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin"

I'm using an instance in Compute Engine, with a TPU. The scripts freezes, with TPU showing no utilization(almost 0%).
Also, dataset download and creation is extremely slow taking around 10 hours.
Am I doing something wrong?

thanks!

**Comment by craffel** [comment]
The `leave_one_out_wmt_t2t_ende_v003` mixture involves training on all tasks we considered in the paper (including unsupervised C4 training) except for WMT EnDe. If you choose that task for fine-tuning, the binary will first try to download all of the datasets, including C4 which will take about 335 CPU days to download. If you would like to use C4 or a mixture that includes C4, you should follow these instructions first: https://github.com/google-research/text-to-text-transfer-transformer#c4
