### ISSUE TITLE
Can we do TensorFlow FineTuning on GPU/CPU for NER

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#336]
I am trying to get the T5 model to work for NER Task on Tensorflow. However, from what I can gather we can't use the Tensorflow code to fine-tune things on GPU/CPU and we can only export the model to serve results for tasks that T5 already works on? To fine-tune for NER, I will need a TPU, right?

**Comment by craffel** [comment]
No, you can train, fine-tune, and run inference on tpu, gpu, or cpu. See e.g. https://github.com/google-research/text-to-text-transfer-transformer#gpu-usage

**Comment by vkaul11** [comment]
Thanks, for CPU usage I just need to skip this line? `--gin_param="utils.run.mesh_devices = ['gpu:0']"`
Also if I want to install only tensorflow T5 package on my local machine should I use setup.py or pip install t5 is sufficient?

**Comment by craffel** [comment]
For CPU you should be able to just set --gin_param="utils.run.mesh_shape = []" and skip the mesh_devices flag, though it will be incredibly slow on a CPU. pip is fine.
