### ISSUE TITLE
Logging info

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#337]
Hi everybody,

Is there a way to log in Colab #epochs for training and fine-tuning as well?
Otherwise, if I want to derive #epochs from the performed steps, is this formula: Z = (batch_size*performed_steps) / (length_of_dataset) enough?
Z should represent #epochs

**Comment by craffel** [comment]
Hi, logging the number of epochs is extremely nontrivial when using packing, see https://github.com/google-research/text-to-text-transfer-transformer/issues/174#issuecomment-614797955 If you turn off packing, then your formula is correct, but packing helps avoid wasting a lot of computation.
