### ISSUE TITLE
What is "TOPOLOGY"? 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#34]
Here and there in the readme I see mentions of "topology" in the readme (for instance, `utils.tpu_mesh_shape.tpu_topology = '2x2'`).  I couldn't find the definition (either the readme or the paper). Could you elaborate?

**Comment by craffel** [comment]
The topology is the shape of the TPU slice used for training. For example, "2x2" refers to a slice of size 8 (since each TPU in the slice has two cores). Assuming you are using a v2 TPU, the correspondence is something like
2x2 = v2-8
4x4  = v2-32
4x8 = v2-64
8x8 = v2-128
etc.

**Comment by danyaljj** [comment]
Got it, thanks!
