### ISSUE TITLE
Can we keep multiple files together in DATA_DIR for training

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#345]
Hi, I have a large data set which is split into 100,000 small .tsv chunks for NER Data like 
Obama is a President /t Obama;

where tab separation is there between input and output. Do I need to combine these files into one .tsv file if I have to use text-to-text format ? I suppose TextLineTask maps to the text-to-text format.

**Comment by craffel** [comment]
You can create individual tf.data.Datasets for each file and combine them inside of the `dataset_fn` of a standard `Task`:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/utils.py#L384
https://www.tensorflow.org/tutorials/load_data/text#load_text_into_datasets

**Comment by vkaul11** [comment]
Is it possible to use TFRecord format also as I don't see that in the notebook.

**Comment by craffel** [comment]
Yes, all you need is a function that returns a tf.data.Dataset when constructing the Task
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/utils.py#L384
You could use a https://www.tensorflow.org/api_docs/python/tf/data/TFRecordDataset
