### ISSUE TITLE
Task Registry and prefix input text with task name

### ISSUE THREAD

**Issue by ashispapu** [google-research/text-to-text-transfer-transformer#347]
Hi Team,

While pre training and fine tuning T5 on a custom data/language, I came across the task registry and prefixing task name to input text. It would be helpful if you could clarify below queries, which may be very fundamental to  train T5.

1.  Why do we add individual tasks to TaskRegistry and how does it help in pre training ?
2.  What is the significance of prefixing the task name in input text while fine tuning? 
3. Is there any particular way/trick to prefix the task names while fine tuning a custom pre trained  model ? Considering both cases  as below .
  a> The pretrained model has the downstream task already
  b> The downstream task is a new one

Thank you .

**Comment by craffel** [comment]
Hi, 

> Why do we add individual tasks to TaskRegistry and how does it help in pre training ?

Adding a Task to the TaskRegistry just allows it to be used for feeding data into the model. It doesn't have any direct impact on pre-training or fine-tuning unless you choose a Task (or Mixture that contains the task) when training a model.

> What is the significance of prefixing the task name in input text while fine tuning?

It is for the model to determine what it should do with some input text in the multi-task setting.

> Is there any particular way/trick to prefix the task names while fine tuning a custom pre trained model ? Considering both cases as below .

If you are fine-tuning on a task that was included in the pre-training mixture, you should use the same prefix during fine-tuning. If it's a new downstream task, you can use any new prefix you want.

**Comment by ashispapu** [comment]
Thanks  @craffel  for the clarification.
