### ISSUE TITLE
gs:// causes exception in t5_mesh_transformer with t5[gcp]

### ISSUE THREAD

**Issue by AlexanderRayCarlson** [google-research/text-to-text-transfer-transformer#348]
I created a tpu instance and debian VM with `ctpu up`, installed t5[gcp] as described [here](https://github.com/google-research/text-to-text-transfer-transformer/#setting-up-tpus-on-gcp).

Encountered what looks like a parsing issue in the file_io used by t5_mesh_transformer that causes it to throw an exception before training can begin. 

If I remove the `gs://` from MODEL_DIR and DATA_DIR then it will train until the first save, then fail to save because it is missing the `gs://`

Works fine on colab so may be a difference between t5 and t5[gcp].

Tensorflow version is the 2.2.0 installed with t5[gcp].

MODEL_DIR=gs://mybucket/model/11B
DATA_DIR=gs://mybucket/data

> >   username@instance:~$ t5_mesh_transformer  \
> >   --tpu="${TPU_NAME}" \
> >   --gcp_project="${PROJECT}" \
> >   --tpu_zone="${ZONE}" \
> >   --model_dir="${MODEL_DIR}" \
> >   --t5_tfds_data_dir="${DATA_DIR}" \
> >   --gin_file="dataset.gin" \
> >   --gin_param="utils.tpu_mesh_shape.model_parallelism = 1" \
> >   --gin_param="utils.tpu_mesh_shape.tpu_topology = '${TPU_SIZE}'" \
> >   --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
> >   --gin_file="gs://t5-data/pretrained_models/small/operative_config.gin" \
> >   --gin_param="run.train_steps = 1010000"

> WARNING:tensorflow:From /usr/local/lib/python3.7/dist-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.op
> s.variable_scope) is deprecated and will be removed in a future version.
> Instructions for updating:
> non-resource variables are not supported in the long term
> Traceback (most recent call last):
>   File "/usr/local/bin/t5_mesh_transformer", line 8, in <module>
>     sys.exit(console_entry_point())
>   File "/usr/local/lib/python3.7/dist-packages/t5/models/mesh_transformer_main.py", line 254, in console_entry_point
>     app.run(main)
>   File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 299, in run
>     _run_main(main, args)
>   File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 250, in _run_main
>     sys.exit(main(argv))
>   File "/usr/local/lib/python3.7/dist-packages/t5/models/mesh_transformer_main.py", line 143, in main
>     tf.io.gfile.makedirs(FLAGS.model_dir)
>   File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/lib/io/file_io.py", line 442, in recursive_create_dir_v2
>     _pywrap_file_io.RecursivelyCreateDir(compat.as_bytes(path))
> tensorflow.python.framework.errors_impl.InvalidArgumentError: 'object' must be a non-empty string. (File: gs://mybucket/)
> username@instance:~$

**Comment by adarob** [comment]
Is your GCS bucket actually called "mybucket"?

**Comment by AlexanderRayCarlson** [comment]
:sweat_smile: actually called mybucket2 (much more creative) 
![image](https://user-images.githubusercontent.com/15145538/90431375-cb9fc200-e07d-11ea-8c6c-a1b1db2bc1e7.png)
 and fixing this resolved the issue. My mistake! "Must be a non-empty string" had me confused as to the cause. Thank you!
