### ISSUE TITLE
Can Task Registry only work on Google Cloud

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#352]
I was trying to run some tasks to first check if they work on my local machine but I am getting Google Authentication errors:

```
"""Add Tasks to registry."""
import collections
import functools
import t5
import tensorflow.compat.v1 as tf
from t5.data import postprocessors
from t5.data import preprocessors
from t5.data.utils import Feature
from t5.data.utils import get_default_vocabulary
from t5.data.utils import set_global_cache_dirs
from t5.data.utils import TaskRegistry
from t5.evaluation import metrics
import tensorflow_datasets as tfds

ner_dataset_path = {
    "train": '/Users/vivekkaul/NER_data_0_train.tsv',
    "validation": '/Users/vivekkaul/NER_data_0_train.tsv'
}

def ner_preprocessor(ds):
  def to_inputs_and_targets(ex):
    """Map {"question": ..., "answer": ...}->{"inputs": ..., "targets": ...}."""
    return {
        "inputs":
             tf.strings.join(
                 ["ner:", ex["inputs"]]),
        "targets": ex["targets"]
    }
  return ds.map(to_inputs_and_targets,
                num_parallel_calls=tf.data.experimental.AUTOTUNE)

t5.data.TaskRegistry.add(
    "ner_data",
    t5.data.TextLineTask,
    split_to_filepattern=ner_dataset_path,
    text_preprocessor=[
      functools.partial(
          t5.data.preprocessors.parse_tsv,
          field_names=["inputs", "targets"]),
          ner_preprocessor
],
    postprocess_fn=t5.data.postprocessors.lower_text,
    metric_fns=[t5.evaluation.metrics.accuracy],
)

ner_task = t5.data.TaskRegistry.get("ner_data")
ds = ner_task.get_dataset(split="validation", sequence_length={"inputs": 128, "targets": 32})
print("A few preprocessed validation examples...")
for ex in tfds.as_numpy(ds.take(5)):
  print(ex)
```
and I get the error

```
2020-08-18 11:34:51.639658: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-18 11:34:51.663606: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fc31168e8e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-18 11:34:51.663623: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
2020-08-18 11:34:53.183222: W tensorflow/core/platform/cloud/google_auth_provider.cc:184] All attempts to get a Google authentication bearer token failed, returning an empty token. Retrieving token from files failed with "Invalid argument: Error executing an HTTP request: HTTP response code 400 with body '{
  "error": "invalid_grant",
  "error_description": "reauth related error (rapt_required)",
  "error_subtype": "rapt_required"
}'". Retrieving token from GCE failed with "Failed precondi
```t
Can we try fine-tuning on CPU with task?

**Comment by craffel** [comment]
The entire `t5` library should be runnable locally, i.e. not on Google Cloud. I think TFDS may be trying to read stuff off of Cloud (like dataset info files) and it looks like you might not be set up to read from Cloud. I don't think this is an issue with the `t5` library though.

**Comment by vkaul11** [comment]
Thanks, so what I did now was setup everything in local path but I am getting this error. My model_dir is same as the directory used for gs://t5-data/pretrained_models/small/ (I copied the contents locally). Do I have to point it to exact model checkpoint?

```
t5_mesh_transformer  --model_dir= '/Users/vivekkaul/t5-small-model/small' --gin_file="dataset.gin" --gin_file='/Users/vivekkaul/t5-small-model/small/operative_config.gin' --gin_param="utils.run.mesh_shape = []" --gin_param="utils.run.train_dataset_fn = @t5.models.mesh_transformer.tsv_dataset_fn" --gin_param="tsv_dataset_fn.filename = '/Users/vivekkaul/t5-ner/data/NER_data_0_train.tsv'" --gin_param="run.train_steps = 1001000" --gin_file="learning_rate_schedules/constant_0_001.gin"
WARNING:tensorflow:From /Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow/python/compat/v2_compat.py:96: disable_resource_variables (from tensorflow.python.ops.variable_scope) is deprecated and will be removed in a future version.
Instructions for updating:
non-resource variables are not supported in the long term
/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/t5/models/mesh_transformer.py:233: UserWarning: get_sentencepiece_model_path is deprecated. Please pass the mixture or task vocabulary directly to the Mesh TensorFlow Transformer instead.
  "get_sentencepiece_model_path is deprecated. Please pass the mixture or "
INFO:tensorflow:model_type=bitransformer
I0818 13:43:04.449634 4480896448 utils.py:2062] model_type=bitransformer
INFO:tensorflow:mode=train
I0818 13:43:04.449772 4480896448 utils.py:2063] mode=train
INFO:tensorflow:sequence_length={'inputs': 512, 'targets': 512}
I0818 13:43:04.449821 4480896448 utils.py:2064] sequence_length={'inputs': 512, 'targets': 512}
INFO:tensorflow:batch_size=2048
I0818 13:43:04.449963 4480896448 utils.py:2065] batch_size=2048
INFO:tensorflow:train_steps=1001000
I0818 13:43:04.450063 4480896448 utils.py:2066] train_steps=1001000
INFO:tensorflow:mesh_shape=[]
I0818 13:43:04.450102 4480896448 utils.py:2067] mesh_shape=[]
INFO:tensorflow:layout_rules=ensemble:ensemble,batch:batch,d_ff:model,heads:model,vocab:model,experts:batch
I0818 13:43:04.450139 4480896448 utils.py:2068] layout_rules=ensemble:ensemble,batch:batch,d_ff:model,heads:model,vocab:model,experts:batch
INFO:tensorflow:Building TPUConfig with tpu_job_name=None
I0818 13:43:04.450194 4480896448 utils.py:2083] Building TPUConfig with tpu_job_name=None
Traceback (most recent call last):
  File "/Users/vivekkaul/.pyenv/versions/t5_setup/bin/t5_mesh_transformer", line 10, in <module>
    sys.exit(console_entry_point())
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 254, in console_entry_point
    app.run(main)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/absl/app.py", line 299, in run
    _run_main(main, args)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/absl/app.py", line 250, in _run_main
    sys.exit(main(argv))
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 248, in main
    model_dir=FLAGS.model_dir)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/gin/config.py", line 1078, in gin_wrapper
    utils.augment_exception_message_and_reraise(e, err_str)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise
    six.raise_from(proxy.with_traceback(exception.__traceback__), None)
  File "<string>", line 3, in raise_from
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/gin/config.py", line 1055, in gin_wrapper
    return fn(*new_args, **new_kwargs)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2107, in run
    mesh_devices=mesh_devices)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1418, in get_estimator
    save_checkpoints_secs=None)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/tpu/tpu_config.py", line 227, in __init__
    super(RunConfig, self).__init__(**kwargs)
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/run_config.py", line 553, in __init__
    compat_internal.path_to_str(model_dir))
  File "/Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow_estimator/python/estimator/run_config.py", line 958, in _get_model_dir
    raise ValueError('model_dir should be non-empty.')
ValueError: model_dir should be non-empty.
  In call to configurable 'run' (<function run at 0x1501dc830>)
```

**Comment by craffel** [comment]
There is a space between `--model_dir=` and `'/Users/vivekkaul/t5-small-model/small'` in your command.

**Comment by vkaul11** [comment]
Thanks for this it does work now but obviously it is too slow on CPU

**Comment by vkaul11** [comment]
Is it expected that even the small model won't be able to train for even 1000 steps? The terminal is stuck here "Done writing checkpoint." Should I try something else to debug on CPU?  I just wanted to see if things are running correctly

I```
NFO:tensorflow:Counters:
einsum: 2.54e+12
einsum_unique: 2.54e+12
output: 6.19e+08
 output/AddOperation: 1.85e+05
 output/Constant: 1
 output/EinsumOperation: 2.42e+08
 output/ImportOperation: 6.29e+06
 output/MinMaxOperation: 262
 output/ReduceOperation: 1.68e+05
 output/ReshapeOperation: 6.29e+06
 output/ScalarAddOperation: 6.05e+07
 output/ScalarMultiplyOperation: 5.38e+05
 output/SlicewiseOperation: 1.82e+08
 output/Variable: 6.07e+07
 output/WhileLoopOperation: 6.05e+07
output_unique: 6.19e+08
 output_unique/AddOperation: 1.85e+05
 output_unique/Constant: 1
 output_unique/EinsumOperation: 2.42e+08
 output_unique/ImportOperation: 6.29e+06
 output_unique/MinMaxOperation: 262
 output_unique/ReduceOperation: 1.68e+05
 output_unique/ReshapeOperation: 6.29e+06
 output_unique/ScalarAddOperation: 6.05e+07
 output_unique/ScalarMultiplyOperation: 5.38e+05
 output_unique/SlicewiseOperation: 1.82e+08
 output_unique/Variable: 6.07e+07
 output_unique/WhileLoopOperation: 6.05e+07
variables: 6.07e+07
 variables/trainable: 6.05e+07
 variables/untrainable: 1.85e+05
I0818 13:52:32.030119 4584648128 ops.py:5936] Counters:
einsum: 2.54e+12
einsum_unique: 2.54e+12
output: 6.19e+08
 output/AddOperation: 1.85e+05
 output/Constant: 1
 output/EinsumOperation: 2.42e+08
 output/ImportOperation: 6.29e+06
 output/MinMaxOperation: 262
 output/ReduceOperation: 1.68e+05
 output/ReshapeOperation: 6.29e+06
 output/ScalarAddOperation: 6.05e+07
 output/ScalarMultiplyOperation: 5.38e+05
 output/SlicewiseOperation: 1.82e+08
 output/Variable: 6.07e+07
 output/WhileLoopOperation: 6.05e+07
output_unique: 6.19e+08
 output_unique/AddOperation: 1.85e+05
 output_unique/Constant: 1
 output_unique/EinsumOperation: 2.42e+08
 output_unique/ImportOperation: 6.29e+06
 output_unique/MinMaxOperation: 262
 output_unique/ReduceOperation: 1.68e+05
 output_unique/ReshapeOperation: 6.29e+06
 output_unique/ScalarAddOperation: 6.05e+07
 output_unique/ScalarMultiplyOperation: 5.38e+05
 output_unique/SlicewiseOperation: 1.82e+08
 output_unique/Variable: 6.07e+07
 output_unique/WhileLoopOperation: 6.05e+07
variables: 6.07e+07
 variables/trainable: 6.05e+07
 variables/untrainable: 1.85e+05
INFO:tensorflow:Initializing variables from gs://t5-data/pretrained_models/small/model.ckpt-1000000:
I0818 13:52:33.332282 4584648128 utils.py:702] Initializing variables from gs://t5-data/pretrained_models/small/model.ckpt-1000000:
INFO:tensorflow:Variables in gs://t5-data/pretrained_models/small/model.ckpt-1000000 but not in graph:
I0818 13:52:33.332514 4584648128 utils.py:704] Variables in gs://t5-data/pretrained_models/small/model.ckpt-1000000 but not in graph:
INFO:tensorflow:
I0818 13:52:33.332602 4584648128 utils.py:705] 
INFO:tensorflow:Variables in graph but not in gs://t5-data/pretrained_models/small/model.ckpt-1000000:
I0818 13:52:33.332659 4584648128 utils.py:706] Variables in graph but not in gs://t5-data/pretrained_models/small/model.ckpt-1000000:
INFO:tensorflow:
I0818 13:52:33.332730 4584648128 utils.py:707] 
INFO:tensorflow:Create CheckpointSaverHook.
I0818 13:52:35.172133 4584648128 basic_session_run_hooks.py:546] Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
I0818 13:52:35.172496 4584648128 estimator.py:1171] Done calling model_fn.
INFO:tensorflow:Starting the session.
I0818 13:52:37.393392 4584648128 ops.py:5738] Starting the session.
INFO:tensorflow:Graph was finalized.
I0818 13:52:37.658127 4584648128 monitored_session.py:246] Graph was finalized.
2020-08-18 13:52:37.661613: I tensorflow/core/platform/cpu_feature_guard.cc:143] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2020-08-18 13:52:37.714548: I tensorflow/compiler/xla/service/service.cc:168] XLA service 0x7fa7a17d97e0 initialized for platform Host (this does not guarantee that XLA will be used). Devices:
2020-08-18 13:52:37.714568: I tensorflow/compiler/xla/service/service.cc:176]   StreamExecutor device (0): Host, Default Version
INFO:tensorflow:Restoring parameters from /Users/vivekkaul/t5-small-model/small/model.ckpt-1000000
I0818 13:52:37.719923 4584648128 saver.py:1293] Restoring parameters from /Users/vivekkaul/t5-small-model/small/model.ckpt-1000000
WARNING:tensorflow:From /Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1077: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
W0818 13:52:38.797224 4584648128 deprecation.py:323] From /Users/vivekkaul/.pyenv/versions/3.7.5/envs/t5_setup/lib/python3.7/site-packages/tensorflow/python/training/saver.py:1077: get_checkpoint_mtimes (from tensorflow.python.training.checkpoint_management) is deprecated and will be removed in a future version.
Instructions for updating:
Use standard file utilities to get mtimes.
INFO:tensorflow:Running local_init_op.
I0818 13:52:39.208189 4584648128 session_manager.py:505] Running local_init_op.
INFO:tensorflow:Done running local_init_op.
I0818 13:52:39.475201 4584648128 session_manager.py:508] Done running local_init_op.
INFO:tensorflow:Before copy master to slices.
I0818 13:52:39.868121 4584648128 ops.py:5767] Before copy master to slices.
INFO:tensorflow:Done with copy master to slices.
I0818 13:52:40.312647 4584648128 ops.py:5769] Done with copy master to slices.
INFO:tensorflow:Calling checkpoint listeners before saving checkpoint 1000000...
I0818 13:52:47.771290 4584648128 basic_session_run_hooks.py:614] Calling checkpoint listeners before saving checkpoint 1000000...
INFO:tensorflow:Before Save.
I0818 13:52:47.771566 4584648128 ops.py:5742] Before Save.
INFO:tensorflow:About to write a checkpoint
I0818 13:52:48.213192 4584648128 ops.py:5744] About to write a checkpoint
INFO:tensorflow:Saving checkpoints for 1000000 into /Users/vivekkaul/t5-small-model/small/model.ckpt.
I0818 13:52:48.213375 4584648128 basic_session_run_hooks.py:618] Saving checkpoints for 1000000 into /Users/vivekkaul/t5-small-model/small/model.ckpt.
INFO:tensorflow:Calling checkpoint listeners after saving checkpoint 1000000...
I0818 13:52:49.938513 4584648128 basic_session_run_hooks.py:626] Calling checkpoint listeners after saving checkpoint 1000000...
INFO:tensorflow:Done writing checkpoint.
I0818 13:52:49.938663 4584648128 ops.py:5747] Done writing checkpoint.
```
