### ISSUE TITLE
Data parallelism on TPU

### ISSUE THREAD

**Issue by arglog** [google-research/text-to-text-transfer-transformer#354]
Hi T5 authors,

I have some questions regarding the data parallelism on TPU.

1. On GPU, we are able to explicitly control the data and model parallelism via parameters like `"utils.run.mesh_shape = 'model:3,batch:2'"`. On TPU, we only have the explicit parameter for model parallelism (`"utils.tpu_mesh_shape.model_parallelism = 1"`) but not for data parallelism. So how does T5/mesh-tf derive the data parallelism factor? Is it implied by `utils.tpu_mesh_shape.tpu_topology`? 

2. If I saw the training speed is `1000 example/sec` (in the command line log or tensor board), does this mean the actual total number of samples per second? Or I need to multiply it by the factor of data parallelism or model parallelism, or both?

3. If I specified the batch size using `("tokens_per_batch", 2048)`, and let's assume there is 4-way data-parallelism, how does T5/mesh-tf distribute the data to each model replica?

Thanks!

**Comment by craffel** [comment]
1. With a TPU, you can either specify the `mesh_shape` directly to `run` or use the `tpu_mesh_shape` helper function https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/utils.py#L216. The docstring of that function answers your question.
1.
