### ISSUE TITLE
Choosing the right `Task` for repeating your NQ-open experiments 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#358]
I've been trying to reproduce your experiments on closed-book-QA in this repo:
https://github.com/google-research/google-research/tree/master/t5_closed_book_qa#released-model-checkpoints

Corresponding to this paper: "How Much Knowledge Can You Pack Into the Parameters of a Language Model?" https://arxiv.org/abs/2002.08910

WhenI look at the list of [the tasks included in the repo](https://github.com/google-research/google-research/blob/master/t5_closed_book_qa/t5_cbqa/tasks.py#L34-L126), I see these `Task` names: 
- `natural_questions_nocontext` and its test variant: `natural_questions_nocontext_test`
- `natural_questions_open` and its test variant: `natural_questions_open_test`
- `natural_questions_open_randanswer`

Which one(s) are the right tasks to fine-tune on, to reproduce your closed-bookQA results?

**Comment by adarob** [comment]
natural_questions_open_test
