### ISSUE TITLE
Speed of fine-tuning on closed-book-QA tasks 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#368]
I am following the script you have in [this repo](https://github.com/google-research/google-research/tree/master/t5_closed_book_qa#released-model-checkpoints) to fine-tune T5-11B on the NQ-open. 

**TLDR;** roughly speaking, how long does it take to fine-tune your models on NQ-open (say, using a v3-128 TPU)? 

----- 

The issue is that my fine-tuning is running quite slow on a v3-128 TPU. 
- The initial dump was made on 1100000 *two days ago*. 
- Currently I see checkpoint  for 1101100 step. 
- Assuming that it's gonna be trained for 10k steps, it would take ~20 days to fine-tune, which sounds quite long. 

For completeness: I am using the following script (which is literally the code you have in [your repo](https://github.com/google-research/google-research/tree/master/t5_closed_book_qa#usage)): 
```shell 
TASK=natural_questions_open
PRETRAINED_DIR=gs://t5-data/pretrained_models/cbqa/t5.1.1.xxl_ssm
PRETRAINED_STEPS=1100000
FINETUNE_STEPS=10000
MODEL_DIR="${BUCKET}/${TASK}/xxl_ssm"

# Run fine-tuning
python -m t5.models.mesh_transformer_main \
  --module_import="t5_cbqa.tasks" \
  --tpu="${TPU}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --gin_file="dataset.gin" \
  --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '8x8'" \
  --gin_param="MIXTURE_NAME = '${TASK}'" \
  --gin_param="utils.run.save_checkpoints_steps=1000" \
  --gin_param="utils.run.batch_size=('tokens_per_batch', 196608)" \
  --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS+FINETUNE_STEPS))" \
  --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
  --gin_param="utils.run.learning_rate_schedule=@learning_rate_schedules.constant_learning_rate" \
  --gin_param="constant_learning_rate.learning_rate=1e-3" \
  --t5_tfds_data_dir="${BUCKET}/t5-tfds"
```

This is much slower than my previous experiences with v3-8 TPUs (for other tasks), where fine-tuning for 10k  steps took just hours. 
I wonder this is caused because the model fails to appropriately *cache* the `natural_questions` datasets (included in `tfds`) and (since it's huge) downloading it many times, results in this slow-down.

**Comment by adarob** [comment]
That is definitely far too slow.  I'm not sure why it would be downloading NQ multiple times.  You can try running  tfds's `download_and_prepare` script to make sure it writes it stores it somewhere locally that you can reuse it.

Another option is to run cache_tasks_main to pre-cache the tokenized data: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/cache_tasks_main.py
