### ISSUE TITLE
Does 'reduce_concat_tokens' duplicate `pack_or_pad`?

### ISSUE THREAD

**Issue by arglog** [google-research/text-to-text-transfer-transformer#388]
I'm training a T5 model from scratch using the denoide objective. In the `denoise.gin` file, the preprocesssors are defined as
```python
preprocessors.unsupervised.preprocessors = [
@preprocessors.select_random_chunk,
@preprocessors.reduce_concat_tokens,
@preprocessors.split_tokens_to_inputs_length,
@preprocessors.denoise,
]
```

I have two questions about the `reduce_concat_tokens` function:

1. In the the `mesh_train_dataset_fn` function of T5 (see below), I found T5 also calls a function `pack_or_pad` ([Link](https://github.com/tensorflow/mesh/blob/55c48ee340463f947c94c4ed33c37053d8e488ad/mesh_tensorflow/transformer/dataset.py#L98)) from mesh_tensorflow.
https://github.com/google-research/text-to-text-transfer-transformer/blob/99ad0ec12ecb29cda6461d517f725ac2c844ebd9/t5/models/mesh_transformer.py#L76-L78
Do  `reduce_concat_tokens` and `pack_or_pad` (with `pack=True`) perform the same operations? If so, is it okay to skip either of them?

2. In the above code snippet of `mesh_train_dataset_fn`, I found that the `pack` parameter is always set to `True`. So does this mean T5 always performs the concatenation for the training dataset, even If I remove `@preprocessors.reduce_concat_tokens` from `preprocessors.unsupervised.preprocessors` in the `denoise.gin` file?

**Comment by craffel** [comment]
No, they do different things (and appear at different points in the pipeline). Please refer to the code for differences.
