### ISSUE TITLE
Use T5 for spanish text summarization

### ISSUE THREAD

**Issue by RoshanTanisha** [google-research/text-to-text-transfer-transformer#391]
Hello,

I am trying to do Spanish text summarization using Transformer based model, I would want to know if it is possible to do it for Spanish text or any other language using the T5 model as it is done for English texts?

**Comment by craffel** [comment]
Hi, we do not currently have a Spanish model but you could create a new vocabulary and pre-train your own Spanish-language T5 using our codebase.

**Comment by wilfoderek** [comment]
> Hi, we do not currently have a Spanish model but you could create a new vocabulary and pre-train your own Spanish-language T5 using our codebase.

Any examples of how to do that?
