### ISSUE TITLE
how to adjust beam_size in model.eval() function and get top 3 predictions

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#396]
When I look at the colab notebook (which I am following) I see that the evaluation is done here. Is the default eval using beam_search ? What is the default beam_size there?
```
model.batch_size = train_batch_size * 4
model.eval(
    mixture_or_task_name="trivia_all",
    checkpoint_steps="all"
)
```
On the github code page we have this command where we can specify the beam_search.gin but I don't know how to pass it using model.eval() function. Also can we change the beam_size parameter also ?
```
t5_mesh_transformer \
  --tpu="${TPU_NAME}" \
  --gcp_project="${PROJECT}" \
  --tpu_zone="${ZONE}" \
  --model_dir="${MODEL_DIR}" \
  --gin_file="${MODEL_DIR}/operative_config.gin" \
  --t5_tfds_data_dir=${DATA_DIR} \
  --gin_file="eval.gin" \
  --gin_file="beam_search.gin" \
  --gin_param="run.dataset_split = 'validation'" \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '${TPU_SIZE}'" \
  --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'" \
  --gin_param="eval_checkpoint_step = 'all'"
```
I also wanted to get the top 3 decoding results from beam search. How can we do that ?

**Comment by craffel** [comment]
>  Is the default eval using beam_search ?

No, the default is just to sample autoregressively without beam search.

> On the github code page we have this command where we can specify the beam_search.gin but I don't know how to pass it using model.eval() function.

You can manually pass extra gin bindings when you construct the model:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/mtf_model.py#L96
You should pass the same bindings that appear in the [beam_search.gin file](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/gin/beam_search.gin). Note that the extra gin bindings argument may not be in the latest stable version on PIP yet so you may need to install from source to get this feature.

> Also can we change the beam_size parameter also ?

Yes, just modify the binding you pass in for `Bitransformer.decode.beam_size = 4`.

> I also wanted to get the top 3 decoding results from beam search. How can we do that ?

This is not supported.

**Comment by vkaul11** [comment]
Thanks Colin. Just a question about the sample autoregressive setting. The results seem to be good and stable (non-random). Does it almost default to greedy decoding with temperature -> 0 ? Or is top k sampling or top p nucleus sampling ? Can you point to the code that does that? Thanks again.

**Comment by craffel** [comment]
> Does it almost default to greedy decoding with temperature -> 0 ? 

Yes, you're exactly right. Here is the decode function: https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/transformer.py#L1506 it will use the default kwarg values unless otherwise specified via gin. Default is beam_size = 1 (aka autoregressive sampling, no beam search) with temperature = 0 (aka greedy).
