### ISSUE TITLE
adding new features into encoder for certain tasks 

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#397]
In many cases there are certain features that the model can use to enhance the performance of the decoder. For instance, we can use the users location, local time etc to improve accuracy for results.
Generally in earlier setups like BERT what was done was to concatenate the additional features to the BERT features but in t5 I suppose we can directly add the features as part of the Input
```
Input: Question: Will the Mcdonalds near me be open in 1 hour? Location: New York, USA Local Time : 18:50 hours 
Target: Yes
```
Is it better to add features directly in the Input of the Encoder or we should still try to concatenate the embeddings with other features. Is it easy to append features like this to the encoder embedding ?

**Comment by craffel** [comment]
Yes, you should just append all information/features together in the input (probably in the text preprocessor). See e.g. the SQuAD text preprocessor https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L297
