### ISSUE TITLE
Incorrect Output on custom dataset trained model

### ISSUE THREAD

**Issue by Vaibhav-nn** [google-research/text-to-text-transfer-transformer#409]
I trained T5 small model on 10k rows of a dataset with each sentences added with the **'Review'**  prefix  and **'Result'** prefix with the target column. The trained model looks confused since it throws output with with any random prefixes and sometimes the output is in German or Spanish though the dataset is entirely in English.

**Comment by craffel** [comment]
How long did you fine-tune for? You may just need further fine-tuning. I would also suggest trying Base, Small is not terribly reliable.
