### ISSUE TITLE
Measuring the correct time of training or finetuning

### ISSUE THREAD

**Issue by working12** [google-research/text-to-text-transfer-transformer#410]
I am running the training like this 
```python -m t5.models.mesh_transformer_main ....... [other options]```. Is there any way I can check how much time did it take to train the model? 

What are the possible ways of measuring the time?

**Comment by craffel** [comment]
Hi, if you did not time the command itself, you can look at the time of the first and last logged events in Tensorboard.

**Comment by working12** [comment]
@craffel Hello. Thanks.  Sorry but can you say where I can find these logs of tensorboard? Pretty new using all these.

**Comment by craffel** [comment]
In the model directory you specified when invoking `python -m t5.models.mesh_transformer_main`. You can start up a tensorboard server with `tensorboard --logdir your_model_dir`

**Comment by working12** [comment]
@craffel  I will try to work this out. In case I get stuck I will ask again. Thx.

**Comment by working12** [comment]
@craffel  If I am not wrong, I need to run tensorboard before I run the training command in a separate terminal right?

**Comment by craffel** [comment]
The events files are saved over the course of training whether you are running tensorboard or not. You can run tensorboard after the fact to parse and visualize the events files.

**Comment by mainakmanna** [comment]
@craffel Where exactly one can notice these events? I have started tensorboard in the designated directory and it is showing the scalar evaluation graphs as per the metric defined under the "custom scalar" tab.

**Comment by craffel** [comment]
I'm not sure I understand your question - it sounds like you can see the graphs? If you look at the date/time of leftmost point on the graph, that is the start time; the rightmost point has the end time.

**Comment by mainakmanna** [comment]
> I'm not sure I understand your question - it sounds like you can see the graphs? If you look at the date/time of leftmost point on the graph, that is the start time; the rightmost point has the end time.

Yes, I can see the graph. And this is the process you have been mentioning. I was expecting something in the line of "there is a tab where you can see the relevant logs in summarized form."  Now I understand. Thanks for clarifying. @craffel
