### ISSUE TITLE
finetuning does not save enough checkpoints when I switch to "large" and "11B" model

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#413]
I see when I use fine-tuning and use "small" and "base" model I do get the checkpoints saved every 1000 steps but when I go to larger "models" lesser number of checkpoints are saved. Is this by design ?

For example:
```
TPU_ADDRESS="tpu-1"
MODEL_SIZE = "11B" #@param["small", "base", "large", "3B", "11B"]
# Public GCS path for T5 pre-trained model checkpoints
BASE_PRETRAINED_DIR = "gs://vivek_kaul/model"
PRETRAINED_DIR = os.path.join(BASE_PRETRAINED_DIR, MODEL_SIZE)
MODEL_DIR = os.path.join(MODELS_DIR, MODEL_SIZE)

# Limit number of checkpoints to fit within 5GB (if possible).
model_parallelism, train_batch_size, keep_checkpoint_max = {
    "small": (1, 256, 16),
    "base": (2, 128, 8),
    "large": (8, 64, 4),
    "3B": (8, 16, 1),
    "11B": (8, 16, 1)}[MODEL_SIZE]

print(MODEL_DIR)
tf.io.gfile.makedirs(MODEL_DIR)
# The models from our paper are based on the Mesh Tensorflow Transformer.
model = t5.models.MtfModel(
    model_dir=MODEL_DIR,
    tpu=TPU_ADDRESS,
    tpu_topology=TPU_TOPOLOGY,
    gcp_project="vivek_kaul",
    tpu_zone="us-east1-d",
    model_parallelism=model_parallelism,
    batch_size=train_batch_size,
    sequence_length={"inputs": input_sequence_length, "targets": output_sequence_length},
    learning_rate_schedule=0.003,
    save_checkpoints_steps=1000,
    keep_checkpoint_max=keep_checkpoint_max,
    iterations_per_loop=100,
   # extra_gin_bindings=["Bitransformer.decode.beam_size = 4","Bitransformer.decode.alpha = 0.6"]
)
FINETUNE = 5000
model.finetune(
    mixture_or_task_name=task_name,
    pretrained_model_dir=PRETRAINED_DIR,
    finetune_steps=FINETUNE,
)

```
When I use the "small" and "base" then we keep more checkpoints I see checkpoints saved corresponding to fine-tuned steps 1000,2000,3000,4000,5000. With "large" I have only 4000 and 5000 and with 11B only 5000. When I looked at the google drive for 11B I saw that while training it does save the checkpoints every 1000 steps but then it deletes the previous checkpoint as soon as it reaches the next 1000 steps. For example it saves 3000 steps checkpoint but then when it reached 4000 steps then it erases the checkpoint for 3000 steps and keeps then one for 4000 steps only. Bigger the model, less checkpoint it preserves. Is it because of memory reasons ? I also tried to  fine-tune "base" model for 10,000 steps and then it preserved checkpoints 5000,6000,7000,8000,9000, 10000 and erased the 1000,2000,3000 and 4000 checkpoint. Is there a way for us to control the deletion of the checkpoints?

**Comment by craffel** [comment]
Hi, the code you posted specifies keep_checkpoint_max = 1 for the 11B model.
```
model_parallelism, train_batch_size, keep_checkpoint_max = {
    "small": (1, 256, 16),
    "base": (2, 128, 8),
    "large": (8, 64, 4),
    "3B": (8, 16, 1),
    "11B": (8, 16, 1)
```
 Raise this value if you want more checkpoints to be retained. You can also just override the value being specified in the construction in `MtfModel` (`keep_checkpoint_max=keep_checkpoint_max`)
