### ISSUE TITLE
Configurable 'utils.run' doesn't have a parameter named 'mesh_devices'.

### ISSUE THREAD

**Issue by V-Enzo** [google-research/text-to-text-transfer-transformer#42]
Hi, I am trying to run the t5 on my own server with single gpu with your command 
t5_mesh_transformer    --model_dir="${MODEL_DIR}"   --t5_tfds_data_dir="${DATA_DIR}"   --gin_file="dataset.gin"   --gin_param="utils.run.mesh_shape = 'model:1,batch:1'"   --gin_param="utils.run.mesh_devices = ['gpu:0']"   --gin_param="MIXTURE_NAME = 'glue_mrpc_v002'"   --gin_file="./text-to-text-transfer-transformer/operative_config.gin"
(the operative_config.gin has been downloaded by gsutil)
but it gave an value error

ValueError: Configurable 'utils.run' doesn't have a parameter named 'mesh_devices'.
  In bindings string line 2
    utils.run.mesh_devices = ['gpu:0']

Do you know the possible reason and could you offer me a solution? Thank you!

**Comment by adarob** [comment]
You may need to update mesh-tensorflow.

**Comment by adarob** [comment]
You need `mesh-tensorflow>=0.1.9`.

**Comment by V-Enzo** [comment]
Thank you! I upgraded mesh-tensorflow and it worked!
