### ISSUE TITLE
Running hf_model.py 

### ISSUE THREAD

**Issue by danyaljj** [google-research/text-to-text-transfer-transformer#457]
I am trying to run your models with [`hf_model`](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py). The current blocker issue is that the code is using `num_parallel_calls` in  [in multiple places](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py#L128), however, this function seems to be [deprecated](https://github.com/google-research/text-to-text-transfer-transformer/blob/838157d433995473e96b773c9c761b6aadf01e37/t5/data/preprocessors.py#L2651).

Wondering if there is a replacement for this function I can use as a quick fix.

**Comment by craffel** [comment]
Ah, they should all be set to `tf.data.experimental.AUTOTUNE`. I will fix this. Thanks for the heads up.

**Comment by danyaljj** [comment]
Thanks @craffel! 

Now that we're on this thread: 
Might be helpful to mention that the model specified by [`model_dir`](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py#L177) is a Pytorch mode, not a TF model (just in case there is any confusion). 

Even better, if you provide an example script for converting TF models to PyTorch ones: 
```python
from transformers import T5Config, T5Tokenizer, T5ForConditionalGeneration
from transformers.modeling_t5 import load_tf_weights_in_t5

base_model = "t5-small"
tokenizer = T5Tokenizer.from_pretrained(base_model)
model = T5ForConditionalGeneration(T5Config.from_pretrained(base_model))
tf_model_path = ... 
load_tf_weights_in_t5(model, None, path)
model.save_pretrained(path + "pytorch_model/")
tokenizer.save_pretrained(path + "pytorch_model/")
```

**Comment by juliahane** [comment]
Hi this issue is not yet fixed when one install your repo with pip, could you please have a look? thanks

**Comment by craffel** [comment]
@danyaljj PRs welcome :)

**Comment by craffel** [comment]
@juliahane This has not made it into the pip release yet, you need to install the current code from GitHub. You can do this with pip via pip install git+https://github.com/google-research/text-to-text-transfer-transformer.git
