### ISSUE TITLE
how to run the pytorch model text-to-text-transfer-transformer/t5/models/hf_model.py

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#475]
Hi
I need to run this model text-to-text-transfer-transformer/t5/models/hf_model.py
could you please tell me how to run it on a sample mixture of datasets?
thanks for your help

**Comment by craffel** [comment]
Hi there, there is a usage example at the top of the file:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py#L27
