### ISSUE TITLE
issue with T5 data downloading

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#483]
Hi
I am trying to run the model on the cloud. I made a T5 mixture task with some existing datasets in tfds, but the model is not able to download them automatically. Here is what I do for task creation as example, am I missing an step? 

```
import t5.data
tasks = ['wmt14_translate', 'wmt14_translate']
t5.data.MixtureRegistry.remove("wmt")
t5.data.MixtureRegistry.add('wmt', tasks, default_rate=1) 
```

thanks for your help.

**Comment by adarob** [comment]
what error are you seeing?
