### ISSUE TITLE
providing the example for two tfds tasks

### ISSUE THREAD

**Issue by cameronalonso2** [google-research/text-to-text-transfer-transformer#486]
Hi
could you provide an example how to join two tfds tasks to form T5 datasets?
thanks

**Comment by craffel** [comment]
You can just use a `Mixture` like this: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/mixtures.py#L194
If you want it to work like you have just concatenated the two datasets, you should set `default_rate=t5.data.rate_num_examples`.
