### ISSUE TITLE
please add more examples on how to form T5 datasets 

### ISSUE THREAD

**Issue by cameronalonso2** [google-research/text-to-text-transfer-transformer#487]
maybe some translation, and question answering could be helpful

**Comment by cameronalonso2** [comment]
for instance if there is question + passage, answer how the task should be formed?

**Comment by craffel** [comment]
There are many examples of QA and translation tasks/preprocessors in the codebase. e.g.
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L280
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L242
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L59
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L144
