### ISSUE TITLE
making the codes generalizable to use other encoders as well 

### ISSUE THREAD

**Issue by rabeehk** [google-research/text-to-text-transfer-transformer#493]
Hi, 
Looking into t5/data/dataset_providers.py [1] line 618, you append a predefined tokenizer, to the list of task preprocessor, and then this is applied by default. I would like to change the tokenizer, could you assist in modifying the codes in a way allowing the users to use any tokenizer? thanks

**Comment by craffel** [comment]
Hi Rabeeh, you can use any tokenizer and we currently support SentiecePiece and byte-level tokenization (see https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/vocabularies.py and https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/sentencepiece_vocabulary.py). The old `Task` class requires tokenization to happen during pre-processing (via any Vocabulary class including a user-defined one) but the new `Taskv3` class does not require tokenization to happen during pre-processing.
