### ISSUE TITLE
Making "copy_plaintext=True" a parameter for get_mixture_or_task function 

### ISSUE THREAD

**Issue by rabeehk** [google-research/text-to-text-transfer-transformer#494]
Hi,
I need to return the original input text from a constructed mixture, currently "copy_plaintext=True" is only a parameter for getting a dataset, not the mixture, could you assist in making "copy_plaintext=True" a parameter for get_mixture_or_task function to allow users have the original text when reading mixtures. 
thanks.

**Comment by craffel** [comment]
Hi Rabeeh, the `get_dataset` function of `Mixture` does have a `copy_plaintext` argument:
https://github.com/google-research/text-to-text-transfer-transformer/blob/da03f71310330bfaf14a1f6072c1e62b563ec91d/t5/data/dataset_providers.py#L1030
`get_mixture_or_task` returns a `Task` or `Mixture` object that you can then call `get_dataset` on with `copy_plaintext=True`.

**Comment by adarob** [comment]
@rabeehk can you provide more details on your use case? There are a few complications with getting plaintext via mixture depending on what token preprocessors you use.

**Comment by rabeehkarimimahabadi** [comment]
Hi Adam,
thanks for reopening it, when you call task = t5.data.get_mixture_or_task(mixture_or_task_name) in the HF model, this is not possible to get the original tasks, but I am currently rewriting your whole data pipeline in PyTorch to allow distributed training, so we can consider it closed for now. thanks.
