### ISSUE TITLE
Error while training a T5 model

### ISSUE THREAD

**Issue by genderbias** [google-research/text-to-text-transfer-transformer#498]
Hello,

When I try to train the T5, I get the following error. I replaced the tpu model, bucket address and other parameters, it runs for few seconds but suddenly stops here. do you have any idea?:

`
INFO:tensorflow:auto_logical_to_physical_tpu logical_shape=[128] physical_shape=[2, 2, 2] I1102 21:45:42.147541 140059250689856 simd_mesh_impl.py:860] auto_logical_to_physical_tpu logical_shape=[128] physical_shape=[2, 2, 2] INFO:tensorflow:training_loop marked as finished I1102 21:45:42.147930 140059250689856 error_handling.py:115] training_loop marked as finished WARNING:tensorflow:Reraising captured error W1102 21:45:42.148096 140059250689856 error_handling.py:149] Reraising captured error Traceback (most recent call last): File "/home/ngr_arabzadeh/.local/bin/t5_mesh_transformer", line 8, in <module> sys.exit(console_entry_point()) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 261, in console_entry_point app.run(main) File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 300, in run _run_main(main, args) File "/usr/local/lib/python3.7/dist-packages/absl/app.py", line 251, in _run_main sys.exit(main(argv)) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/t5/models/mesh_transformer_main.py", line 255, in main model_dir=FLAGS.model_dir) File "/usr/local/lib/python3.7/dist-packages/gin/config.py", line 1078, in gin_wrapper utils.augment_exception_message_and_reraise(e, err_str) File "/usr/local/lib/python3.7/dist-packages/gin/utils.py", line 49, in augment_exception_message_and_reraise six.raise_from(proxy.with_traceback(exception.__traceback__), None) File "<string>", line 3, in raise_from File "/usr/local/lib/python3.7/dist-packages/gin/config.py", line 1055, in gin_wrapper return fn(*new_args, **new_kwargs) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 2302, in run skip_seen_data=skip_seen_data) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 1615, in train_model estimator.train(input_fn=input_fn, max_steps=train_steps) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3089, in train rendezvous.raise_errors() File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/error_handling.py", line 150, in raise_errors six.reraise(typ, value, traceback) File "/usr/local/lib/python3.7/dist-packages/six.py", line 703, in reraise raise value File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3084, in train saving_listeners=saving_listeners) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 349, in train loss = self._train_model(input_fn, hooks, saving_listeners) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1175, in _train_model return self._train_model_default(input_fn, hooks, saving_listeners) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1204, in _train_model_default self.config) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2921, in _call_model_fn config) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/estimator.py", line 1163, in _call_model_fn model_fn_results = self._model_fn(features=features, **kwargs) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3212, in _model_fn _train_on_tpu_system(ctx, model_fn_wrapper, dequeue_fn)) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3654, in _train_on_tpu_system device_assignment=ctx.device_assignment) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/tpu/tpu.py", line 1665, in split_compile_and_shard name=name) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/tpu/tpu.py", line 1380, in split_compile_and_replicate outputs = computation(*computation_inputs) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3640, in multi_tpu_train_steps_on_single_shard inputs=[0, _INITIAL_LOSS]) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/tpu/training_loop.py", line 178, in while_loop condition_wrapper, body_wrapper, inputs, name="", parallel_iterations=1) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2774, in while_loop return_same_structure) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2256, in BuildLoop pred, body, original_loop_vars, loop_vars, shape_invariants) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/ops/control_flow_ops.py", line 2181, in _BuildLoop body_result = body(*packed_vars_for_body) File "/usr/local/lib/python3.7/dist-packages/tensorflow/python/tpu/training_loop.py", line 121, in body_wrapper outputs = body(*(inputs + dequeue_ops)) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 3639, in <lambda> lambda i, loss: [i + 1, single_tpu_train_step(i)], File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 1753, in train_step self._call_model_fn(features, labels)) File "/usr/local/lib/python3.7/dist-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py", line 2031, in _call_model_fn estimator_spec = self._model_fn(features=features, **kwargs) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/mesh_tensorflow/transformer/utils.py", line 388, in my_model_fn mesh_shape.to_integer_list, physical_shape) File "/home/ngr_arabzadeh/.local/lib/python3.7/site-packages/mesh_tensorflow/simd_mesh_impl.py", line 864, in auto_logical_to_physical_tpu "physical_shape=%s logical_shape=%s" % (physical_shape, logical_shape)) ValueError: physical and logical shapes must have the same product physical_shape=[2, 2, 2] logical_shape=[128] In call to configurable 'run' (<function run at 0x7f61d15b70d0>)`

**Comment by adarob** [comment]
It's tough to say without more details, but it looks like you may no be setting the tpu_topology correctly. What size TPU are you using and what is your launch command?

**Comment by craffel** [comment]
You are trying to run a model with a large amount of model parallelism on a v3-8 or v2-8 device. Try setting --model_parallelism=1.

**Comment by adarob** [comment]
Closing this out since there has been no response. Please open a new issue if @craffel's suggestion didn't work.
