### ISSUE TITLE
model.eval vs model.predict

### ISSUE THREAD

**Issue by bhavanadalvi** [google-research/text-to-text-transfer-transformer#515]
Can someone please explain the difference between model.eval and model.predict functionalities?
Same T5 model gives much better predictions when I use model.eval instead of model.predict.
In terms of accuracy on an end task I get a performance difference of around 20%, which is huge.
I tried changing temperature and beam_size parameters but couldn't improve model.predict's performance to match that of eval.

**Comment by craffel** [comment]
Do you mean you use model.predict, take the predictions, and then feed them into a metric to get the accuracy or whatever? What task is it for? When you use predict and separately feed the predictions into the metric, you are skipping any postprocessing that the task does before computing the metric. For example, for question-answering, it's standard to lowercase the predictions before eval'ing them.

**Comment by bhavanadalvi** [comment]
For both model.eval and model.predict, I am only using the actual predictions file generated by T5. I have a separate metric computation code that already accounts for lowercasing etc. So that part is same for both.
What I see is: predictions themselves are significantly different across these two, with "eval" they are better than "predict".
My task is "fact generation" so there are a couple of sentences in the target output.

**Comment by craffel** [comment]
Where are you getting the inputs for predict?

**Comment by enzoveltri** [comment]
Actually, I've noticed the same behaviour.
I've called eval() and predict() on the same inputs.
The differences are also in the input_files that it generates to make predictions:
- in the `eval()` the inputs are in the format:
   `b'string'`
   `b'string'`
    `...`
    `b'string'`
- in the `predict()` the inputs are in the format:
   `string`
   `string`
    `...`
    `string`

**Comment by enzoveltri** [comment]
I think the different results come from the `_sequence_length`. In the `eval()` if not specified, it computes the best `_sequence_length` that could be different from the `model._sequence_length` one used in the predict().

In my case changing `model._sequence_length` with the same sizes as the one calculated in the `eval()` solved the problem
