### ISSUE TITLE
Feature Extraction for T5 Models

### ISSUE THREAD

**Issue by agemagician** [google-research/text-to-text-transfer-transformer#522]
Hello,

We have trained several models using recent T5 release from small models to the 11B models for protein sequences tasks and source code tasks.

We tried to port it to Huggingface library for feature extraction, but due to the changes in mesh tensorflow and T5 library, the porting failed.

My question is:
What is the the easiest way to extract the encoder and decoder final features using T5 library ?
For example, can we modify for example "t5-deploy.ipynb" to make it extract features ?

@craffel  @adarob any ideas ?

**Comment by craffel** [comment]
This is not possible without modifying the mesh tensorflow transformer implementation itself.
