### ISSUE TITLE
Multiple input files as input

### ISSUE THREAD

**Issue by working12** [google-research/text-to-text-transfer-transformer#529]
In the example notebook ([link](https://github.com/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb)) there is one single train file and one validation file.
```
NQ_SPLIT_FNAMES = {
    "train": "simplified-nq-train.jsonl.gz",
    "validation": "nq-dev-all.jsonl.gz"
}
```
Suppose, to a task, I need to pass several train files and validation files, then what is the best way of doing that in this context using T5? (Dataset is split across multiple training files).

**Comment by craffel** [comment]
You can use a glob-like filepattern with the `TextLineDataSource` https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/dataset_providers.py#L379
