### ISSUE TITLE
Error when installing on Computer Canada

### ISSUE THREAD

**Issue by HangCui0510** [google-research/text-to-text-transfer-transformer#530]
I got the following error when trying to install on Compute Canada. Is there any way i can solve this?
<img width="1673" alt="Screen Shot 2020-11-16 at 12 27 46 AM" src="https://user-images.githubusercontent.com/64120158/99216002-8edd8700-27a2-11eb-8be2-76b25f548c5a.png">

**Comment by craffel** [comment]
This looks like an error where a downstream library (`cffi`) can't find a required shared library. It's out-of-scope for the kind of support we can offer, sorry. Maybe check with your system administrators.
