### ISSUE TITLE
Multi-label Classification approach

### ISSUE THREAD

**Issue by mainakmanna** [google-research/text-to-text-transfer-transformer#535]
In the case of multi-label classification, what should be the correct way of training given a situation like this:-

We have a text document and associated with that 3,4,5 or 6 numbers (which denote the document class it belongs to). An example would be:
```

"Line 0. Here is the document. Line. Line...end of the document."  --> 123 784 23 555 456
"Document 2. Line 0. Here is the document. Line. Line...end of the document."  --> 33 856 32 55 999 433

```
(as you can see the number of labels is different in both cases. 5 in the first document and 6 in the second document)
Now if we want to train T5 for these tasks what would be the correct way of doing that?

I am actually curious about these steps in general:

1. Should we convert the target labels using SPM? 
2. What metric can we use in the context of T5? 
3. Specifically how to get the validation score? (Should we use postprocess_fn to convert the string output?)

**Comment by craffel** [comment]
I would suggest not using label IDs and instead use the text corresponding to the meaning of each label. I'd also suggest keeping the order of the labels consistent across the different examples. And yes, you should write a postprocessor function and metric function that satisfies your use-case.

**Comment by mainakmanna** [comment]
> I would suggest not using label IDs and instead use the text corresponding to the meaning of each label. I'd also suggest keeping the order of the labels consistent across the different examples. And yes, you should write a postprocessor function and metric function that satisfies your use-case.

Actually I didn’t have to preprocess anything, the labels were already given in Id form. Maybe I will change them (if possible) to their original meaningful labels rather than numbers. About the metric function I am wondering how the model would predict same number of target labels as given in a sample. For example, if model guesses 4 classes and actually there are 5, how to cope that? 

Also by order do you mean I should always maintain some order (maybe alphabetical or some thing like that?)

**Comment by craffel** [comment]
> if model guesses 4 classes and actually there are 5, how to cope that?

It's up to you how to define a metric relevant to your task. An F1 score seems appropriate.

> Also by order do you mean I should always maintain some order (maybe alphabetical or some thing like that?)

Yes.

**Comment by mainakmanna** [comment]
I was checking the process of creating the postprocessor function. I don't clearly understand the inputs of such a function. If I write a custom one, what would be in the input? (Because these will be passed to me, so it would be great to know this clearly).

I have noticed this part 
```
Note: postprocessors must either accept an `example` and `is_target` kwargs
or include `**unused_kwargs` in their signature. The `example` will be the
full example.
These functions should assume input strings to be unicode, but that strings
in the `example` dict will be in bytes.
```
But still it is not clear how the inputs are worked upon here.

**Comment by munish0838** [comment]
Hi @mmcs-work, I am trying to  train t5 for multilabel classification, can you share your method of labelling if possible
