### ISSUE TITLE
C4 dataset doesn't provide summarized texts 

### ISSUE THREAD

**Issue by minhtam2048** [google-research/text-to-text-transfer-transformer#536]
I read the T5's document and It was well explained. But one thing that bothering me is the link to C4 dataset which is provided in the document doesn't have the summarized data for training process. As far as I know, the training process requires the original and the summarized texts. Can someone point out what I'm missing or how can I obtain the summarized data for training ?
Many thanks.

**Comment by craffel** [comment]
Hi, C4 is not a summarization dataset, it's just a large unstructured text corpus that we apply self-supervised objectives to. Converting raw C4 data into a format used for training is done by the preprocessors in this library, see e.g. https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/preprocessors.py#L1886
