### ISSUE TITLE
T5 fp16 training

### ISSUE THREAD

**Issue by shenfe** [google-research/text-to-text-transfer-transformer#539]
We tried finetuning T5 upon a downstream task, in AMP mode (O1 or O2), but found some hidden outputs became overflowing to inf and nan.

Similar problem https://github.com/huggingface/transformers/issues/4586 .

I doubt whether the T5 model architecture tends to produce parameter values beyond fp16 boundary. Or anyone especially the official has ever done any experiment on T5 fp16? Welcome some advice or experience :)

**Comment by craffel** [comment]
All of our experiments use bfloat16 activations.

**Comment by shenfe** [comment]
> All of our experiments use bfloat16 activations.

Thank you, and all right. The bfloat16 is the reason. So it's understandable that fp16 training did not work.
