### ISSUE TITLE
Running distributed training on multiple GPU nodes getting stuck 

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#540]
Hi, I created a new task pre-training on reddit corpus, and I am looking at using multiple GPU nodes for training my T5. As mentioned in [distributed TF](https://www.tensorflow.org/guide/distributed_training#TF_CONFIG), I set my TF config for each node as follows 

```
export TF_CONFIG='{"cluster": { "chief": ["node0:port0"], "worker": ["node1:port1"]}, "task": {"type": "chief", "index": 0}}'
``` 
and 
```
export TF_CONFIG='{"cluster": { "chief": ["node0:port0"], "worker": ["node1:port1"]}, "task": {"type": "worker", "index": 0}}'
``` 

And the command I use for pretraining is as follows, 

```
python -m t5.models.mesh_transformer_main \
    --module_import="reddit_corpus" \
    --model_dir=model/ \
    --gin_file="dataset.gin"  \
    --gin_file="models/bi_v1_l6.gin" \
    --gin_param="utils.run.train_steps = 100000" \
    --gin_param="utils.run.save_checkpoints_steps = 5000" \
    --gin_param="utils.run.batch_size = 64" \
    --gin_file="learning_rate_schedules/rsqrt_no_ramp_down.gin"  \
    --gin_file="objectives/span.gin" \
    --gin_param="MIXTURE_NAME = 'reddit_masked_language_modeling'" \
    --gin_param="utils.run.mesh_shape = 'model:2,batch:1'" \
```

However, my training is stuck for hours on just the following 
```
INFO:tensorflow:Create CheckpointSaverHook.
I1123 06:56:44.131780 139999962376000 basic_session_run_hooks.py:546] Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
I1123 06:56:44.132405 139999962376000 estimator.py:1164] Done calling model_fn.
INFO:tensorflow:Starting the session.
I1123 06:56:47.724841 139999962376000 ops.py:5746] Starting the session.
INFO:tensorflow:Graph was finalized.
I1123 06:56:48.036149 139999962376000 monitored_session.py:246] Graph was finalized.
```
and for worker node 
```
INFO:tensorflow:Create CheckpointSaverHook.
I1123 06:56:48.245734 139772280100672 basic_session_run_hooks.py:546] Create CheckpointSaverHook.
INFO:tensorflow:Done calling model_fn.
I1123 06:56:48.246445 139772280100672 estimator.py:1164] Done calling model_fn.
INFO:tensorflow:Graph was finalized.
I1123 06:56:51.740572 139772280100672 monitored_session.py:246] Graph was finalized.
```

What am I missing or doing incorrectly here?

**Comment by craffel** [comment]
Hi, with mesh tensorflow you need to specify a layout (how to assign different model dimensions to different devices), see e.g. https://github.com/google-research/text-to-text-transfer-transformer#gpu-usage
I'm not sure if this supports distributed TF at all; it's not something we've tried or support. Maybe @nshazeer can comment on whether mesh tensorflow can be made to work with distributed TF.

**Comment by dpanshu** [comment]
@nshazeer mentioned in here https://github.com/tensorflow/mesh/issues/80 that if we can construct the GPU graph than it would be doable. Are there any pointers on how to do this on AWS

**Comment by gbxu** [comment]
I'm expecting this feature too. As mentioned in this [paper](https://arxiv.org/pdf/1811.02084.pdf), it will be supported in GPU clusters. Well, maybe the "future" is not coming.

**Comment by dkajtoch** [comment]
so is it possible to train the model on a cluster of gpus at all? or this only works for a single machine and tpu pod?

**Comment by craffel** [comment]
This is an issue for mesh tensorflow - feel free to take it up there.
