### ISSUE TITLE
export_beam_size option is not working.

### ISSUE THREAD

**Issue by jayendra13** [google-research/text-to-text-transfer-transformer#555]
I am trying to export the `t5-small` model with `export_beam_size=5` but the exported model always gives the single output.

Here is the colab to reproduce the issue.
https://colab.research.google.com/drive/1eu4O7jeV_1lLfVp5zFvnFiU_9GbXlTs1?resourcekey=0-28MU8r1JMvm80IrODHdCdQ&usp=sharing

**Comment by craffel** [comment]
The beam size specifies how many candidates are considered during beam search. It will always return the most likely beam, and will never return more than one sequence.

**Comment by jayendra13** [comment]
Ok got it, is there any way to get the output from all the beams, with the API(i.e. without modifying the code?).

**Comment by craffel** [comment]
No, sorry.
