### ISSUE TITLE
Update custom tokenizer instruction

### ISSUE THREAD

**Issue by nkruglikov** [google-research/text-to-text-transfer-transformer#566]
Hi,

I was trying to train a new SentencePiece tokenizer for T5. According to README, in order for tokenizer to be compatible with your code, it should be trained with flags `--pad_id=0 --eos_id=1 --unk_id=2`. However, it causes an obscure error when applied to actual SentencePiece. After some digging around, I discovered that you should also add option `--bos_id=-1`, and found a confirmation that it was the case for original T5: https://github.com/google-research/text-to-text-transfer-transformer/issues/270#issuecomment-646793421

Could you please update the instruction?

**Comment by craffel** [comment]
What instruction/readme are you referring to?

**Comment by nkruglikov** [comment]
The main README of this repo. Quote:
> The SentencePiece model is used to tokenize the input strings and decode the output tokens. You can create your own model with the google/sentencepiece library, or use our default one at t5.data.DEFAULT_SPM_PATH. If you create your own, you must use the flags --pad_id=0 --eos_id=1 --unk_id=2 with spm_train to be compatible with our model code.
