### ISSUE TITLE
Running pre-training on a large text with multiple files on gs://path/to/dataset

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#574]
Hi, 

I have a large set of text present in google cloud which is around 100B tokens stored in 10,000 files as `gs://path/file.00001.txt` etc. It is not possible to download all the files locally on the TPU. How can I go about pre-training a model from scratch for such a dataset? 

What should be dataset function look like? and do I need to make any changes to the training command that I can use for a wikipedia task as given below 

```
t5_mesh_transformer  \
  --model_dir=gs://model/ \
  --gin_file="dataset.gin" \
  --gin_param="MIXTURE_NAME = 'wikipedia_20190301.en_v003_unsupervised'" \
  --gin_file="models/bi_v1.gin" \
  --gin_param="utils.run.train_steps =  524288" \
  --gin_param="utils.run.save_checkpoints_steps = 10000" \
  --gin_param="utils.run.batch_size = (\"tokens_per_batch\", 65536)"  \
  --gin_file="learning_rate_schedules/rsqrt_no_ramp_down.gin" \
  --gin_file="objectives/span_3_15_u_u.gin" \
  --tpu=$TPU_ADDRESS \
  --gin_param="utils.tpu_mesh_shape.tpu_topology = '${TPU_TOPOLOGY}'"\
  --gin_param="utils.tpu_mesh_shape.model_parallelism = 4" 
```

**Comment by craffel** [comment]
You should create a `TextLineTask` https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/dataset_providers.py#L1050 and use its name in place of "wikipedia_20190301.en_v003_unsupervised" in your command. However, reading from text files on GCS may be slow; you might want to cache it first https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/cache_tasks_main.py

**Comment by dpanshu** [comment]
@craffel , I am getting the following warning when caching , my data set is 10B lines 
```
2020-12-15 00:22:37,301 program=BlobbySync pid=223 loc=sync_planner.py:57	INFO: Adding changed path to SyncPlanner: /mnt/task_wrapper/user_output/logs/system/console
2020-12-15 00:22:44,362 program=system_usage_metrics pid=413 loc=system_metrics.py:260	WARNING: disk_usage=37.77% cpu_usage=7.2% memory_usage=99.96%
2020-12-15 00:23:14,332 program=system_usage_metrics pid=413 loc=system_metrics.py:260	WARNING: disk_usage=37.77% cpu_usage=7.4% memory_usage=99.96%
```
