### ISSUE TITLE
Segmentation fault when importing t5

### ISSUE THREAD

**Issue by yuvalkirstain** [google-research/text-to-text-transfer-transformer#58]
hey, 
I pip installed t5.
When I try to import t5 I get a Segmentation fault.

**Comment by craffel** [comment]
Hi, I wouldn't expect anything in t5 to cause a segmentation fault as it's basically pure Python. I bet one of the libraries that t5 imports is causing a segmentation fault. You should try importing all of the libraries installed for t5, listed here:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/setup.py#L39
If one of those libraries causes a segfault on import then please open an issue on that library. If you can import all of those libraries without a seg fault then please reopen this issue.
