### ISSUE TITLE
Pretrained weights for Shared Encoder-Decoder

### ISSUE THREAD

**Issue by j-min** [google-research/text-to-text-transfer-transformer#581]
Hello,

Could you please share the pretrained weights of T5-base model that shares encoder and decoder weights (2nd row)?
Also, it would be helpful if you could clarify which components are shared(ex. self-attention weights, relative position embeddings, layer norms).
![image](https://user-images.githubusercontent.com/18069263/102039030-bcfcb980-3d96-11eb-903b-e598e23a63c9.png)

**Comment by craffel** [comment]
Hey Jaemin, note that the shared model is not T5-Base, it's just the baseline from the paper (so, it was pre-trained for a lot less time, and it was trained on a slightly-worse objective on unlabeled data only, etc - basically works quite a bit worse than T5-Base). All parameters that could be shared were shared (so, everything except encoder-decoder attention). If you are still interested in that checkpoint, I can dig it up for you.

**Comment by j-min** [comment]
Oh thanks for pointing the training differences, I just re-read the Sec.3.7 and found the difference with the models in the table and T5-base.
But yes, I'm still interested in the checkpoint anyways.
I'm working on fine-tuning shared encoder-decoder models on seq2seq tasks. I tried copying T5-base decoder weights to encoder and tying them, but it didn't work well. I'd like to see if shared enc-dec initialization helps a bit even though it's not trained as long as T5-base.

**Comment by craffel** [comment]
Hi Jaemin, I copied the checkpoint to gs://t5-data/tmp. Please copy it elsewhere and let me know when you've done so, and I will go ahead and delete it.

**Comment by j-min** [comment]
Just downloaded the checkpoints, thanks!
If you later have plan to do additional experiments like T5 v1.1, please consider including a shared enc-dec version :)
It would help community seeking models with less memory (like myself) and [this paper](https://arxiv.org/pdf/2003.01473.pdf) found it helpful to share enc-dec for image captioning.
