### ISSUE TITLE
benchmarking inference times for t5 models

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#593]
Is there any benchmarking available for t5 models of various sizes on CPUs and GPUs? I got the following numbers on 16 GB GPU
T5 small: 100ms
T5 base: 150ms
T5 large: 250ms
T5 3B: 500ms
Do these look reasonable? 
Also in your experience what are the biggest bottlenecks in inference performance.
1) Sequence Length (Model specified parameter)
2)Input Length (Input length for one example)
3) Decoder Output Length(Output length for an example)

Are they any good ways to improve the latency which can be suggested here?

**Comment by craffel** [comment]
Hi, we have not benchmarked inference speed on GPUs whatsoever. During inference, the decoder is the bottleneck because sampling is not parallelizeable across time.
