### ISSUE TITLE
Generating multiple output for same query

### ISSUE THREAD

**Issue by dpanshu** [google-research/text-to-text-transfer-transformer#606]
Hi, 

I am trying to generate multiple hypothesis given a single input. Say for conversational system, my training data has following data 
```
input: How are you? 
output1: I am doing good. 

input: How are you? 
output1: I had a busy day
```

Now, during inference time, I would like to generate multiple output for same input. How can I do that in T5?

**Comment by craffel** [comment]
If you use a stochastic sampling strategy (e.g. not greedy sampling), each time you decode from the model it will sample a new (possibly different) output. There is no way to force it to generate different outputs, though - it is random.

**Comment by dpanshu** [comment]
@craffel is there a gin file on the sampling strategy ?

**Comment by craffel** [comment]
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/gin/sample_decode.gin

**Comment by dpanshu** [comment]
What variable is need to be changed to implement stochastic sampling instead of beam=1 greedy decoding
?

**Comment by craffel** [comment]
The file I posted.

**Comment by dpanshu** [comment]
Thanks

**Comment by dpanshu** [comment]
Can I generate multiple output with exported model "saved_model.pb" as well ?

**Comment by stefanondisponibile** [comment]
hey @dpanshu did you figure out if that sampling strategy is exportable also in the SavedModel format?

**Comment by dpanshu** [comment]
@stefanondisponibile, I think you can use `--export_temperature`, when running the export API here: https://github.com/google-research/text-to-text-transfer-transformer#export

**Comment by stefanondisponibile** [comment]
thank you!
