### ISSUE TITLE
training translation task with multiple options for the same input

### ISSUE THREAD

**Issue by vkaul11** [google-research/text-to-text-transfer-transformer#608]
How can I use my training data with two possible outputs for the same input in case of machine translation task from Spanish->English. Say "Cómo está usted?"-> "How are you?" and  "Cómo está usted?" -> "How do you do?". 
How do I use both examples in training or do I have to pick only one always? I don't seem to get the errors to  converge if I use both examples separately.

**Comment by craffel** [comment]
You can use both examples in your training data, this is quite common.

**Comment by vkaul11** [comment]
So just feed them as separate examples at training time ? Thanks. Can we use the same scheme for multi-label classification problem. For example if we have to find an utterance category among several categories and we have examples that have multiple categories.  "What is Harry Potter" -> "Book" and "What is Harry Potter" -> "Movie" where "Book" and "Movie" are separate categories. So we can just need them as separate examples at training time and then use beam search or top k decoding at inference time with thresholds to find multiple categories or is there some better way to handle a multi-label problem?

**Comment by craffel** [comment]
Yes, that is fine. I would recommend computing the log probability of each possible label at test time, and using those for scores.

**Comment by vkaul11** [comment]
So basically limit the decoder output to the classification categories we have at test time instead of using the entire vocabular?

**Comment by craffel** [comment]
You can do that too, but I was just referring to computing the log probs.

**Comment by vkaul11** [comment]
But how do I extract log probs from the decoder? It is a Vocabulary * T (time steps matrix) right ? How to isolate and compute the log probability on the decoder side.

**Comment by craffel** [comment]
Use one of the score modes from the MTF transformer.

**Comment by vkaul11** [comment]
Thanks a lot for your help. Besides the score mode,  I guess we need to dig deeper into MTF transformer code to restrict the decoder outputs to certain tokens also?
