### ISSUE TITLE
How T5 handles COPA and other multiple choice datasets 

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#611]
Hi
I found the description of COPA in the paper as below:

```
Original input:
Question: effect
Premise: Political violence broke out in the nation.
Choice 1: Many citizens relocated to the capitol.
Choice 2: Many citizens took refuge in other territories.
Processed input: copa choice1: Many citizens relocated to the capitol. choice2:
Many citizens took refuge in other territories. premise: Political violence
broke out in the nation. question: effect
Original target: 1
Processed target: True
```
1) T5 concatenates all candidates answers and then for the target it uses "true"? I did not get how this is working since the target to be needs to be 1.

2) If the number of choices are more than two, could you please assist in saying how T5 convert multiple choice datasets? Assuming commonsense_qa, there are answers list of A-E and then one is correct, could you tell me how the correct seq2seq format for this dataset for T5? shall I add the choices as A:ignore, ... to the input sequence? 

```
Question:The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change? 
{ "label": [     "A",     "B",     "C",     "D",     "E"   ],   "text": [     "ignore",     "enforce",     "authoritarian",     "yell at",     "avoid"   ] }
answer: A
```
 thanks

**Comment by craffel** [comment]
1. False means choice1 and True means choice2. It's a bit funky but we just used our standard way of converting binary classification tasks, which is what COPA is.
2. The task format is totally up to you, there is no specific way that T5 converts multiple choice datasets. But yes, I would do something like 

inputs = "question: The sanctions against the school were a punishing blow, and they seemed to what the efforts the school had made to change? ? choice A: ignore choice B: enforce ..."
targets: "ignore"

**Comment by adarob** [comment]
You could consider using the rank_classification preprocessor.
