### ISSUE TITLE
unsupervised Fine tuning 

### ISSUE THREAD

**Issue by mlnlpenthusiast** [google-research/text-to-text-transfer-transformer#612]
Hello, I apologize if this question is already answered. 
I was wondering if T5 can be fine tuned with domain specific data . Intention is to perform unsupervised fine tuning without specific to any task. Please provide any examples if you have any

thank you

**Comment by craffel** [comment]
Hi, yes, this is possible and simple and we have done it in the past. The easiest way to do it is to create a new task exactly like this one:
https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L42
but with a different tfds_name (or if you want to use a TextLineTask or some other non-TFDS type, just change the task type).
