### ISSUE TITLE
 Layer normalization

### ISSUE THREAD

**Issue by pvop** [google-research/text-to-text-transfer-transformer#613]
In Section 2.1, "We use a simplified version of layer normalization where the activations are only rescaled and no additive bias is applied". I wonder why this change was made. For speed or better result?
Thank you for your time!

**Comment by craffel** [comment]
Yes, it makes very little difference in terms of final model quality but is marginally faster. The additive bias is simply unnecessary. This paper proposes a similar thing with similar findings: https://arxiv.org/abs/1910.07467
