### ISSUE TITLE
Question on SentencePiece and T5

### ISSUE THREAD

**Issue by dkamalakar** [google-research/text-to-text-transfer-transformer#630]
Hello, This is more of a curious question than anything else. Since T5 uses SentencePiece for embedding, I was wondering if it will have adverse impact when using domain specific tokens ? SentencePiece paper talks about lossless tokenization and I belive it confirms that there wont be issue. I am planning to review sentiencepiece in details, but wanted to raise it here

Thank you for your feedback

**Comment by craffel** [comment]
The model used for T5 did not have byte fallback enabled, so it is not lossless. If you want a model that can do lossless tokenization, you should use mT5, which has byte fallback enabled.

**Comment by dkamalakar** [comment]
Thank you for your response
I might have Mia understood lossless training
I am not really interested in multi lingual model
My question mostly was around ability for domain adaptation using T5. In other words, will I be able to pre train T5 using domain specific data ? My data may contain tokens specific to my domain and want to make sure sentence piece will not mess it up 

Thanks

**Comment by craffel** [comment]
> I am not really interested in multi lingual model

mT5 works as well as T5 on English data.

> will I be able to pre train T5 using domain specific data

Yes.

> My data may contain tokens specific to my domain and want to make sure sentence piece will not mess it up

The sentencepiece model in T5 is not lossless, the one in mT5 is lossless. I don't know what your special tokens are so I have no idea if the T5 sentencepiece model will mess them up or not.
