### ISSUE TITLE
Pre-train on custom masked dataset

### ISSUE THREAD

**Issue by antoniomastro1996** [google-research/text-to-text-transfer-transformer#632]
Hi everybody!

Basically, I want to pre-train T5 on a dataset I've already masked(I.e: I have the masked input with <extra_id_XX> tokens and the labels).

input =  'The <extra_id_0> walks in <extra_id_1> 
output = '<extra_id_0> cute dog <extra_id_1> the <extra_id_2>'

Is this possible with your implementation?

Thanks in advance!

**Comment by craffel** [comment]
Yes, this should work. If it doesn't, let us know.

**Comment by adarob** [comment]
You will need to install from the repo, however, because extra_id is not
yet supported in the pip package.
