### ISSUE TITLE
Imbalanced Data Question - T5 finetuning

### ISSUE THREAD

**Issue by dkamalakar** [google-research/text-to-text-transfer-transformer#633]
Hello, A question regarding the multi task fine tuning. Suppose I continue to fine tune my model for multi task but one kind of task has significantly low data compared to other tasks...does it make the task with less data perform worst than the data which has more data ? I guess my question is, even though you fine tune for different task types are they somehow related ?

**Comment by craffel** [comment]
It is typically the case that a task with less data will perform worse than a task with more data. In multi-task learning, if one task has a small training dataset and another has a large training dataset and they are similar tasks, you can often see benefits in the limited-data task. UnifiedQA provides some example of this effect https://arxiv.org/abs/2005.00700
