### ISSUE TITLE
layer norm and residual path 

### ISSUE THREAD

**Issue by pvop** [google-research/text-to-text-transfer-transformer#637]
In page 5 of paper, "placing the layer normalization outside the residual path". 
But in mesh tensorflow, I found 
"self._sublayers_per_layer = [sublayer_legacy_rms_norm,
                                 sublayer_call_layer,
                                 sublayer_legacy_dropout,
                                 sublayer_residual]".
This means layer_norm -> sub_layer -> dropout -> residual -> layer_norm -> ..., which is same as transformer.
I don't know where to place layer normalization and the relationship between layer norm and residual path.
Thank you for your time!

**Comment by craffel** [comment]
sublayer_residual adds the layer's original input:
https://github.com/tensorflow/mesh/blob/master/mesh_tensorflow/transformer/transformer.py#L552
The computation is
x = input
x = layer_norm(x)
x = sub_layer(x)
x = dropout(x)
x = x + input
The original Transformer is
input = layer_norm(input)
x = input
x = sub_layer(x)
x = dropout(x)
x = x + input
Please review the code in the Transformers library if it is not still clear.

**Comment by albertz** [comment]
In Tensor2Tensor, there is a comment:
```
# TODO(noam): The current settings ("", "dan") are the published version
# of the transformer.  ("n", "da") seems better for harder-to-learn
# models, so it should probably be the default.
layer_preprocess_sequence="none",
layer_postprocess_sequence="dan",
```
Where d: dropout, n: layernorm, a: add. So as I understand this, the original Transformer does actually:
```python
x = sub_layer(input)
x = dropout(x)
x = x + input
x = layer_norm(x)
```
However, @craffel's code is basically the same when you consider the last op as the first op for the next sub layer.
But I wonder for the very first and very last sub layer, whether layer-norm is applied. I think the very first layer would not have layer-norm on the input.
