### ISSUE TITLE
Getting error on GPU

### ISSUE THREAD

**Issue by KVSAkhilesh** [google-research/text-to-text-transfer-transformer#640]
Hi Team,

I am running T5-large pretrained model for summarizer  in AWS EC2 instance. But I am getting error in model.generate step.
Could you please help to solve this issue.
Please find the below screenshot for reference. 
Thanks in advance.

![image](https://user-images.githubusercontent.com/44360141/104083334-ca0cab80-5263-11eb-9bac-4e5892949297.png)
![image](https://user-images.githubusercontent.com/44360141/104083335-cf69f600-5263-11eb-889b-7b66a748641e.png)
![image](https://user-images.githubusercontent.com/44360141/104083338-d3961380-5263-11eb-932c-5ab5bbcdb119.png)

**Comment by adarob** [comment]
It looks like you're using the HuggingFace implementation. Please file an issue with them.
