### ISSUE TITLE
Missing some operative_config.gin

### ISSUE THREAD

**Issue by sarapapi** [google-research/text-to-text-transfer-transformer#645]
Hi all,
I've noticed that some gin files in your google cloud folder are missing, like in mT5/large-xl-xxl or t5.1.1.large  while in small and base are present. 
Why?
Thanks

**Comment by craffel** [comment]
I'm not sure what you mean - the operative configs are there for all models, e.g.
https://console.cloud.google.com/storage/browser/_details/t5-data/pretrained_models/t5.1.1.large/operative_config.gin
https://console.cloud.google.com/storage/browser/_details/t5-data/pretrained_models/mt5/large/operative_config.gin
etc.

**Comment by sarapapi** [comment]
Sorry, my explanation was terrible, I mean that using mT5 for example I get this error message:
`ERROR:root:Path not found: gs://t5-data/pretrained_models/mt5/large/operative_config.gin`
but effectively if I verify with `gsutil` the file is present in your storage, of course.

**Comment by craffel** [comment]
I assume this means that the machine that your Python job is running on does not have the Python Cloud API set up/installed correctly.

**Comment by sarapapi** [comment]
> I assume this means that the machine that your Python job is running on does not have the Python Cloud API set up/installed correctly.

After I forced a reinstall from the t5 repo (even if I made an upgrade this morning), it works, I don't know why.  Thanks anyway!

**Comment by ruiqi-zhong** [comment]
I also had the same issue, and it's also present in this colab tutorial: https://tiny.cc/t5-colab . Would you mind giving hints on how to fix this? Thanks!

**Comment by sarapapi** [comment]
> I also had the same issue, and it's also present in this colab tutorial: https://tiny.cc/t5-colab . Would you mind giving hints on how to fix this? Thanks!

It worked for me downgrading gin to 0.4.0

**Comment by alirezasalemi7** [comment]
any solution for this issue? I get this error when I try to fine-tune this model on colab. as suggested I should downgrade gin to 0.4.0 but how should I do that?

**Comment by alirezasalemi7** [comment]
> > I also had the same issue, and it's also present in this colab tutorial: https://tiny.cc/t5-colab . Would you mind giving hints on how to fix this? Thanks!
> 
> It worked for me downgrading gin to 0.4.0

any solution for this issue? I get this error when I try to fine-tune this model on colab. as suggested I should downgrade gin to 0.4.0 but how should I do that?

**Comment by adarob** [comment]
That error message is a red herring. This should be fixed by https://github.com/google-research/text-to-text-transfer-transformer/pull/768
