### ISSUE TITLE
Getting unknown symbols (??) in the eval step ?

### ISSUE THREAD

**Issue by mellahysf** [google-research/text-to-text-transfer-transformer#657]
Hi,

I used T5 as described in colab, in a text-to-text task.

The fine-tune phase seems good, and the predictions file is generated in the eval step, but some lines with unknowing symbols!!

Exemple 1 :
Expected output: a < b 
predicted output (from the file generated with model.eval() method): a ?? b 

Exemple 2 :
Expected output: date = 01-01-1995
predicted output (from the file generated with model.eval() method): date = 01??01??1995

It's very urgent, please.

Thank you very much.

**Comment by craffel** [comment]
Hi, the T5 sentencepiece vocabulary does not have the token "<" in it, so it is unknown and decodes to ??. For your hyphens, I assume the actual text has some kind of unusual unicode hyphen that it also does not have. We created the T5 vocabulary before the byte-fallback feature was implemented in sentencepiece (which allows any text sequence to be tokenized). The mT5 vocabulary has byte-fallback enabled, so if you want to be able to tokenize any character you should use mT5.

**Comment by mellahysf** [comment]
Thank you @craffel  for your reply.

I treated the case of "<" by replacing it with the word "inferior" and do the reverse in predictions, it works perfectly

Now I have other tokens that are not well decoded like:

Exemple1:
Expected: győri 
Predicted: gy ⁇ ri

Exemple2:
Expected: kyrkjebø
Predicted: kyrkjeb ⁇

Exemple3:
Expected: yuming lai (賴銘偉)
Predicted: yuming lai ( ⁇ )

Thank you very much for the help.

**Comment by craffel** [comment]
The T5 vocabulary was only built on English, Roman, and German text, and  T5 was only trained on English data. If you want to process multlingual data, you should use mT5.

**Comment by mellahysf** [comment]
ok I see @craffel .

I work with T5 in colab and it work perfectly.

And now, I don't know if there is a colab for mt5 fine-tuning? ideally for translation task ?

Thank you very much @craffel again!

**Comment by craffel** [comment]
Any colab for T5 will work fine with mT5, just change the checkpoint/operative config.

**Comment by mellahysf** [comment]
Ok, I'm doing it.

And in the phase of finetune (model.fintune method), it gives me the error below:

ValueError: Shape of variable decoder/logits/kernel:0 ((1024, 32128)) doesn't match with shape of tensor decoder/logits/kernel ([1024, 250112]) from checkpoint reader.

any idea about it, please?

**Comment by craffel** [comment]
It looks like you changed the model checkpoint path but not the operative config.

**Comment by mellahysf** [comment]
yes, it works now. 

Thank you soo much @craffel
