### ISSUE TITLE
Prefix of unsupervised span prediction task in multi-task pretraining

### ISSUE THREAD

**Issue by j-min** [google-research/text-to-text-transfer-transformer#667]
Hi, I found the released T5 models have ability of span prediction and some downstream tasks (ex. summarization, translation) without further finetuning thanks to multi-task pretraining.
Did you try using prefix for original span prediction task to disambiguate it from other tasks? Or simply not using prefix just worked?

**Comment by craffel** [comment]
Hey Jaemin, no, there is no prefix - it is easy for the model to figure out that it is the span corruption task given that it is the only task that uses the special sentinel tokens.

**Comment by puraminy** [comment]
how special sentinel tokens work? In a zero shot and also finetuning I tried to use `<extra_id_0>` in the input but it seems `t5` doesn't attend to it and it works as if it's not there (like LM objective)

I tried to add them like these:

```
extra_tokens = ["<xIntent>", "<xNeed>", "<xAttr>", "<xReact>",
        "<xIntent_0>", "<xIntent_1>", "<xIntent_2>", "<gen_en>",
        "<extra_id_0>", "<extra_id_1>", "<extra_id_2>", "<extra_id_3>",
        "<xIntent_3>", "<xIntent_4>",
        "<xNeed_0>", "<xNeed_1>", "<xNeed_2>", "<xNeed_3>", "<xNeed_4>",
        "<Attr_0>", "<xAttr_1>", "<xAttr_2>", "<xAttr_3>", "<xAttr_4>",
        "<xReact_0>", "<xReact_1>", "<xReact_2>", "<xReact_3>", "<xReact_4>"]

T5_DEFAULT_VOCAB = t5.data.SentencePieceVocabulary(T5_DEFAULT_SPM_PATH, extra_tokens=extra_tokens) 
```
