### ISSUE TITLE
Converting to tensorflow.js

### ISSUE THREAD

**Issue by JEF1056** [google-research/text-to-text-transfer-transformer#668]
I would like to convert the tensorflow savedmodel generated after exporting the model in https://colab.research.google.com/github/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb
to a tensorflow.js compatable model. However it seems like SentencepieceOp from tensorflow-text is an op builtin to the model, making it impossible to run .
```
tensorflowjs_converter  \
    saved_model_path \
    "output path" \
    --input_format tf_saved_model \
    --output_format tfjs_graph_model
```
even with the --skip_op_check flag

Update: With some success, I was able to add `import tensorflow_text` into the code that launches tensorflowjs_converter, which allowed the converter to run. However, it appears that the following operations are still not supported in tensorflow.js:
```
TensorSliceDataset, ReadVariableOp, ParallelMapDatasetV2, SentencepieceDetokenizeOp, VarHandleOp, DatasetToSingleElement, SentencepieceOp, BatchDatasetV2
```

**Comment by lukemovement** [comment]
Has there been any update on this issue? Most of the models on tfhub cannot be converted due to verious issues with missing layers.

**Comment by JEF1056** [comment]
Ah, I haven't updated this for quite some time -  these missing layers are mostly due to things like sentencepiece and dataset processing being integrated into the model;
It isn't really feasable to add these ops into tfjs, and so this isn't being worked on. I would look to newer solutions, such as Huggingface's transformers.js repo for being able to run T5 in nodejs or in the browser
