### ISSUE TITLE
Sentence embedding using T5

### ISSUE THREAD

**Issue by Two-Days** [google-research/text-to-text-transfer-transformer#669]
Hi. I would like to use T5 pretrain model to get sentence embedding vector, it can be achieved? if I can, how can I do it?

**Comment by craffel** [comment]
No, T5 does not produce sentence embeddings.

**Comment by Elfsong** [comment]
You can take the `last_hidden_state` from the T5 encoder output:

`model = T5Model.from_pretrained("t5-small")
tok = T5Tokenizer.from_pretrained("t5-small")

enc = tok("some text", return_tensors="pt")

# forward pass through encoder only
output = model.encoder(
    input_ids=enc["input_ids"], 
    attention_mask=enc["attention_mask"], 
    return_dict=True
)
# get the final hidden states
emb = output.last_hidden_state`

Ref from: https://discuss.huggingface.co/t/how-to-use-t5-for-sentence-embedding/1097

**Comment by guotong1988** [comment]
https://arxiv.org/abs/2108.08877
