### ISSUE TITLE
How can I do cross validation ? 

### ISSUE THREAD

**Issue by mellahysf** [google-research/text-to-text-transfer-transformer#674]
I have 3 set: Train, Dev and Test Set and I want to train with the Train Set, and do cross validation with the Dev Set then evaluate on Test Set.

How can I do the cross validation on the Dev Set with T5?

Thanks,

**Comment by craffel** [comment]
If you mean simply evaluating performance on the dev set, you just need to run eval, specifying the appropriate split:
https://github.com/google-research/text-to-text-transfer-transformer#eval
If you want to do k-fold cross validation, you need to create k different tasks, where each task uses a different subset of the data. You can specify the subset via splitting notation when constructing the task, e.g.:
https://github.com/google-research/google-research/blob/master/t5_closed_book_qa/t5_cbqa/tasks.py#L54
