### ISSUE TITLE
getting error while exporting model

### ISSUE THREAD

**Issue by shreyasdantkale** [google-research/text-to-text-transfer-transformer#676]
I successfully fine tuned and able to use model with predictions.
But while exporting getting error mentioned below.
It is trying to fetch task named "all_mix" not mentioned by me.

you can get my code here.
https://colab.research.google.com/drive/1m-m6AaEo7SqaoRfA7hI-w4WCLOpnSZzh#scrollTo=micz4zR7sdfq

### **Error:**

ValueError                                Traceback (most recent call last)
<ipython-input-28-468c56e6b2af> in <module>()
      4     checkpoint_step=-1,  # use most recent
      5     beam_size=1,  # no beam search
----> 6     temperature=1.0  # sample according to predicted distribution
      7 )
      8 print("Model saved to:", saved_model_path)

2 frames
/usr/local/lib/python3.6/dist-packages/t5/models/mtf_model.py in export(self, export_dir, checkpoint_step, beam_size, temperature, keep_top_k, vocabulary, eval_with_score)
    533 
    534     if vocabulary is None:
--> 535       vocabulary = utils.get_vocabulary()
    536     model_ckpt = "model.ckpt-" + str(checkpoint_step)
    537     export_dir = export_dir or self._model_dir

/usr/local/lib/python3.6/dist-packages/t5/models/utils.py in get_vocabulary(mixture_or_task_name)
    180       logging.warning("Could not extract mixture/task name from gin config.")
    181   if mixture_or_task_name:
--> 182     provider = t5.data.get_mixture_or_task(mixture_or_task_name)
    183     features = provider.output_features
    184     if "inputs" in features and "targets" in features:

/usr/local/lib/python3.6/dist-packages/t5/data/dataset_providers.py in get_mixture_or_task(task_or_mixture_name)
   1439   else:
   1440     raise ValueError("No Task or Mixture found with name: %s" %
-> 1441                      task_or_mixture_name)
   1442 
   1443 

ValueError: No Task or Mixture found with name: all_mix

**Comment by adarob** [comment]
Try doing `import t5.data.mixtures` before calling the export method.
