### ISSUE TITLE
TextLineTask Usage

### ISSUE THREAD

**Issue by Sujit27** [google-research/text-to-text-transfer-transformer#683]
I want to use TextLineTask for a translation fine tuning. My source txt file has one sentence per line and target file has corresponding sentences per line in target language. How should I add this task to the TaskRegistry, is it something close to the following code ?
```
t5.data.TaskRegistry.add(
    "combined_data",
    t5.data.TextLineTask
    tfds_name={'train':<data file_path>},
    text_preprocessor=preprocessors.translate,
    output_features=DEFAULT_OUTPUT_FEATURES,
    metric_fns=[])
```

**Comment by craffel** [comment]
You can see an example of using TextLineTask here: https://tiny.cc/t5-colab

**Comment by Sujit27** [comment]
Thank you.
