### ISSUE TITLE
what exactly does tokens_per_batch mean?

### ISSUE THREAD

**Issue by sumanthd17** [google-research/text-to-text-transfer-transformer#684]
## This is not an issue but a query.

What exactly does the gin_param `tokens_per_batch` mean?

In my case I'm using a `tokens_per_batch` value of `8192` with` input sequence length 128` and `output sequence length 128`

Does this mean we are processing `8192/(128+128)` == `32` examples for each step?

Or am I missing something?

Also is there a good `tokens_per_batch` number to use for fine-tuning, I'm using `TPU v3-8` for the fine-tuning

Thanks in Advance

**Comment by craffel** [comment]
It is `max(n_input_examples*input_sequence_length, n_output_examples*output_sequence_length)`. So, in your example, you'd have 64 examples per batch. There is no good number to use, it depends on your available memory.

**Comment by sumanthd17** [comment]
@craffel 

Does this mean the 64 examples are shared by 8 cores? (`i.e 8 examples for each core`)

Also in 1 step we process 64 examples right? i.e for each step the 64 examples are processed by 8 cores

**Comment by craffel** [comment]
> Does this mean the 64 examples are shared by 8 cores?

It depends on how you specify model/data parallelism.

> Also in 1 step we process 64 examples right?

Yes.

**Comment by sumanthd17** [comment]
During fine-tuning I'm using this gin_param `utils.tpu_mesh_shape.model_parallelism = 1` to define model parallelism and not leaving data parallelism to the default value.

How would the data be used in this case?

**Comment by craffel** [comment]
The batch will be split evenly across the cors.
