### ISSUE TITLE
pretraining T5 model 

### ISSUE THREAD

**Issue by juliahane** [google-research/text-to-text-transfer-transformer#693]
Dear T5 authors, 
I would like to pretrain your model, using huggingface repo though, could you kindly confirm shall I use "masked language model loss" or "causal language model loss" and which one can simulate your pretraining phase? thank you very much

**Comment by craffel** [comment]
Hi Rabeeh, you should use this task: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/tasks.py#L47
You can feed a task in to the HF model as shown here: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/models/hf_model.py
