### ISSUE TITLE
input format required for span_corruption preprocessor

### ISSUE THREAD

**Issue by dorost1234** [google-research/text-to-text-transfer-transformer#701]
Hi
I was wondering if you could help me understand input format required for span_corruption, please see my closed issue here:
https://github.com/google-research/text-to-text-transfer-transformer/issues/698

I was not sure how to reopen it and I made this issue for this, I included my minimal example and errors, in this function the input format is not documented, could you assist me understanding how I should call this function. I really need to understand this and appreciate having a look. thanks

**Comment by dorost1234** [comment]
Hi @craffel @adarob  I really have a hard time with this function, could not figure out sofar how the format shouldbe, could you please explain and document how the format of input to span_corruption should be? Do you mind having a look into my exmaples in bug #698 ?  thanks

**Comment by craffel** [comment]
Hi, here is an example where the inputs are articles from the CNNDM dataset:
https://colab.research.google.com/drive/1-oAupD_NVUT9mynSxrH8PkN5V7LaFWxE?usp=sharing
