### ISSUE TITLE
"Bad hardware status" with T5 11B model

### ISSUE THREAD

**Issue by swarooprm** [google-research/text-to-text-transfer-transformer#767]
On a v3-8 TPU (software version 2.2), I am getting the following error while trying to train the T5 11B model, however the T5 small model works fine.
Bad hardware status: Queue is closed.
	 [[node OutfeedDequeueTuple (defined at /site-packages/tensorflow_estimator/python/estimator/tpu/tpu_estimator.py:2220) ]]

**To Reproduce**
python -m t5.models.mesh_transformer_main \
      --module_import="t5_tasks" \
      --tpu="${TPU_NAME}" \
      --gcp_project="${PROJECT}" \
      --tpu_zone="${ZONE}" \
      --model_dir="${MODEL_DIR}" \
      --gin_file="dataset.gin" \
      --gin_file="${PRETRAINED_DIR}/operative_config.gin" \
      --gin_param="utils.run.save_checkpoints_steps=1000" \
      --gin_param="utils.tpu_mesh_shape.tpu_topology = 'v3-8'" \
      --gin_param="MIXTURE_NAME = 'training_mix_full'" \
      --gin_param="utils.run.batch_size=('tokens_per_batch', 8192)" \
      --gin_param="utils.run.train_steps=$((PRETRAINED_STEPS + FINETUNE_STEPS))" \
      --gin_param="utils.run.init_checkpoint='${PRETRAINED_DIR}/model.ckpt-${PRETRAINED_STEPS}'" \
      --gin_param="utils.tpu_mesh_shape.model_parallelism = 8" \
      --t5_tfds_data_dir="${BUCKET}/t5-tfds"

**Comment by craffel** [comment]
This is likely because the TPU OOMed. T5-11B will not fit on a v3-8 unless you have a very short sequence length/very tiny batch.

**Comment by swarooprm** [comment]
Thank you Colin! I am able to run it with 4096 token per bath.
