### ISSUE TITLE
Request for link to SeqIO repo.

### ISSUE THREAD

**Issue by quocdat32461997** [google-research/text-to-text-transfer-transformer#792]
Can you share the repo for seqio. For now, there is not docs for seqio; hence, I need source codes. I still can look at previous commits. Still, officials repos are better.

**Comment by adarob** [comment]
It will be available within a week. Sorry about that.

**Comment by quocdat32461997** [comment]
@adarob 
In  **seqio** pypi website, the usage tutorial provides incorrect snippets.
The following function call "module not found" errors.
* seqio.tokenize
* seqio.append_eos
I guess you forgot imports to seqio.preprocessors.

**Comment by adarob** [comment]
Thanks for bringing this to our attention! I have fixed the README for when
we open source the code. The correct paths are
`seqio.preprocessors.tokenize` and `seqio.preprocessors.append_eos`.

**Comment by quocdat32461997** [comment]
Thanks. Meanwhile, I'll look at past commits for Seqio codes.
