### ISSUE TITLE
Can I fine-tune T5 on a Spanish question-answering dataset?

### ISSUE THREAD

**Issue by zekaouinoureddine** [google-research/text-to-text-transfer-transformer#794]
Hey,
I am trying to fine-tune **T5 Model** on a **question-answering dataset**, I would want to know if it is possible to do it for **Spanish text** or any other language using this model as it is done for English texts?

**Comment by craffel** [comment]
T5 is English-only; if you want a Spanish model you can try https://github.com/google-research/multilingual-t5. (closing issue since this is a discussion, not an issue)
