### ISSUE TITLE
Running inference

### ISSUE THREAD

**Issue by NaxAlpha** [google-research/text-to-text-transfer-transformer#80]
Hi, I am trying to run inference on exported model. I am using tensorflow serving to deploy the model. After deploying, when I send the request, I get this error:

```
out = requests.post('http://localhost:8501/v1/models/t5:predict', json=dict(inputs=['hello']))
```
Error message:

![image](https://user-images.githubusercontent.com/11090613/74251688-5211ca80-4d0e-11ea-8d20-0329cb2197ad.png)

Can anyone help me what I am doing wrong here? 
Thanks

**Comment by dadams3524** [comment]
My apologies

**Comment by adarob** [comment]
Duplicate of #92

**Comment by adarob** [comment]
@NaxAlpha did my comment in the other issue solve your issue? I realize now that it may be a different problem.

**Comment by adarob** [comment]
It looks like your answer may be in https://www.tensorflow.org/tfx/serving/api_rest. Your JSON should look like:
```
{
  // List of Example objects
  "examples": [
    {
      // Example 1
      "inputs": "hello",
    }
  ]
}
```

**Comment by NaxAlpha** [comment]
Yeah I ll look into the other issue, but my problem is to deploy T5 using TF serving. I have analyzed in-depth but still stuck. Here is my analysis so far.

First I tried as you have described but it gives this error:
![image](https://user-images.githubusercontent.com/11090613/74822454-f86d5980-5326-11ea-8468-cc6fb97a6fe3.png)

When I replace examples with inputs/instances:
![image](https://user-images.githubusercontent.com/11090613/74822541-176beb80-5327-11ea-9282-c468375a1f9f.png)
---
![image](https://user-images.githubusercontent.com/11090613/74822577-2783cb00-5327-11ea-8b76-d5b4fbfd733f.png)

I have looked into code and found out that it has to do something related to mesh tensorflow's export function. I am not entire sure but I think what is provided by TF serving cannot be provided to mesh tensorflow's export function.  

![image](https://user-images.githubusercontent.com/11090613/74826484-81878f00-532d-11ea-8ee9-3568f186b159.png)

So I also tried using this:

![image](https://user-images.githubusercontent.com/11090613/74827419-3cfcf300-532f-11ea-8ae5-eba8a8874110.png)

So this issue is currently unresolved.

**Comment by adarob** [comment]
Based on https://www.tensorflow.org/tfx/serving/api_rest, I think you want the json to be

{"inputs": ["hello"]}

**Comment by adarob** [comment]
have you tried `json={"inputs": ["hello"]}`?

**Comment by adarob** [comment]
So this looks like something that can be greatly simplified by removing the tf.Example from our SavedModel export. I will look into it today.

**Comment by NaxAlpha** [comment]
> have you tried `json={"inputs": ["hello"]}`?

Yeah already tried it.

![image](https://user-images.githubusercontent.com/11090613/74900929-16889780-53c3-11ea-88c5-bde8c7dbef05.png)



> So this looks like something that can be greatly simplified by removing the tf.Example from our SavedModel export. I will look into it today.

Thanks, looking forward to it

**Comment by NaxAlpha** [comment]
Just upgraded to latest version. Now the error is at least consistent in both cases i.e. tensorflow serving and using saved model via APIs:
TFX:
```
2 root error(s) found.
  (0) Invalid argument: Input to reshape is a tensor with 512 values, but the requested shape has 32768
	 [[{{node Reshape}}]]
	 [[SentenceTokenizer/RaggedFromTensor/Reshape/_1163]]
  (1) Invalid argument: Input to reshape is a tensor with 512 values, but the requested shape has 32768
	 [[{{node Reshape}}]]
0 successful operations.
0 derived errors ignored.
```
SavedModel:
```
InvalidArgumentError:  Input to reshape is a tensor with 512 values, but the requested shape has 32768
	 [[node Reshape (defined at <ipython-input-2-c4be6460dc7f>:3) ]] [Op:__inference_pruned_42949]

Function call stack:
pruned
```
Plus model load time was really fast this time!!! like 2 minutes down to 10-20 seconds

**Comment by NaxAlpha** [comment]
On a side note (might be helpful) I am not using vanilla model rather I have fine-tuned it on custom dataset with io shape:
``` python
{'input': 512, 'output': 8}
```

**Comment by adarob** [comment]
I'm working on an example at the end of the colab. I'll add it n the next few hours.

**Comment by adarob** [comment]
check out https://github.com/google-research/text-to-text-transfer-transformer/pull/100

**Comment by NaxAlpha** [comment]
Thanks, I'll check it and share the update

**Comment by NaxAlpha** [comment]
This actually works on TPU and is faster than predict because model is preloaded. But when running (large model 512, 32) on GPU (T4), it OOMed. both for savedmodel technique described in the example (without TPU_ADDRESS in session) and TF serving. 
```
Limit:                 14772800717
InUse:                 14745484544
MaxInUse:              14745648384
NumAllocs:                    2118
MaxAllocSize:           4211081216
```

**Comment by adarob** [comment]
Is that with batch size of 1? Have you tried to see if CPU is fast enough?

**Comment by NaxAlpha** [comment]
Thanks a lot, it worked. I could not pass batch size to model.export but when I set manually model.batch_size = 1 and exported again, it worked both on CPU and GPU.
