### ISSUE TITLE
AgWordCloudModule Issue while Build Angular Application

### ISSUE THREAD

**Issue by Vijayachandranr2020** [google-research/text-to-text-transfer-transformer#82]
Hi,

We used 'angular4-word-cloud' for word cloud graph in angular 7 application.

Issue: After importing it as 'AgWordCloudModule', there is a issue when running it on prod build. The Error showing as **' Function calls are not supported in decorators but 'AgWordCloudModule' was called.'**

Please suggest ASAP.

Thanks,
Vijay

**Comment by craffel** [comment]
Hi, I think you may be posting this issue in the wrong repo -- I don't know what "angular4-word-cloud", "word cloud graph", or "angular 7" are.
