### ISSUE TITLE
Parse Error on TriviaQA colab example

### ISSUE THREAD

**Issue by ctmckee** [google-research/text-to-text-transfer-transformer#83]
I receive the following error when I run your colab notebook cell for loading the trivia_qa data set.

ERROR:absl:Failed to construct dataset trivia_qa
ParseError: Message type "tensorflow_datasets.SplitInfo" has no field named "numBytes".
 Available Fields(except extensions): ['name', 'numShards', 'shardLengths', 'statistics']

**Comment by adarob** [comment]
Fixed, thanks!

**Comment by gabrielraya** [comment]
How did you fix it?, I am having a similar error in tfds.
