### ISSUE TITLE
t5' has no attribute 'MtfModel

### ISSUE THREAD

**Issue by antonio-mastropaolo** [google-research/text-to-text-transfer-transformer#865]
**Describe the bug**
Hello everyone!
I think the new update broke something.
I'm getting the following error: AttributeError: module 't5' has no attribute 'MtfModel'.
Could it be possible is this commit led to the problem?
 #8d48e089639b55bdfacb42ec8eb3533edc2bc837.
In other words, the version upgrade from 0.9.1 to 0.9.2

Any ideas or workaround?
Thank you all!

**Comment by adarob** [comment]
You can also do `import t5.models` and then `t5.models.MtfModel` will work.
