### ISSUE TITLE
GLUE dev set results of T5

### ISSUE THREAD

**Issue by Dopaminezsy** [google-research/text-to-text-transfer-transformer#866]
Hi folks,

Firstly, thanks for the awesome work. So who know the results of T5 on different tasks of GLUE dev set, especially T5-Base/Large's results on RTE task dev-set?

I found that there is only Table 15 in T5 paper showing the T5-Base result on GLUE dev set : 85.97. However, I want to know the detailed results of different task, which is really useful for the same reason of [another issue].(https://github.com/google-research/text-to-text-transfer-transformer/issues/24#issue-537776434)
Or are there anyone having reproduced the results of T5-Base/Large on GLUE and could share the dev results ?

Thanks for anyone's suggestions.

**Comment by Dopaminezsy** [comment]
@craffel  Hi sir, sorry to disturb you for [what you replied](https://github.com/google-research/text-to-text-transfer-transformer/issues/24#issuecomment-565674835), do you have any idea?

**Comment by craffel** [comment]
I don't have access to the validation scores anymore (I left Google). I don't know of anyone who has re-fine-tuned T5-Base/Large, but it should be straightforward to do.
