### ISSUE TITLE
Score function usage

### ISSUE THREAD

**Issue by antonio-mastropaolo** [google-research/text-to-text-transfer-transformer#872]
Hi everybody,

I have a question about the model.score function: https://github.com/google-research/text-to-text-transfer-transformer/blob/3442f91ac9dd6a0792a19da675e800e46e4bfaac/t5/models/mtf_model.py#L434

If I want to retrieve the model's confidence on a given input, does it make sense to feed the model.score function like so?
model.score(inputs=inputs, targets=predictions). Where input is the actual input file, and predictions is the file containing all the predictions obtained previously.
I am assuming that such score will further be normalized between [0, 1] range in order to retrieve the final confidence

**Comment by craffel** [comment]
Yes, that will work, but it will give you the model's assigned log-likelihood, not a confidence between 0 and 1.
