### ISSUE TITLE
For pip installed version 0.9.2 no module named t5.models

### ISSUE THREAD

**Issue by dukesun99** [google-research/text-to-text-transfer-transformer#898]
**Describe the bug**
For pip installed version 0.9.2 no module named t5.models

**To Reproduce**
1. pip install t5[gcp]
2. import t5
3. t5.models

**Expected behavior**
t5.models should exists as given in the documentation.

**Additional context**
Downgrade to 0.9.1 fixes the problem.

**Comment by adarob** [comment]
The solution is to do `import t5.models`
