### ISSUE TITLE
Recreating pretraining

### ISSUE THREAD

**Issue by iyor** [google-research/text-to-text-transfer-transformer#93]
Hi,

I am trying to pretrain the T5 model on wikipedia data, but am having some trouble. Below is a pared-down version of the pretraining script:

```python
import functools
import gin
import gin.tf
import tensorflow as tf   # Using version 1.15
import tensorflow_datasets as tfds
import t5

DATA_DIR = "~/tensorflow_datasets/"
MODEL_DIR = "./model_dir/"
TRAIN_STEPS = 1

gin.parse_config_file(f"{MODEL_DIR}/operative_config.gin")

MODEL_PARALLELISM, TRAIN_BATCH_SIZE = (2, 2)

# Enable eager execution
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.enable_eager_execution()


def wikipedia_danish(split, shuffle_files):
    wiki_train = tfds.load(
        name="wikipedia/20190301.da:1.0.0", data_dir=DATA_DIR, split="train", as_supervised=False
    )
    wiki_train = wiki_train.padded_batch(
        TRAIN_BATCH_SIZE, tf.compat.v1.data.get_output_shapes(wiki_train)
    )
    return wiki_train.batch(TRAIN_BATCH_SIZE)


t5.data.TaskRegistry.add(
    "wikipedia_danish",
    dataset_fn=wikipedia_danish,
    splits=["train"],
    text_preprocessor=functools.partial(
        t5.data.preprocessors.rekey, key_map={"inputs": None, "targets": "text"}
    ),
    token_preprocessor=t5.data.preprocessors.unsupervised,
    sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
    metric_fns=[],
)

# Define Model
model = t5.models.MtfModel(
    model_dir=MODEL_DIR,
    tpu=None,  # I am running in a GPU environment
    model_parallelism=MODEL_PARALLELISM,
    batch_size=TRAIN_BATCH_SIZE,
    sequence_length={"inputs": 512, "targets": 512},
    learning_rate_schedule=0.003,
    save_checkpoints_steps=5000,
    keep_checkpoint_max=None,
    iterations_per_loop=100,
)

model.train(mixture_or_task_name="wikipedia_danish", steps=TRAIN_STEPS)
```
(This code is mostly based off https://github.com/google-research/text-to-text-transfer-transformer/blob/3de7b8baa99b87869eef1fe0195838458a59f900/t5/data/tasks.py#L46 and https://colab.research.google.com/github/google-research/text-to-text-transfer-transformer/blob/master/notebooks/t5-trivia.ipynb#scrollTo=6rU32DjyeLuL)

My operative gin file is essentially the same as the one located at `gs://t5-data/pretrained_models/base/operative_config.gin` (I change the `MIXTURE_NAME` variable to equal `"wikipedia_danish"`).

Running the above script yields the error,
`ValueError: Task dataset has incorrect rank for feature 'targets' after text preprocessing: Got 2, expected 0`

I believe the underlying issue is related to versioning of the t5 library not playing nice with the versioning in the wikipedia dataset, however, I am unable to locate my error or an example pretraining setup. Any help would be much appreciated.

**Comment by craffel** [comment]
Hi, you shouldn't be batching the dataset in the dataset_fn.  If you are just using a dataset from TFDS, it's simpler to use a TfdsTask: https://github.com/google-research/text-to-text-transfer-transformer/blob/master/t5/data/utils.py#L687

**Comment by iyor** [comment]
Apologies for being unclear. While I am using wikipedia data in my example, my actual code does not use TFDS data (though it has been formatted in the same way as the wikipedia data). Using a TfdsTask is unfortunately not possible, if I've understood things correctly.

**Comment by iyor** [comment]
For the record, replacing the above call to `TaskRegistry.add()` with the standard way of adding a Tfds task (which, again, probably isn't applicable in my use case),
```python
t5.data.TaskRegistry.add(
    "wikipedia_danish",
    t5.data.utils.TfdsTask,
    tfds_name="wikipedia/20190301.da:1.0.0",
    text_preprocessor=functools.partial(
        t5.data.preprocessors.rekey, key_map={"inputs": None, "targets": "text"}),
    token_preprocessor=t5.data.preprocessors.unsupervised,
    sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
    metric_fns=[])
```
yields the error,
```
AttributeError: 'ShuffleDataset' object has no attribute 'output_shapes'
  In call to configurable 'pack_dataset' (<function pack_dataset at 0x14982aa70>)
  In call to configurable 'pack_or_pad' (<function pack_or_pad at 0x14971a5f0>)
  In call to configurable 'mesh_train_dataset_fn' (<function mesh_train_dataset_fn at 0x149807950>)
```
same as: https://github.com/google-research/text-to-text-transfer-transformer/issues/23#issuecomment-565703211

**Comment by adarob** [comment]
@iyor, you shouldn't be batching in your dataset fn. Instead, return individual examples.

**Comment by iyor** [comment]
The change in https://github.com/google-research/text-to-text-transfer-transformer/issues/93#issuecomment-587345369 removes calls to a user-defined dataset function. In other words, there's no batching being done. See complete code below,
```python
import functools
import gin
import gin.tf
import tensorflow as tf   # Using version 1.15
import tensorflow_datasets as tfds
import t5

DATA_DIR = "~/tensorflow_datasets/"
MODEL_DIR = "./model_dir/"
TRAIN_STEPS = 1

gin.parse_config_file(f"{MODEL_DIR}/operative_config.gin")

MODEL_PARALLELISM, TRAIN_BATCH_SIZE = (2, 2)

# Enable eager execution
tf.compat.v1.disable_v2_behavior()
tf.compat.v1.enable_eager_execution()

t5.data.TaskRegistry.add(
    "wikipedia_danish",
    t5.data.utils.TfdsTask,
    tfds_name="wikipedia/20190301.da:1.0.0",
    text_preprocessor=functools.partial(
        t5.data.preprocessors.rekey, key_map={"inputs": None, "targets": "text"}),
    token_preprocessor=t5.data.preprocessors.unsupervised,
    sentencepiece_model_path=t5.data.DEFAULT_SPM_PATH,
    metric_fns=[])

# Define Model
model = t5.models.MtfModel(
    model_dir=MODEL_DIR,
    tpu=None,  # I am running in a GPU environment
    model_parallelism=MODEL_PARALLELISM,
    batch_size=TRAIN_BATCH_SIZE,
    sequence_length={"inputs": 512, "targets": 512},
    learning_rate_schedule=0.003,
    save_checkpoints_steps=5000,
    keep_checkpoint_max=None,
    iterations_per_loop=100,
)

model.train(mixture_or_task_name="wikipedia_danish", steps=TRAIN_STEPS)
```

To be clear, removing batching (and substituting my dataset_fn with standard TFDS loading) did not solve my problem.

**Comment by adarob** [comment]
I see, I misinterpreted your issue. I'm not sure why you would be having this problem with 1.15.0, as the `output_shapes` property should still exist. However, I just opened an internal PR to update to the new `tf.data.get_ouptut_shapes` function in mesh.  I'll close this issue once it's submitted.

**Comment by iyor** [comment]
Cheers. Was the original pretraining done with this library or is code to recreate pretraining available somewhere?

**Comment by adarob** [comment]
We used the same data preprocessing code (which is where you're hitting the bug), but the training API you're using did not yet exist. Instead we used a ton of gin configs. The instructions in the README are closer to what we used.

**Comment by adarob** [comment]
I fixed the mesh issue here: https://github.com/tensorflow/mesh/commit/2085e36bff4a3da9abdd857cb3ab6bab41cf6456
