### ISSUE TITLE
The huggingface version of LM-adapted T5 v1.1 checkpoints for prompt tuning

### ISSUE THREAD

**Issue by Doragd** [google-research/text-to-text-transfer-transformer#936]
Could you provide the huggingface version of LM-adapted T5 v1.1 checkpoints for prompt tuning ?
or are there any converted scripts that can be used?
@nconstant-google

**Comment by adarob** [comment]
This would be something HuggingFace typically does. You should ask them.

**Comment by YuxiangLee1224** [comment]
Hello, how to use these models that cannot be found on huggingface？
